/*
ANSI C code generated by SmallEiffel The GNU Eiffel Compiler
Release -0.74 Beta #18 (Monday March 4th 2002)
Copyright (C), 1994-2002 - LORIA - UHP - INRIA - FRANCE
Dominique COLNET and Suzanne COLLIN - SmallEiffel@loria.fr
http://SmallEiffel.loria.fr
C Compiler options used: -pipe -O2 `sdl-config --libs`
*/
#ifdef __cplusplus
}
#endif
#include "bliss.h"
#ifdef __cplusplus
extern "C" {
#endif

T6 r96legal_col(T2 a1){
T6 R=0;
/*[IF*/
if(((a1)>=(1))&&((a1)<=((/*RF2*/((T81*)((/*RF2*/((T28*)(r96song()))->_tracks/*25*/)))->_upper/*4*/)))){
R=1;
}
/*FI]*/
return R;
}
T0*oBC17blue=NULL;
int fBC17blue=0;

T0* r96blue(void){
if(fBC17blue==0){fBC17blue=1;{
{T50*n=new50();
oBC17blue=((T0*)n);
r50make(n,0,0,127);
}
}}
return oBC17blue;
}

void r96handle_event(T96* C,T0* a1){
/*[IRF3.3put_x*/((((T22*)(((T22*)a1))))->_x/*8*/)=(((/*RF2*/(((T22*)a1))->_x/*8*/))-((/*RF2*/(C)->_offsetx/*4*/)));
/*]*/
/*[IRF3.3put_y*/((((T22*)(((T22*)a1))))->_y/*4*/)=(((/*RF2*/(((T22*)a1))->_y/*4*/))-((/*RF2*/(C)->_offsety/*8*/)));
/*]*/
r96process_event(C,a1);
}

void r96process_key(T96* C,T0* a1){
/*[IF*/
if(/*[ from line 272 of ./sdl_constant.e:*/
is_kmod((/*RF2*/(((T22*)a1))->_kmod/*24*/),192)
/* from line 272 of ./sdl_constant.e]*/
){
/*[INSPECT*/
{int z1=(/*RF2*/(((T22*)a1))->_i1/*20*/);
switch(z1){
case 101:
/*[IRF3.3put_end_beat*/((((T28*)((T28*)(r96song()))))->_end_beat/*37*/)=(r96abs_row(C,(/*RF2*/(C)->_cursorr/*28*/)));
/*]*/
break;
default:;
/*[IF*/
if(!(/*(IRF4.7is_empty*/((/*RF2*/((T81*)((/*RF2*/((T28*)(r96song()))->_tracks/*25*/)))->_first_link/*8*/))==(NULL)/*)*/)){
r96process_edit_key(C,(/*RF2*/(((T22*)a1))->_i1/*20*/));
}
/*FI]*/
}
}/*INSPECT]*/
}
else{
/*[IF*/
if(!(/*(IRF4.7is_empty*/((/*RF2*/((T81*)((/*RF2*/((T28*)(r96song()))->_tracks/*25*/)))->_first_link/*8*/))==(NULL)/*)*/)){
r96process_edit_key(C,(/*RF2*/(((T22*)a1))->_i1/*20*/));
}
/*FI]*/
}
/*FI]*/
}
T0*oBC19song=NULL;
int fBC19song=0;

T0* r96song(void){
if(fBC19song==0){fBC19song=1;{
{T28*n=new28();
oBC19song=((T0*)n);
r28make(n);
}
}}
return oBC19song;
}
T0*oBC1io=NULL;

void r96write(T96* C,T2 a1,T2 a2,T0* a3){
T0* _img=NULL;
{T48*n=new48();
/*[IRF3.1make*//*]*/
_img=((T0*)n);
}
r48render_string(((T48*)_img),a3);
/*[IRF3.6blit*/{T48* C1=((T48*)_img);
T2 b1=((/*RF2*/(C)->_offsetx/*4*/))+(a1);
T2 b2=((/*RF2*/(C)->_offsety/*8*/))+(a2);
/*[ from line 169 of ./image.e:*/
ext_blit_img((/*RF2*/(C1)->_ptr/*5*/),b1,b2);
/* from line 169 of ./image.e]*/
}/*]*/
r48free(((T48*)_img));
}

void r96move_cursor_up(T96* C,T2 a1){
/*[IF*/
if(((/*RF2*/(C)->_cursorr/*28*/))>=(a1)){
(/*SFN*/C->_cursorr/*28*/)=((/*RF2*/(C)->_cursorr/*28*/))-(a1);
}
else{
/*[IF*/
if(((/*RF2*/(C)->_originr/*24*/))>=(a1)){
(/*SFN*/C->_originr/*24*/)=((/*RF2*/(C)->_originr/*24*/))-(a1);
}
else{
(/*SFN*/C->_originr/*24*/)=0;
}
/*FI]*/
}
/*FI]*/
}

void r96draw_song(T96* C){
T2 _r=0;
T2 _c=0;
T2 _x=0;
/*[IF*/
if(!(/*(IRF4.7is_empty*/((/*RF2*/((T81*)((/*RF2*/((T28*)(r96song()))->_tracks/*25*/)))->_first_link/*8*/))==(NULL)/*)*/)){
/*[IRF3.6fill_rect*/{T96* C1=C;
T2 b1=(30)+(((/*RF2*/(C)->_cursorc/*32*/))*(60));
T2 b2=(40)+(((/*RF2*/(C)->_cursorr/*28*/))*(20));
T2 b3=60;
T2 b4=20;
T0* b5=r96blue();
/*[ from line 50 of ./window.e:*/
ext_fill_rect((b1)+((/*RF2*/(C1)->_offsetx/*4*/)),(b2)+((/*RF2*/(C1)->_offsety/*8*/)),b3,b4,(/*RF2*/(((T50*)b5))->_to_integer/*4*/));
/* from line 50 of ./window.e]*/
}/*]*/
_c=0;
while (!((_c)==((/*RF2*/(C)->_maxc/*40*/))))
{
/*[IF*/
if(r96legal_col(/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/)){
/*[IRF3.6draw_col_label*/{T96* C1=C;
T2 b1=_c;
T0* b2=/*SSWARF2*//*X30name*/(/*RF2*/((T67*)((/*RF2*/((T80*)(r81item((T81*)((/*RF2*/((T28*)(r96song()))->_tracks/*25*/)),/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/)))->_machine/*4*/)))->_name/*4*/);
r96write(C1,(30)+((b1)*(60)),20,b2);
}/*]*/
}
/*FI]*/
_c=(_c)+(1);
}
_c=0;
while (!((_c)==((/*RF2*/(C)->_maxc/*40*/))))
{
_x=/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/;
/*[IF*/
if(r96legal_col(/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/)){
_x=((30)+(((_c)+(1))*(60)))-(1);
/*[IRF3.6aalinecolor*/{T96* C1=C;
T2 b1=_x;
T2 b2=20;
T2 b3=_x;
T2 b4=((/*RF2*/(C)->_height/*16*/))-(1);
T0* b5=r96white();
/*[ from line 90 of ./window.e:*/
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 90 of ./window.e]*/
}/*]*/
}
/*FI]*/
_c=(_c)+(1);
}
}
/*FI]*/
/*[IRF3.6aalinecolor*/{T96* C1=C;
T2 b1=0;
T2 b2=(40)-(1);
T2 b3=((/*RF2*/(C)->_width/*12*/))-(1);
T2 b4=(40)-(1);
T0* b5=r96white();
/*[ from line 90 of ./window.e:*/
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 90 of ./window.e]*/
}/*]*/
/*[IRF3.6aalinecolor*/{T96* C1=C;
T2 b1=(30)-(1);
T2 b2=20;
T2 b3=(30)-(1);
T2 b4=((/*RF2*/(C)->_height/*16*/))-(1);
T0* b5=r96white();
/*[ from line 90 of ./window.e:*/
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 90 of ./window.e]*/
}/*]*/
_r=0;
while (!((_r)==((/*RF2*/(C)->_maxr/*36*/))))
{
/*[IRF3.6draw_row_label*/{T96* C1=C;
T2 b1=_r;
T0* b2=r2to_string(r96abs_row(C,_r));
r96write(C1,0,(40)+((b1)*(20)),b2);
}/*]*/
_r=(_r)+(1);
}
_r=0;
while (!((_r)==((/*RF2*/(C)->_maxr/*36*/))))
{
_c=0;
while (!((_c)==((/*RF2*/(C)->_maxc/*40*/))))
{
/*[IF*/
if(r96legal_col(/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/)){
/*[IF*/
if(r28has((T28*)(r96song()),r96abs_row(C,_r),/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/)){
r96write(C,(30)+((_c)*(60)),(40)+((_r)*(20)),r28at((T28*)(r96song()),r96abs_row(C,_r),/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+(_c)/*)*/));
}
/*FI]*/
}
/*FI]*/
_c=(_c)+(1);
}
_r=(_r)+(1);
}
_r=(((((/*RF2*/((T28*)(r96song()))->_end_beat/*37*/))*(20))/(16))-(((/*RF2*/(C)->_originr/*24*/))*(20)))+(40);
/*[IF*/
if(((_r)>=(40))&&((_r)<((/*RF2*/(C)->_height/*16*/)))){
/*[IRF3.6aalinecolor*/{T96* C1=C;
T2 b1=0;
T2 b2=_r;
T2 b3=((/*RF2*/(C)->_width/*12*/))-(1);
T2 b4=_r;
T0* b5=r96white();
/*[ from line 90 of ./window.e:*/
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 90 of ./window.e]*/
}/*]*/
}
/*FI]*/
_r=(((((/*RF2*/((T28*)(r96song()))->_beat_count/*33*/))*(20))/(16))-(((/*RF2*/(C)->_originr/*24*/))*(20)))+(40);
_r=(_r)+(((20)*((/*RF2*/((T28*)(r96song()))->_sample_mod_tick/*57*/)))/(((/*RF2*/((T28*)(r96song()))->_samples_per_tick/*65*/))*(16)));
/*[IF*/
if(((_r)>=(40))&&((_r)<((/*RF2*/(C)->_height/*16*/)))){
/*[IRF3.6aalinecolor*/{T96* C1=C;
T2 b1=0;
T2 b2=_r;
T2 b3=((/*RF2*/(C)->_width/*12*/))-(1);
T2 b4=_r;
T0* b5=r96white();
/*[ from line 90 of ./window.e:*/
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 90 of ./window.e]*/
}/*]*/
}
/*FI]*/
}

void r96make(T96* C,T2 a1,T2 a2,T2 a3,T2 a4){
r96put_geometry(C,a1,a2,a3,a4);
(/*SFN*/C->_maxc/*40*/)=(((/*RF2*/(C)->_width/*12*/))/(60))-(1);
(/*SFN*/C->_maxr/*36*/)=(((/*RF2*/(C)->_height/*16*/))/(20))-(1);
(/*SFN*/C->_originc/*20*/)=1;
}

void r96put_geometry(T96* C,T2 a1,T2 a2,T2 a3,T2 a4){
(/*SFN*/C->_offsetx/*4*/)=a1;
(/*SFN*/C->_offsety/*8*/)=a2;
(/*SFN*/C->_width/*12*/)=a3;
(/*SFN*/C->_height/*16*/)=a4;
}

void r96process_event(T96* C,T0* a1){
/*[INSPECT*/
{int z1=(/*RF2*/(((T22*)a1))->_type/*12*/);
switch(z1){
case 2:
r96process_key(C,a1);
break;
case 5:
r96process_buttondown(C,a1);
break;
}
}/*INSPECT]*/
}

T0* r96twin(T96* C){
T0* R=NULL;
R=((void*)new96());
*((T96*)R)=*C;
return R;
}
T0*oBC17white=NULL;
int fBC17white=0;

T0* r96white(void){
if(fBC17white==0){fBC17white=1;{
{T50*n=new50();
oBC17white=((T0*)n);
r50make(n,255,255,255);
}
}}
return oBC17white;
}

void r96process_edit_key(T96* C,T2 a1){
/*[INSPECT*/
{int z1=a1;
switch(z1){
case 275:
/*[IF*/
if((/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+((/*RF2*/(C)->_cursorc/*32*/))/*)*/)<((/*RF2*/((T81*)((/*RF2*/((T28*)(r96song()))->_tracks/*25*/)))->_upper/*4*/))){
/*[IF*/
if(((/*RF2*/(C)->_cursorc/*32*/))<(((/*RF2*/(C)->_maxc/*40*/))-(1))){
(/*SFN*/C->_cursorc/*32*/)=((/*RF2*/(C)->_cursorc/*32*/))+(1);
}
else{
(/*SFN*/C->_originc/*20*/)=((/*RF2*/(C)->_originc/*20*/))+(1);
}
/*FI]*/
}
/*FI]*/
break;
case 276:
/*[IF*/
if((/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+((/*RF2*/(C)->_cursorc/*32*/))/*)*/)>(1)){
/*[IF*/
if(((/*RF2*/(C)->_cursorc/*32*/))>(0)){
(/*SFN*/C->_cursorc/*32*/)=((/*RF2*/(C)->_cursorc/*32*/))-(1);
}
else{
/*[IF*/
if(((/*RF2*/(C)->_originc/*20*/))>(0)){
(/*SFN*/C->_originc/*20*/)=((/*RF2*/(C)->_originc/*20*/))-(1);
}
/*FI]*/
}
/*FI]*/
}
/*FI]*/
break;
case 281:
r96move_cursor_down(C,16);
break;
case 280:
r96move_cursor_up(C,16);
break;
case 274:
r96move_cursor_down(C,1);
break;
case 273:
r96move_cursor_up(C,1);
break;
case 48:
/*[IRF3.6put*/{T28* C1=(T28*)(r96song());
T0* b1=((T0*)se_ms(1,"0"));
T2 b2=r96abs_row(C,(/*RF2*/(C)->_cursorr/*28*/));
T2 b3=/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+((/*RF2*/(C)->_cursorc/*32*/))/*)*/;
/*[IRF3.5put*/r56put(((T56*)((/*RF2*/((T80*)(r81_px_64((T81*)((/*RF2*/(C1)->_tracks/*25*/)),b3)))->_commands/*8*/))),b1,b2);
/*]*/
}/*]*/
break;
case 49:
/*[IRF3.6put*/{T28* C1=(T28*)(r96song());
T0* b1=((T0*)se_ms(1,"1"));
T2 b2=r96abs_row(C,(/*RF2*/(C)->_cursorr/*28*/));
T2 b3=/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+((/*RF2*/(C)->_cursorc/*32*/))/*)*/;
/*[IRF3.5put*/r56put(((T56*)((/*RF2*/((T80*)(r81_px_64((T81*)((/*RF2*/(C1)->_tracks/*25*/)),b3)))->_commands/*8*/))),b1,b2);
/*]*/
}/*]*/
break;
case 46:
/*[IF*/
if(r28has((T28*)(r96song()),r96abs_row(C,(/*RF2*/(C)->_cursorr/*28*/)),/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+((/*RF2*/(C)->_cursorc/*32*/))/*)*/)){
/*[IRF3.6remove*/{T28* C1=(T28*)(r96song());
T2 b1=r96abs_row(C,(/*RF2*/(C)->_cursorr/*28*/));
T2 b2=/*(IRF4.6abs_col*/((/*RF2*/(C)->_originc/*20*/))+((/*RF2*/(C)->_cursorc/*32*/))/*)*/;
r56remove((T56*)((/*RF2*/((T80*)(r81_px_64((T81*)((/*RF2*/(C1)->_tracks/*25*/)),b2)))->_commands/*8*/)),b1);
}/*]*/
}
/*FI]*/
break;
}
}/*INSPECT]*/
}

void r96move_cursor_down(T96* C,T2 a1){
/*[IF*/
if(((/*RF2*/(C)->_cursorr/*28*/))<(((/*RF2*/(C)->_maxr/*36*/))-(a1))){
(/*SFN*/C->_cursorr/*28*/)=((/*RF2*/(C)->_cursorr/*28*/))+(a1);
}
else{
(/*SFN*/C->_originr/*24*/)=((/*RF2*/(C)->_originr/*24*/))+(a1);
}
/*FI]*/
}

T2 r96abs_row(T96* C,T2 a1){
T2 R=0;
R=(16)*(((/*RF2*/(C)->_originr/*24*/))+(a1));
return R;
}

void r96process_buttondown(T96* C,T0* a1){
T2 _r=0;
/*[INSPECT*/
{int z1=(/*RF2*/(((T22*)a1))->_i1/*20*/);
switch(z1){
default:;
/*[IF*/
if((((/*RF2*/(((T22*)a1))->_x/*8*/))<(30))&&(((/*RF2*/(((T22*)a1))->_y/*4*/))>(40))){
_r=(16)*(((/*RF2*/(C)->_originr/*24*/))+((((/*RF2*/(((T22*)a1))->_y/*4*/))-(40))/(20)));
/*[IF*/
if((_r)>((/*RF2*/((T28*)(r96song()))->_end_beat/*37*/))){
_r=(/*RF2*/((T28*)(r96song()))->_end_beat/*37*/);
}
/*FI]*/
r89put_string(r7_px_43((T7*)(r7_px_43(se_ms(8,"jump to "),r2to_string(_r))),((T0*)se_ms(1,"\n"))));
r28jump_to((T28*)(r96song()),_r);
}
/*FI]*/
}
}/*INSPECT]*/
}

T0* r167twin(T167* C){
T0* R=NULL;
R=((void*)new167());
*((T167*)R)=*C;
return R;
}

T0* r161twin(T161* C){
T0* R=NULL;
R=((void*)new161());
*((T161*)R)=*C;
return R;
}

T0* r165twin(T165* C){
T0* R=NULL;
R=((void*)new165());
*((T165*)R)=*C;
return R;
}

T0* r74new_pattern_autoname(T74* C){
T0* R=NULL;
T2 _i=0;
while (!(!(r61has((T61*)((/*RF2*/(C)->_pattern_table/*12*/)),r2to_string(_i)))))
{
_i=(_i)+(1);
}
R=r74new_pattern(C,r2to_string(_i));
return R;
}

void r74put_cutoff(T74* C,T2 a1){
(/*SFN*/C->_cutoff/*73*/)=((T5)((a1)+(1)))/(256);
}

T0* r74blue(void){
if(fBC17blue==0){fBC17blue=1;{
{T50*n=new50();
oBC17blue=((T0*)n);
r50make(n,0,0,127);
}
}}
return oBC17blue;
}

T2 r74fade_time(void){
T2 R=0;
R=(/*(IRF4.9sample_rate*/(/*RF2*/((T28*)(r74song()))->_samples_per_tick/*65*/)/*)*/)/(16);
return R;
}

void r74move_to(T74* C,T2 a1,T2 a2){
(/*SFN*/C->_posx/*28*/)=a1;
(/*SFN*/C->_posy/*24*/)=a2;
}

T0* r74song(void){
if(fBC19song==0){fBC19song=1;{
{T28*n=new28();
oBC19song=((T0*)n);
r28make(n);
}
}}
return oBC19song;
}

T2 r74centerx(T74* C){
T2 R=0;
R=((/*RF2*/(C)->_posx/*28*/))+(((/*RF2*/(C)->_width/*32*/))/(2));
return R;
}

void r74compute_taps(T74* C){
T5 _b1=0;
T5 _b2=0;
T5 _bd=0;
_b2=(T4toT5(1.))/(tan((r74pi())*((/*RF2*/(C)->_cutoff/*73*/))));
_b1=((/*RF2*/(C)->_recipq/*61*/))*(_b2);
_b2=(_b2)*(_b2);
_bd=(T4toT5(1.))/(((_b2)+(_b1))+(T4toT5(1.)));
r205put_outcoeff((T205*)((/*RF2*/(C)->_bq/*69*/)),(-((T4toT5(2.))-((T4toT5(2.))*(_b2))))*(_bd),1);
r205put_outcoeff((T205*)((/*RF2*/(C)->_bq/*69*/)),(-(((_b2)-(_b1))+(T4toT5(1.))))*(_bd),2);
r205put_incoeff((T205*)((/*RF2*/(C)->_bq/*69*/)),(T4toT5(1.))*(_bd),0);
r205put_incoeff((T205*)((/*RF2*/(C)->_bq/*69*/)),(T4toT5(2.))*(_bd),1);
r205put_incoeff((T205*)((/*RF2*/(C)->_bq/*69*/)),(T4toT5(1.))*(_bd),2);
}

T2 r74centery(T74* C){
T2 R=0;
R=((/*RF2*/(C)->_posy/*24*/))+(((/*RF2*/(C)->_height/*36*/))/(2));
return R;
}

T0* r74new_pattern(T74* C,T0* a1){
T0* R=NULL;
{T51*n=new51();
r51make(n,a1,(T0*)C);
R=((T0*)n);
}
r61put((T61*)((/*RF2*/(C)->_pattern_table/*12*/)),R,a1);
r59add_last((T59*)((/*RF2*/(C)->_pattern_list/*16*/)),R);
return R;
}

T0* r74clone(T0* a1){
T0* R=NULL;
/*[IF*/
if((a1)!=((void*)(NULL))){
R=X10twin(a1);
}
/*FI]*/
return R;
}

T0* r74make_instance(T74* C,T0* a1){
T0* R=NULL;
R=r74clone((T0*)C);
r74put_name(((T74*)R),a1);
r74init_connection_lists(((T74*)R));
r74init_pattern_table(((T74*)R));
r74init_picture(((T74*)R));
r74init(((T74*)R));
return R;
}

void r74put_length(T74* C,T2 a1){
(/*SFN*/C->_ttl/*83*/)=a1;
(/*SFN*/C->_fade_in/*81*/)=1;
/*[IF*/
if(((/*RF2*/(C)->_ttl/*83*/))==(1)){
(/*SFN*/C->_fade_out/*82*/)=1;
}
else{
(/*SFN*/C->_fade_out/*82*/)=0;
}
/*FI]*/
}

void r74play_freq(T74* C,T5 a1){
r74put_freq(C,a1);
r74put_length(C,1);
/*[IRF3.3put_vol*/((((T74*)(C)))->_vol/*95*/)=(T4toT5(1.0));
/*]*/
(/*SFN*/C->_x/*87*/)=0;
}
T5 oBC74pi=0;
int fBC74pi=0;

T5 r74pi(void){
if(fBC74pi==0){fBC74pi=1;{
oBC74pi=(T4toT5(4.0))*(r4atan(1.0));
}}
return oBC74pi;
}

T6 r74is_note(T0* a1,T2 a2){
T6 R=0;
T2 _j=0;
_j=a2;
/*[IF*/
if(((((unsigned)(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))>=((unsigned)(((T3)'A')))))&&((((unsigned)(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))<=((unsigned)(((T3)'G')))))){
_j=(_j)+(1);
/*[IF*/
if(((_j)<=(/*(IRF4.3upper*/(/*RF2*/(((T7*)a1))->_count/*8*/)/*)*/))&&((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)==(((T3)'\43')))){
_j=(_j)+(1);
}
/*FI]*/
/*[IF*/
if(((_j)<=(/*(IRF4.3upper*/(/*RF2*/(((T7*)a1))->_count/*8*/)/*)*/))&&(r3is_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))){
R=1;
}
/*FI]*/
}
/*FI]*/
return R;
}
T0*oBC74saw_table=NULL;
int fBC74saw_table=0;

T0* r74saw_table(void){
if(fBC74saw_table==0){fBC74saw_table=1;{
T2 _i=0;
{T118*n=new118();
oBC74saw_table=((T0*)n);
r118make(n,0,(1024)-(1));
}
_i=0;
while (!((_i)==(1024)))
{
X118put(oBC74saw_table,(T4toT5(0.5))-(((T5)(_i))/(1024)),_i);
_i=(_i)+(1);
}
}}
return oBC74saw_table;
}

void r74process_command(T74* C,T0* a1){
T2 _i=0;
r89put_string(r7_px_43((T7*)(r7_px_43(se_ms(10,"command = "),a1)),((T0*)se_ms(1,"\n"))));
/*[IF*/
if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(1)-(1)]/*)*/)==(((T3)'L'))){
_i=r3value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/);
/*[IF*/
if((((/*RF2*/(((T7*)a1))->_count/*8*/))>(2))&&(r3is_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/))){
_i=((_i)*(10))+(r3value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/));
}
/*FI]*/
r74put_length(C,_i);
}
 else if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(1)-(1)]/*)*/)==(((T3)'V'))){
_i=r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/);
/*[IF*/
if(r3is_hexadecimal_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/)){
_i=((_i)*(16))+(r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/));
}
/*FI]*/
/*[IRF3.3put_vol*/((((T74*)(C)))->_vol/*95*/)=(((T5)(_i))/(128));
/*]*/
}
 else if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(1)-(1)]/*)*/)==(((T3)'c'))){
_i=r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/);
/*[IF*/
if(r3is_hexadecimal_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/)){
_i=((_i)*(16))+(r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/));
}
/*FI]*/
r74put_cutoff(C,_i);
r74compute_taps(C);
}
 else if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(1)-(1)]/*)*/)==(((T3)'r'))){
_i=r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/);
/*[IF*/
if(r3is_hexadecimal_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/)){
_i=((_i)*(16))+(r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/));
}
/*FI]*/
r74put_resonance(C,_i);
r74compute_taps(C);
}
 else if(r74is_note(a1,1)){
r74play_freq(C,X118item(r74note_freq_table(),r74note_to_rank(a1,1)));
}
/*FI]*/
}

void r74init(T74* C){
(/*SFN*/C->_wave_table/*103*/)=r74saw_table();
{T205*n=new205();
r205make(n);
(/*SFN*/C->_bq/*69*/)=((T0*)n);
}
r74put_cutoff(C,128);
r74put_resonance(C,0);
r74compute_taps(C);
}

void r74init_connection_lists(T74* C){
{T65*n=new65();
r65make(n);
(/*SFN*/C->_in_connection/*8*/)=((T0*)n);
}
}

void r74put_resonance(T74* C,T2 a1){
(/*SFN*/C->_recipq/*61*/)=(T4toT5(1.))-(((T5)(a1))/(256));
}
T0*oBC31note_rank_array=NULL;
int fBC31note_rank_array=0;

T0* r74note_rank_array(void){
if(fBC31note_rank_array==0){fBC31note_rank_array=1;{
oBC31note_rank_array=se_ma146(7,
0,
2,
4,
5,
7,
9,
11);
}}
return oBC31note_rank_array;
}

void r74init_pattern_table(T74* C){
{T61*n=new61();
/*[IRF3.4make*/r61with_capacity(n,193);
/*]*/
(/*SFN*/C->_pattern_table/*12*/)=((T0*)n);
}
{T59*n=new59();
r59make(n);
(/*SFN*/C->_pattern_list/*16*/)=((T0*)n);
}
{T51*n=new51();
r51make(n,((T0*)se_ms(5,"SETUP")),(T0*)C);
(/*SFN*/C->_setup_pattern/*20*/)=((T0*)n);
}
}

T0* r74next_pattern(T74* C,T0* a1){
T0* R=NULL;
T2 _i=0;
_i=(r59fast_index_of((T59*)((/*RF2*/(C)->_pattern_list/*16*/)),a1))+(1);
/*[IF*/
if((_i)>((/*RF2*/((T59*)((/*RF2*/(C)->_pattern_list/*16*/)))->_upper/*4*/))){
_i=1;
}
/*FI]*/
R=r59_px_64((T59*)((/*RF2*/(C)->_pattern_list/*16*/)),_i);
return R;
}
T0*oBC74fade_table=NULL;
int fBC74fade_table=0;

T0* r74fade_table(void){
if(fBC74fade_table==0){fBC74fade_table=1;{
T2 _i=0;
{T118*n=new118();
oBC74fade_table=((T0*)n);
r118make(n,0,128);
}
_i=0;
while (!((_i)==(128)))
{
X118put(oBC74fade_table,(r4pow(2.0,((T5)(_i))/(128)))-(T2toT5(1)),_i);
_i=(_i)+(1);
}
}}
return oBC74fade_table;
}

T0* r74twin(T74* C){
T0* R=NULL;
R=((void*)new74());
*((T74*)R)=*C;
return R;
}
T0*oBC31note_freq_table=NULL;
int fBC31note_freq_table=0;

T0* r74note_freq_table(void){
if(fBC31note_freq_table==0){fBC31note_freq_table=1;{
T2 _i=0;
{T118*n=new118();
oBC31note_freq_table=((T0*)n);
r118make(n,0,127);
}
_i=0;
while (!((_i)>(127)))
{
X118put(oBC31note_freq_table,(T4toT5(220.0))*(r4pow(2.0,((T5)((_i)-(57)))/(12))),_i);
_i=(_i)+(1);
}
}}
return oBC31note_freq_table;
}

void r74put_freq(T74* C,T5 a1){
(/*SFN*/C->_freq/*91*/)=r5rounded((a1)*(T2toT5(32)));
}

T0* r74white(void){
if(fBC17white==0){fBC17white=1;{
{T50*n=new50();
oBC17white=((T0*)n);
r50make(n,255,255,255);
}
}}
return oBC17white;
}

T2 r74note_to_rank(T0* a1,T2 a2){
T2 R=0;
T2 _j=0;
_j=a2;
R=(T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))-(T3code(((T3)'C')));
/*[IF*/
if((R)<(0)){
R=(R)+(7);
}
/*FI]*/
R=r146item((T146*)(r74note_rank_array()),(R)+(1));
_j=(_j)+(1);
/*[IF*/
if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)==(((T3)'\43'))){
R=(R)+(1);
_j=(_j)+(1);
}
/*FI]*/
R=(R)+((12)*(r3value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)));
return R;
}

T5 r74work(T74* C){
T5 R=0;
/*[IF*/
if(((/*RF2*/(C)->_ttl/*83*/))>(0)){
R=((X118item((/*RF2*/(C)->_wave_table/*103*/),(((/*RF2*/(C)->_x/*87*/))*(1024))/(r74modulus())))*((/*RF2*/(C)->_vol/*95*/)))*(T4toT5(0.6));
(/*SFN*/C->_x/*87*/)=((/*RF2*/(C)->_x/*87*/))+((/*RF2*/(C)->_freq/*91*/));
/*[IF*/
if(((/*RF2*/(C)->_x/*87*/))>=(r74modulus())){
(/*SFN*/C->_x/*87*/)=((/*RF2*/(C)->_x/*87*/))-(r74modulus());
}
/*FI]*/
/*[IF*/
if((/*(IRF4.9sample*/(/*RF2*/((T28*)(r74song()))->_sample_mod_tick/*57*/)/*)*/)==(0)){
(/*SFN*/C->_ttl/*83*/)=((/*RF2*/(C)->_ttl/*83*/))-(1);
/*[IF*/
if(((/*RF2*/(C)->_ttl/*83*/))==(1)){
(/*SFN*/C->_fade_out/*82*/)=1;
}
/*FI]*/
}
/*FI]*/
/*[IF*/
if((/*RF2*/(C)->_fade_in/*81*/)){
/*[IF*/
if((/*(IRF4.9sample*/(/*RF2*/((T28*)(r74song()))->_sample_mod_tick/*57*/)/*)*/)<(r74fade_time())){
R=(R)*(X118item(r74fade_table(),((/*(IRF4.9sample*/(/*RF2*/((T28*)(r74song()))->_sample_mod_tick/*57*/)/*)*/)*(128))/(r74fade_time())));
}
/*FI]*/
}
else{
(/*SFN*/C->_fade_in/*81*/)=0;
}
/*FI]*/
/*[IF*/
if((/*RF2*/(C)->_fade_out/*82*/)){
/*[IF*/
if((/*(IRF4.9sample*/(/*RF2*/((T28*)(r74song()))->_sample_mod_tick/*57*/)/*)*/)>((/*(IRF4.9sample_rate*/(/*RF2*/((T28*)(r74song()))->_samples_per_tick/*65*/)/*)*/)-(r74fade_time()))){
R=(R)*(X118item(r74fade_table(),(((/*(IRF4.9sample_rate*/(/*RF2*/((T28*)(r74song()))->_samples_per_tick/*65*/)/*)*/)-(/*(IRF4.9sample*/(/*RF2*/((T28*)(r74song()))->_sample_mod_tick/*57*/)/*)*/))*(128))/(r74fade_time())));
}
/*FI]*/
}
/*FI]*/
R=/*(IRF4.6lpfilter*/r205filter(((T205*)((/*RF2*/(C)->_bq/*69*/))),R)/*)*/;
}
/*FI]*/
return R;
}

void r74compute_next_frame(T74* C){
T0* _it=NULL;
/*[IF*/
if(!((/*RF2*/(C)->_visited/*60*/))){
(/*SFN*/C->_mix_input/*44*/)=T2toT5(0);
_it=r65get_new_iterator((T65*)((/*RF2*/(C)->_in_connection/*8*/)));
r122start(((T122*)_it));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T122*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
X30compute_next_frame((/*RF2*/((T64*)(/*(IRF4.6item*/(/*RF2*/(((T66*)((/*RF2*/(((T122*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_src/*8*/));
(/*SFN*/C->_mix_input/*44*/)=((/*RF2*/(C)->_mix_input/*44*/))+((1.0)*(/*SSWARF2*//*X30last_frame*/(/*RF2*/((T67*)((/*RF2*/((T64*)(/*(IRF4.6item*/(/*RF2*/(((T66*)((/*RF2*/(((T122*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_src/*8*/)))->_last_frame/*52*/)));
r122next(((T122*)_it));
}
(/*SFN*/C->_last_frame/*52*/)=r74work(C);
(/*SFN*/C->_visited/*60*/)=1;
}
/*FI]*/
}

void r74put_name(T74* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
}

void r74init_picture(T74* C){
(/*SFN*/C->_posx/*28*/)=0;
(/*SFN*/C->_posy/*24*/)=0;
(/*SFN*/C->_width/*32*/)=70;
(/*SFN*/C->_height/*36*/)=25;
{T48*n=new48();
/*[IRF3.1make*//*]*/
(/*SFN*/C->_image/*40*/)=((T0*)n);
}
r48new((T48*)((/*RF2*/(C)->_image/*40*/)),(/*RF2*/(C)->_width/*32*/),(/*RF2*/(C)->_height/*36*/));
/*[IRF3.6box*/{T48* C1=(T48*)((/*RF2*/(C)->_image/*40*/));
T2 b1=0;
T2 b2=0;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(1);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(1);
T0* b5=r74white();
/*[ from line 177 of ./image.e:*/
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 177 of ./image.e]*/
}/*]*/
/*[IRF3.6box*/{T48* C1=(T48*)((/*RF2*/(C)->_image/*40*/));
T2 b1=2;
T2 b2=2;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(3);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(3);
T0* b5=/*(IRF4.8bgcolor*/r74blue()/*)*/;
/*[ from line 177 of ./image.e:*/
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 177 of ./image.e]*/
}/*]*/
/*[IRF3.5put_heading*/r48draw_text(((T48*)((/*RF2*/(C)->_image/*40*/))),4,6,(/*RF2*/(C)->_name/*4*/));
/*]*/
}
T2 oBC74modulus=0;
int fBC74modulus=0;

T2 r74modulus(void){
if(fBC74modulus==0){fBC74modulus=1;{
oBC74modulus=(44100)*(32);
}}
return oBC74modulus;
}

void r205put_outcoeff(T205* C,T5 a1,T2 a2){
X118put((/*RF2*/(C)->_outcoeff/*8*/),a1,a2);
}

void r205make(T205* C){
{T118*n=new118();
r118make(n,1,2);
(/*SFN*/C->_outcoeff/*8*/)=((T0*)n);
}
{T118*n=new118();
r118make(n,0,2);
(/*SFN*/C->_incoeff/*4*/)=((T0*)n);
}
}

T5 r205filter(T205* C,T5 a1){
T5 R=0;
R=(X118item((/*RF2*/(C)->_incoeff/*4*/),0))*(a1);
R=(R)+((X118item((/*RF2*/(C)->_incoeff/*4*/),1))*((/*RF2*/(C)->_inhistory1/*12*/)));
R=(R)+((X118item((/*RF2*/(C)->_incoeff/*4*/),2))*((/*RF2*/(C)->_inhistory2/*20*/)));
R=(R)+((X118item((/*RF2*/(C)->_outcoeff/*8*/),1))*((/*RF2*/(C)->_outhistory1/*28*/)));
R=(R)+((X118item((/*RF2*/(C)->_outcoeff/*8*/),2))*((/*RF2*/(C)->_outhistory2/*36*/)));
(/*SFN*/C->_inhistory2/*20*/)=(/*RF2*/(C)->_inhistory1/*12*/);
(/*SFN*/C->_inhistory1/*12*/)=a1;
(/*SFN*/C->_outhistory2/*36*/)=(/*RF2*/(C)->_outhistory1/*28*/);
(/*SFN*/C->_outhistory1/*28*/)=R;
return R;
}

void r205put_incoeff(T205* C,T5 a1,T2 a2){
X118put((/*RF2*/(C)->_incoeff/*4*/),a1,a2);
}

T0* r205twin(T205* C){
T0* R=NULL;
R=((void*)new205());
*((T205*)R)=*C;
return R;
}

void r184make(T184* C,T0* a1,T2 a2,T2 a3){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
(/*SFN*/C->_offset/*8*/)=a2;
(/*SFN*/C->_size/*12*/)=a3;
}

T0* r184twin(T184* C){
T0* R=NULL;
R=((void*)new184());
*((T184*)R)=*C;
return R;
}

T0* r175twin(T175* C){
T0* R=NULL;
R=((void*)new175());
*((T175*)R)=*C;
return R;
}

T0* r172twin(T172* C){
T0* R=NULL;
R=((void*)new172());
*((T172*)R)=*C;
return R;
}

T0* r174twin(T174* C){
T0* R=NULL;
R=((void*)new174());
*((T174*)R)=*C;
return R;
}

void r138init_data(T138* C,T2 a1){
{T197*n=new197();
r197make(n,0,(a1)-(1));
(/*SFN*/C->_data/*16*/)=((T0*)n);
}
}

T0* r138twin(T138* C){
T0* R=NULL;
R=((void*)new138());
*((T138*)R)=*C;
return R;
}
T0*oBC132conv_table=NULL;
int fBC132conv_table=0;

T0* r131conv_table(void){
if(fBC132conv_table==0){fBC132conv_table=1;{
T0* _c=NULL;
{T162*n=new162();
oBC132conv_table=((T0*)n);
/*[IRF3.4make*/r162with_capacity(n,193);
/*]*/
}
{T179*n=new179();
/*[IRF3.6register*/{T179* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms179_1658653172));
}/*]*/
_c=((T0*)n);
}
{T178*n=new178();
/*[IRF3.6register*/{T178* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms178_581741755));
}/*]*/
_c=((T0*)n);
}
{T177*n=new177();
/*[IRF3.6register*/{T177* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms177_1658706155));
}/*]*/
_c=((T0*)n);
}
{T176*n=new176();
/*[IRF3.6register*/{T176* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms176_296345362));
}/*]*/
_c=((T0*)n);
}
{T175*n=new175();
/*[IRF3.6register*/{T175* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms175_1386254719));
}/*]*/
_c=((T0*)n);
}
{T174*n=new174();
/*[IRF3.6register*/{T174* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms174_1578465704));
}/*]*/
_c=((T0*)n);
}
{T173*n=new173();
/*[IRF3.6register*/{T173* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms173_1658719074));
}/*]*/
_c=((T0*)n);
}
{T172*n=new172();
/*[IRF3.6register*/{T172* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms172_529023852));
}/*]*/
_c=((T0*)n);
}
{T171*n=new171();
/*[IRF3.6register*/{T171* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms171_296581587));
}/*]*/
_c=((T0*)n);
}
{T170*n=new170();
/*[IRF3.6register*/{T170* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms170_616173747));
}/*]*/
_c=((T0*)n);
}
{T169*n=new169();
/*[IRF3.6register*/{T169* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms169_1043126849));
}/*]*/
_c=((T0*)n);
}
{T168*n=new168();
/*[IRF3.6register*/{T168* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms168_1658670231));
}/*]*/
_c=((T0*)n);
}
{T167*n=new167();
/*[IRF3.6register*/{T167* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms167_502183218));
}/*]*/
_c=((T0*)n);
}
{T166*n=new166();
/*[IRF3.6register*/{T166* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms166_1058194184));
}/*]*/
_c=((T0*)n);
}
{T165*n=new165();
/*[IRF3.6register*/{T165* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms165_1761360889));
}/*]*/
_c=((T0*)n);
}
{T161*n=new161();
/*[IRF3.6register*/{T161* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms161_1065849555));
}/*]*/
_c=((T0*)n);
}
}}
return oBC132conv_table;
}

void r131convert_waves(T0* a1,T0* a2){
T2 _i=0;
T0* _bw=NULL;
T0* _bl=NULL;
T0* _w=NULL;
_i=0;
while (!((_i)==((/*RF2*/(((T129*)a2))->_wave_count/*32*/))))
{
_bw=r143item((T143*)((/*RF2*/(((T129*)a2))->_wavetable/*28*/)),_i);
_bl=/*(IRF4.6first*/((/*RF2*/((T140*)((/*RF2*/(((T139*)_bw))->_level_table/*24*/)))->_storage/*4*/))[0]/*)*/;
{T76*n=new76();
/*[IRF3.6make*/{T76* C1=n;
T0* b1=(/*RF2*/(((T139*)_bw))->_name/*20*/);
r76put_name(C1,b1);
}/*]*/
_w=((T0*)n);
}
/*[IRF3.3put_volume*/((((T76*)(((T76*)_w))))->_volume/*12*/)=((/*RF2*/(((T139*)_bw))->_volume/*8*/));
/*]*/
/*[IRF3.3set_data*/((((T76*)(((T76*)_w))))->_data/*24*/)=((/*RF2*/(((T138*)_bl))->_data/*16*/));
/*]*/
/*[IRF3.3put_length*/((((T76*)(((T76*)_w))))->_length/*20*/)=((/*RF2*/(((T138*)_bl))->_length/*4*/));
/*]*/
/*[IRF3.3put_root_freq*/((((T76*)(((T76*)_w))))->_root_freq/*4*/)=((/*RF2*/(((T138*)_bl))->_root_freq/*8*/));
/*]*/
/*[IRF3.5put_wave*/r77put(((T77*)((/*RF2*/(((T28*)a1))->_wave_table/*29*/))),_w,(_i)+(1));
/*]*/
r89put_string(r7_px_43((T7*)(r7_px_43((T7*)(r7_px_43((T7*)(r7_px_43(se_ms(11,"converting "),(/*RF2*/(((T76*)_w))->_name/*28*/))),((T0*)se_ms(9,": put at ")))),r2to_string((_i)+(1)))),((T0*)se_ms(1,"\n"))));
r89put_string(r7_px_43((T7*)(r7_px_43(se_ms(8,"index = "),r2to_string((/*RF2*/(((T139*)_bw))->_index/*4*/)))),((T0*)se_ms(1,"\n"))));
r89put_string(r7_px_43((T7*)(r7_px_43(se_ms(9,"volume = "),r5to_string((/*RF2*/(((T139*)_bw))->_volume/*8*/)))),((T0*)se_ms(1,"\n"))));
_i=(_i)+(1);
}
}

void r131convert(T0* a1,T0* a2){
T2 _i=0;
T2 _j=0;
T0* _bm=NULL;
T0* _m=NULL;
T2 _x=0;
T2 _y=0;
T0* _bc=NULL;
T0* _seq=NULL;
T0* _m_array=NULL;
T0* _t=NULL;
T0* _c=NULL;
{T134*n=new134();
r134make(n,0,((/*RF2*/(((T129*)a2))->_machine_count/*40*/))-(1));
_m_array=((T0*)n);
}
_i=0;
while (!((_i)==((/*RF2*/(((T129*)a2))->_machine_count/*40*/))))
{
_bm=r153item((T153*)((/*RF2*/(((T129*)a2))->_machine/*36*/)),_i);
/*[IF*/
if(((/*RF2*/(((T137*)_bm))->_type/*8*/))==(0)){
_m=(/*RF2*/(((T28*)a1))->_master/*4*/);
}
else{
_c=r162at((T162*)(r131conv_table()),(/*RF2*/(((T137*)_bm))->_dll/*12*/));
_m=r28new_machine(((T28*)a1),(/*RF2*/(((T137*)_bm))->_name/*4*/),X133bliss_id(_c));
}
/*FI]*/
/*[IRF3.6put*/{T134* C1=((T134*)_m_array);
T0* b1=_m;
T2 b2=_i;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
_x=r4rounded(((T2toT4(638))*(((/*RF2*/(((T137*)_bm))->_x/*20*/))+(T2toT4(1))))/(T2toT4(2)));
_y=r4rounded(((T2toT4(438))*(((/*RF2*/(((T137*)_bm))->_y/*16*/))+(T2toT4(1))))/(T2toT4(2)));
r28move_to(_m,_x,_y);
_i=(_i)+(1);
}
_i=0;
while (!((_i)==((/*RF2*/(((T129*)a2))->_connection_count/*48*/))))
{
_bc=r180item((T180*)((/*RF2*/(((T129*)a2))->_connection/*44*/)),_i);
r28connect(((T28*)a1),r134item(((T134*)_m_array),(/*RF2*/(((T136*)_bc))->_src/*4*/)),r134item(((T134*)_m_array),(/*RF2*/(((T136*)_bc))->_dst/*8*/)));
_i=(_i)+(1);
}
_i=1;
while (!((_i)==((/*RF2*/(((T129*)a2))->_machine_count/*40*/))))
{
_bm=r153item((T153*)((/*RF2*/(((T129*)a2))->_machine/*36*/)),_i);
_c=r162at((T162*)(r131conv_table()),(/*RF2*/(((T137*)_bm))->_dll/*12*/));
X133convert_patterns(_c,r134item(((T134*)_m_array),_i),_bm);
_i=(_i)+(1);
}
/*[IRF3.3put_end_beat*/((((T28*)(((T28*)a1))))->_end_beat/*37*/)=((/*RF2*/(((T129*)a2))->_song_end/*12*/));
/*]*/
/*[IRF3.3put_loop_begin*/((((T28*)(((T28*)a1))))->_loop_begin/*41*/)=((/*RF2*/(((T129*)a2))->_loop_begin/*8*/));
/*]*/
/*[IRF3.3put_loop_end*/((((T28*)(((T28*)a1))))->_loop_end/*45*/)=((/*RF2*/(((T129*)a2))->_loop_end/*4*/));
/*]*/
_i=0;
while (!((_i)==((/*RF2*/(((T129*)a2))->_sequence_count/*56*/))))
{
_seq=r158item((T158*)((/*RF2*/(((T129*)a2))->_sequence/*52*/)),_i);
{T80*n=new80();
r80make(n,r134item(((T134*)_m_array),(/*RF2*/(((T135*)_seq))->_machine_index/*4*/)));
_t=((T0*)n);
}
_bm=r153item((T153*)((/*RF2*/(((T129*)a2))->_machine/*36*/)),(/*RF2*/(((T135*)_seq))->_machine_index/*4*/));
r81add_last((T81*)((/*RF2*/(((T28*)a1))->_tracks/*25*/)),_t);
_j=0;
while (!((_j)==((/*RF2*/(((T135*)_seq))->_event_count/*16*/))))
{
_x=(r146item((T146*)((/*RF2*/(((T135*)_seq))->_event/*12*/)),_j))-(16);
/*[IRF3.5put*/r56put(((T56*)((/*RF2*/(((T80*)_t))->_commands/*8*/))),(/*RF2*/((T149*)(r150item((T150*)((/*RF2*/(((T137*)_bm))->_pattern/*32*/)),_x)))->_name/*4*/),r146item((T146*)((/*RF2*/(((T135*)_seq))->_eventpos/*8*/)),_j));
/*]*/
_j=(_j)+(1);
}
_i=(_i)+(1);
}
r131convert_waves(a1,a2);
}

T0* r131twin(T131* C){
T0* R=NULL;
R=((void*)new131());
*((T131*)R)=*C;
return R;
}

T0* r71new_pattern_autoname(T71* C){
T0* R=NULL;
T2 _i=0;
while (!(!(r61has((T61*)((/*RF2*/(C)->_pattern_table/*12*/)),r2to_string(_i)))))
{
_i=(_i)+(1);
}
R=r71new_pattern(C,r2to_string(_i));
return R;
}

T0* r71blue(void){
if(fBC17blue==0){fBC17blue=1;{
{T50*n=new50();
oBC17blue=((T0*)n);
r50make(n,0,0,127);
}
}}
return oBC17blue;
}

void r71move_to(T71* C,T2 a1,T2 a2){
(/*SFN*/C->_posx/*28*/)=a1;
(/*SFN*/C->_posy/*24*/)=a2;
}

void r71put_track(T71* C,T2 a1){
/*[IF*/
if(((a1)>=(0))&&((a1)<(8))){
(/*SFN*/C->_track/*65*/)=a1;
}
/*FI]*/
}

T2 r71centerx(T71* C){
T2 R=0;
R=((/*RF2*/(C)->_posx/*28*/))+(((/*RF2*/(C)->_width/*32*/))/(2));
return R;
}

T2 r71centery(T71* C){
T2 R=0;
R=((/*RF2*/(C)->_posy/*24*/))+(((/*RF2*/(C)->_height/*36*/))/(2));
return R;
}

T0* r71new_pattern(T71* C,T0* a1){
T0* R=NULL;
{T51*n=new51();
r51make(n,a1,(T0*)C);
R=((T0*)n);
}
r61put((T61*)((/*RF2*/(C)->_pattern_table/*12*/)),R,a1);
r59add_last((T59*)((/*RF2*/(C)->_pattern_list/*16*/)),R);
return R;
}

T0* r71clone(T0* a1){
T0* R=NULL;
/*[IF*/
if((a1)!=((void*)(NULL))){
R=X10twin(a1);
}
/*FI]*/
return R;
}

T0* r71make_instance(T71* C,T0* a1){
T0* R=NULL;
R=r71clone((T0*)C);
r71put_name(((T71*)R),a1);
r71init_connection_lists(((T71*)R));
r71init_pattern_table(((T71*)R));
r71init_picture(((T71*)R));
r71init(((T71*)R));
return R;
}

T6 r71is_note(T0* a1,T2 a2){
T6 R=0;
T2 _j=0;
_j=a2;
/*[IF*/
if(((((unsigned)(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))>=((unsigned)(((T3)'A')))))&&((((unsigned)(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))<=((unsigned)(((T3)'G')))))){
_j=(_j)+(1);
/*[IF*/
if(((_j)<=(/*(IRF4.3upper*/(/*RF2*/(((T7*)a1))->_count/*8*/)/*)*/))&&((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)==(((T3)'\43')))){
_j=(_j)+(1);
}
/*FI]*/
/*[IF*/
if(((_j)<=(/*(IRF4.3upper*/(/*RF2*/(((T7*)a1))->_count/*8*/)/*)*/))&&(r3is_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))){
R=1;
}
/*FI]*/
}
/*FI]*/
return R;
}

void r71process_command(T71* C,T0* a1){
T2 _i=0;
r89put_string(r7_px_43((T7*)(r7_px_43(se_ms(10,"command = "),a1)),((T0*)se_ms(1,"\n"))));
/*[INSPECT*/
{int z1=/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(1)-(1)]/*)*/;
switch(z1){
case 86:
_i=r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/);
/*[IF*/
if(r3is_hexadecimal_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/)){
_i=((_i)*(16))+(r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/));
}
/*FI]*/
/*[IRF3.3put_vol*/((((T203*)((T203*)(((/*RF2*/(C)->_track_array/*61*/))[(/*RF2*/(C)->_track/*65*/)]))))->_vol/*12*/)=(((T5)(_i))/(128));
/*]*/
break;
case 83:
_i=((r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/))*(16))+(r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/));
r203put_wave_index((T203*)(((/*RF2*/(C)->_track_array/*61*/))[(/*RF2*/(C)->_track/*65*/)]),_i);
break;
case 84:
_i=r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(2)-(1)]/*)*/);
r71put_track(C,_i);
break;
case 118:
_i=((r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(3)-(1)]/*)*/))*(16))+(r3hexadecimal_value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(4)-(1)]/*)*/));
r203volslidedown((T203*)(((/*RF2*/(C)->_track_array/*61*/))[(/*RF2*/(C)->_track/*65*/)]),_i);
break;
default:;
/*[IF*/
if(r71is_note(a1,1)){
r203play_freq((T203*)(((/*RF2*/(C)->_track_array/*61*/))[(/*RF2*/(C)->_track/*65*/)]),X118item(r71note_freq_table(),r71note_to_rank(a1,1)));
}
/*FI]*/
}
}/*INSPECT]*/
}

void r71init(T71* C){
T0* _t=NULL;
T2 _i=0;
(/*SFN*/C->_track_array/*61*/)=new204(8);
_i=0;
while (!((_i)==(8)))
{
{T203*n=new203();
/*[IRF3.1make*//*]*/
_t=((T0*)n);
}
((/*RF2*/(C)->_track_array/*61*/))[_i]=(_t);
_i=(_i)+(1);
}
}

void r71init_connection_lists(T71* C){
{T65*n=new65();
r65make(n);
(/*SFN*/C->_in_connection/*8*/)=((T0*)n);
}
}

T0* r71note_rank_array(void){
if(fBC31note_rank_array==0){fBC31note_rank_array=1;{
oBC31note_rank_array=se_ma146(7,
0,
2,
4,
5,
7,
9,
11);
}}
return oBC31note_rank_array;
}

void r71init_pattern_table(T71* C){
{T61*n=new61();
/*[IRF3.4make*/r61with_capacity(n,193);
/*]*/
(/*SFN*/C->_pattern_table/*12*/)=((T0*)n);
}
{T59*n=new59();
r59make(n);
(/*SFN*/C->_pattern_list/*16*/)=((T0*)n);
}
{T51*n=new51();
r51make(n,((T0*)se_ms(5,"SETUP")),(T0*)C);
(/*SFN*/C->_setup_pattern/*20*/)=((T0*)n);
}
}

T0* r71next_pattern(T71* C,T0* a1){
T0* R=NULL;
T2 _i=0;
_i=(r59fast_index_of((T59*)((/*RF2*/(C)->_pattern_list/*16*/)),a1))+(1);
/*[IF*/
if((_i)>((/*RF2*/((T59*)((/*RF2*/(C)->_pattern_list/*16*/)))->_upper/*4*/))){
_i=1;
}
/*FI]*/
R=r59_px_64((T59*)((/*RF2*/(C)->_pattern_list/*16*/)),_i);
return R;
}

T0* r71twin(T71* C){
T0* R=NULL;
R=((void*)new71());
*((T71*)R)=*C;
return R;
}

T0* r71note_freq_table(void){
if(fBC31note_freq_table==0){fBC31note_freq_table=1;{
T2 _i=0;
{T118*n=new118();
oBC31note_freq_table=((T0*)n);
r118make(n,0,127);
}
_i=0;
while (!((_i)>(127)))
{
X118put(oBC31note_freq_table,(T4toT5(220.0))*(r4pow(2.0,((T5)((_i)-(57)))/(12))),_i);
_i=(_i)+(1);
}
}}
return oBC31note_freq_table;
}

T0* r71white(void){
if(fBC17white==0){fBC17white=1;{
{T50*n=new50();
oBC17white=((T0*)n);
r50make(n,255,255,255);
}
}}
return oBC17white;
}

T2 r71note_to_rank(T0* a1,T2 a2){
T2 R=0;
T2 _j=0;
_j=a2;
R=(T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))-(T3code(((T3)'C')));
/*[IF*/
if((R)<(0)){
R=(R)+(7);
}
/*FI]*/
R=r146item((T146*)(r71note_rank_array()),(R)+(1));
_j=(_j)+(1);
/*[IF*/
if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)==(((T3)'\43'))){
R=(R)+(1);
_j=(_j)+(1);
}
/*FI]*/
R=(R)+((12)*(r3value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)));
return R;
}

T5 r71work(T71* C){
T5 R=0;
T2 _i=0;
_i=0;
while (!((_i)==(8)))
{
R=(R)+(r203next_sample((T203*)(((/*RF2*/(C)->_track_array/*61*/))[_i])));
_i=(_i)+(1);
}
return R;
}

void r71compute_next_frame(T71* C){
T0* _it=NULL;
/*[IF*/
if(!((/*RF2*/(C)->_visited/*60*/))){
(/*SFN*/C->_mix_input/*44*/)=T2toT5(0);
_it=r65get_new_iterator((T65*)((/*RF2*/(C)->_in_connection/*8*/)));
r122start(((T122*)_it));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T122*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
X30compute_next_frame((/*RF2*/((T64*)(/*(IRF4.6item*/(/*RF2*/(((T66*)((/*RF2*/(((T122*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_src/*8*/));
(/*SFN*/C->_mix_input/*44*/)=((/*RF2*/(C)->_mix_input/*44*/))+((1.0)*(/*SSWARF2*//*X30last_frame*/(/*RF2*/((T67*)((/*RF2*/((T64*)(/*(IRF4.6item*/(/*RF2*/(((T66*)((/*RF2*/(((T122*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_src/*8*/)))->_last_frame/*52*/)));
r122next(((T122*)_it));
}
(/*SFN*/C->_last_frame/*52*/)=r71work(C);
(/*SFN*/C->_visited/*60*/)=1;
}
/*FI]*/
}

void r71put_name(T71* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
}

void r71init_picture(T71* C){
(/*SFN*/C->_posx/*28*/)=0;
(/*SFN*/C->_posy/*24*/)=0;
(/*SFN*/C->_width/*32*/)=70;
(/*SFN*/C->_height/*36*/)=25;
{T48*n=new48();
/*[IRF3.1make*//*]*/
(/*SFN*/C->_image/*40*/)=((T0*)n);
}
r48new((T48*)((/*RF2*/(C)->_image/*40*/)),(/*RF2*/(C)->_width/*32*/),(/*RF2*/(C)->_height/*36*/));
/*[IRF3.6box*/{T48* C1=(T48*)((/*RF2*/(C)->_image/*40*/));
T2 b1=0;
T2 b2=0;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(1);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(1);
T0* b5=r71white();
/*[ from line 177 of ./image.e:*/
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 177 of ./image.e]*/
}/*]*/
/*[IRF3.6box*/{T48* C1=(T48*)((/*RF2*/(C)->_image/*40*/));
T2 b1=2;
T2 b2=2;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(3);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(3);
T0* b5=/*(IRF4.8bgcolor*/r71blue()/*)*/;
/*[ from line 177 of ./image.e:*/
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T50*)b5))->_to_gfx_integer/*8*/));
/* from line 177 of ./image.e]*/
}/*]*/
/*[IRF3.5put_heading*/r48draw_text(((T48*)((/*RF2*/(C)->_image/*40*/))),4,6,(/*RF2*/(C)->_name/*4*/));
/*]*/
}

T5 r212next_sample(T212* C){
T5 R=0;
r212next_t(C);
R=(/*RF2*/(C)->_current_value/*24*/);
return R;
}

void r212next_value(T212* C){
T2 _i=0;
T2 _n=0;
_n=10;
(/*SFN*/C->_current_value/*24*/)=T2toT5(0);
_i=0;
while (!((_i)==(_n)))
{
r213next((T213*)((/*RF2*/(C)->_sr/*20*/)));
(/*SFN*/C->_current_value/*24*/)=((/*RF2*/(C)->_current_value/*24*/))+(r213last_double((T213*)((/*RF2*/(C)->_sr/*20*/))));
_i=(_i)+(1);
}
(/*SFN*/C->_current_value/*24*/)=(((T2toT5(2))*((/*RF2*/(C)->_current_value/*24*/)))/(T2toT5(_n)))-(T4toT5(1.0));
}

void r212make(T212* C){
{T213*n=new213();
r213make(n);
(/*SFN*/C->_sr/*20*/)=((T0*)n);
}
r212next_value(C);
}

T0* r212twin(T212* C){
T0* R=NULL;
R=((void*)new212());
*((T212*)R)=*C;
return R;
}

void r212put_freq(T212* C,T5 a1){
(/*SFN*/C->_t_max/*12*/)=(T2toT5(44100))/(a1);
}

void r212next_t(T212* C){
/*[IF*/
if(((/*RF2*/(C)->_t_max/*12*/))>(T4toT5(0.0))){
(/*SFN*/C->_t/*4*/)=((/*RF2*/(C)->_t/*4*/))+(T4toT5(1.0));
/*[IF*/
if(((/*RF2*/(C)->_t/*4*/))>((/*RF2*/(C)->_t_max/*12*/))){
r212next_value(C);
(/*SFN*/C->_t/*4*/)=((/*RF2*/(C)->_t/*4*/))-((/*RF2*/(C)->_t_max/*12*/));
}
/*FI]*/
}
/*FI]*/
}

T0* r171twin(T171* C){
T0* R=NULL;
R=((void*)new171());
*((T171*)R)=*C;
return R;
}

T0* r178twin(T178* C){
T0* R=NULL;
R=((void*)new178());
*((T178*)R)=*C;
return R;
}

T0* r137conv_table(void){
if(fBC132conv_table==0){fBC132conv_table=1;{
T0* _c=NULL;
{T162*n=new162();
oBC132conv_table=((T0*)n);
/*[IRF3.4make*/r162with_capacity(n,193);
/*]*/
}
{T179*n=new179();
/*[IRF3.6register*/{T179* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms179_1658653172));
}/*]*/
_c=((T0*)n);
}
{T178*n=new178();
/*[IRF3.6register*/{T178* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms178_581741755));
}/*]*/
_c=((T0*)n);
}
{T177*n=new177();
/*[IRF3.6register*/{T177* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms177_1658706155));
}/*]*/
_c=((T0*)n);
}
{T176*n=new176();
/*[IRF3.6register*/{T176* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms176_296345362));
}/*]*/
_c=((T0*)n);
}
{T175*n=new175();
/*[IRF3.6register*/{T175* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms175_1386254719));
}/*]*/
_c=((T0*)n);
}
{T174*n=new174();
/*[IRF3.6register*/{T174* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms174_1578465704));
}/*]*/
_c=((T0*)n);
}
{T173*n=new173();
/*[IRF3.6register*/{T173* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms173_1658719074));
}/*]*/
_c=((T0*)n);
}
{T172*n=new172();
/*[IRF3.6register*/{T172* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms172_529023852));
}/*]*/
_c=((T0*)n);
}
{T171*n=new171();
/*[IRF3.6register*/{T171* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms171_296581587));
}/*]*/
_c=((T0*)n);
}
{T170*n=new170();
/*[IRF3.6register*/{T170* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms170_616173747));
}/*]*/
_c=((T0*)n);
}
{T169*n=new169();
/*[IRF3.6register*/{T169* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms169_1043126849));
}/*]*/
_c=((T0*)n);
}
{T168*n=new168();
/*[IRF3.6register*/{T168* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms168_1658670231));
}/*]*/
_c=((T0*)n);
}
{T167*n=new167();
/*[IRF3.6register*/{T167* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms167_502183218));
}/*]*/
_c=((T0*)n);
}
{T166*n=new166();
/*[IRF3.6register*/{T166* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms166_1058194184));
}/*]*/
_c=((T0*)n);
}
{T165*n=new165();
/*[IRF3.6register*/{T165* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms165_1761360889));
}/*]*/
_c=((T0*)n);
}
{T161*n=new161();
/*[IRF3.6register*/{T161* C1=n;
T0* b1=oBC132conv_table;
r162put(((T162*)b1),(T0*)C1,((T0*)ms161_1065849555));
}/*]*/
_c=((T0*)n);
}
}}
return oBC132conv_table;
}

void r137put_type(T137* C,T2 a1){
(/*SFN*/C->_type/*8*/)=a1;
/*[IF*/
if(((/*RF2*/(C)->_type/*8*/))==(0)){
(/*SFN*/C->_global_parm_size/*40*/)=5;
(/*SFN*/C->_track_parm_size/*44*/)=0;
}
/*FI]*/
}

void r137put_dll(T137* C,T0* a1){
T0* _c=NULL;
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_dll/*12*/)=((T0*)n);
}
/*[IF*/
if(r162has((T162*)(r137conv_table()),(/*RF2*/(C)->_dll/*12*/))){
_c=r162at((T162*)(r137conv_table()),(/*RF2*/(C)->_dll/*12*/));
(/*SFN*/C->_global_parm_size/*40*/)=X133global_parm_count(_c);
(/*SFN*/C->_track_parm_size/*44*/)=X133track_parm_count(_c);
}
else{
r89put_string(r7_px_43((T7*)(r7_px_43(se_ms(19,"Unhandled machine: "),(/*RF2*/(C)->_dll/*12*/))),((T0*)se_ms(1,"\n"))));
exit(1);
}
/*FI]*/
}

void r137put_pattern_count(T137* C,T2 a1){
(/*SFN*/C->_pattern_count/*36*/)=a1;
{T150*n=new150();
r150make(n,0,((/*RF2*/(C)->_pattern_count/*36*/))-(1));
(/*SFN*/C->_pattern/*32*/)=((T0*)n);
}
}

void r137make(T137* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
}

void r137put_xy(T137* C,T4 a1,T4 a2){
(/*SFN*/C->_x/*20*/)=a1;
(/*SFN*/C->_y/*16*/)=a2;
}

void r137increment_in_count(T137* C){
(/*SFN*/C->_in_count/*48*/)=((/*RF2*/(C)->_in_count/*48*/))+(1);
}

T0* r137twin(T137* C){
T0* R=NULL;
R=((void*)new137());
*((T137*)R)=*C;
return R;
}

void r93handle_event(T93* C,T0* a1){
/*[IRF3.3put_x*/((((T22*)(((T22*)a1))))->_x/*8*/)=(((/*RF2*/(((T22*)a1))->_x/*8*/))-((/*RF2*/(C)->_offsetx/*4*/)));
/*]*/
/*[IRF3.3put_y*/((((T22*)(((T22*)a1))))->_y/*4*/)=(((/*RF2*/(((T22*)a1))->_y/*4*/))-((/*RF2*/(C)->_offsety/*8*/)));
/*]*/
r93process_event(C,a1);
}

void r93process_key(T93* C,T0* a1){
T2 _k=0;
_k=(/*RF2*/(((T22*)a1))->_i1/*20*/);
/*[IF*/
if(((_k)>=(97))&&((_k)<=(122))){
/*[IF*/
if(/*[ from line 272 of ./sdl_constant.e:*/
is_kmod((/*RF2*/(((T22*)a1))->_kmod/*24*/),3)
/* from line 272 of ./sdl_constant.e]*/
){
/*[IRF3.5text_append*/r7add_last(((T7*)((/*RF2*/(C)->_filename/*24*/))),((T3)((_k)-(32))));
/*]*/
}
else{
/*[IRF3.5text_append*/r7add_last(((T7*)((/*RF2*/(C)->_filename/*24*/))),((T3)(_k)));
/*]*/
}
/*FI]*/
}
 else if((_k)==(8)){
r93text_remove_last(C);
}
 else if((_k)==(27)){
/*[IRF3.3put_modal*/((((T16*)((T16*)((/*RF2*/(C)->_manager/*20*/)))))->_modal/*20*/)=(NULL);
/*]*/
}
 else if((_k)==(13)){
r93import_buzz_file(C);
}
else{
/*[IRF3.5text_append*/r7add_last(((T7*)((/*RF2*/(C)->_filename/*24*/))),((T3)(_k)));
/*]*/
}
/*FI]*/
}

void r93import_buzz_file(T93* C){
T0* _bl=NULL;
T0* _b=NULL;
{T130*n=new130();
r130make(n);
_bl=((T0*)n);
}
_b=r130load(((T130*)_bl),(/*RF2*/(C)->_filename/*24*/));
/*[IF*/
if((_b)==((void*)(NULL))){
r89put_string(((T0*)se_ms(19,"error loading file\n")));
}
else{
r28import_buzz((T28*)(r93song()),_b);
}
/*FI]*/
/*[IRF3.3put_modal*/((((T16*)((T16*)((/*RF2*/(C)->_manager/*20*/)))))->_modal/*20*/)=(NULL);
/*]*/
}

T0* r93song(void){
if(fBC19song==0){fBC19song=1;{
{T28*n=new28();
oBC19song=((T0*)n);
r28make(n);
}
}}
return oBC19song;
}

void r93text_remove_last(T93* C){
/*[IF*/
if(!(/*(IRF4.7is_empty*/((/*RF2*/((T7*)((/*RF2*/(C)->_filename/*24*/)))->_count/*8*/))==(0)/*)*/)){
r7remove_last((T7*)((/*RF2*/(C)->_filename/*24*/)),1);
}
/*FI]*/
}

void r93write(T93* C,T2 a1,T2 a2,T0* a3){
T0* _img=NULL;
{T48*n=new48();
/*[IRF3.1make*//*]*/
_img=((T0*)n);
}
r48render_string(((T48*)_img),a3);
/*[IRF3.6blit*/{T48* C1=((T48*)_img);
T2 b1=((/*RF2*/(C)->_offsetx/*4*/))+(a1);
T2 b2=((/*RF2*/(C)->_offsety/*8*/))+(a2);
/*[ from line 169 of ./image.e:*/
ext_blit_img((/*RF2*/(C1)->_ptr/*5*/),b1,b2);
/* from line 169 of ./image.e]*/
}/*]*/
r48free(((T48*)_img));
}

void r93make(T93* C,T0* a1){
(/*SFN*/C->_manager/*20*/)=a1;
r93put_geometry(C,20,20,600,50);
{T7*n=new7();
r7make(n,128);
(/*SFN*/C->_filename/*24*/)=((T0*)n);
}
}

void r93put_geometry(T93* C,T2 a1,T2 a2,T2 a3,T2 a4){
(/*SFN*/C->_offsetx/*4*/)=a1;
(/*SFN*/C->_offsety/*8*/)=a2;
(/*SFN*/C->_width/*12*/)=a3;
(/*SFN*/C->_height/*16*/)=a4;
}

void r93process_event(T93* C,T0* a1){
/*[IF*/
if(((/*RF2*/(((T22*)a1))->_type/*12*/))==(2)){
r93process_key(C,a1);
}
/*FI]*/
}

T0* r93twin(T93* C){
T0* R=NULL;
R=((void*)new93());
*((T93*)R)=*C;
return R;
}

T0* r93white(void){
if(fBC17white==0){fBC17white=1;{
{T50*n=new50();
oBC17white=((T0*)n);
r50make(n,255,255,255);
}
}}
return oBC17white;
}

void r93update(T93* C){
/*[IRF3.6fill_rect*/{T93* C1=C;
T2 b1=0;
T2 b2=0;
T2 b3=(/*RF2*/(C)->_width/*12*/);
T2 b4=(/*RF2*/(C)->_height/*16*/);
T0* b5=r93white();
/*[ from line 50 of ./window.e:*/
ext_fill_rect((b1)+((/*RF2*/(C1)->_offsetx/*4*/)),(b2)+((/*RF2*/(C1)->_offsety/*8*/)),b3,b4,(/*RF2*/(((T50*)b5))->_to_integer/*4*/));
/* from line 50 of ./window.e]*/
}/*]*/
/*[IRF3.6fill_rect*/{T93* C1=C;
T2 b1=2;
T2 b2=2;
T2 b3=((/*RF2*/(C)->_width/*12*/))-(4);
T2 b4=((/*RF2*/(C)->_height/*16*/))-(4);
T0* b5=r93black();
/*[ from line 50 of ./window.e:*/
ext_fill_rect((b1)+((/*RF2*/(C1)->_offsetx/*4*/)),(b2)+((/*RF2*/(C1)->_offsety/*8*/)),b3,b4,(/*RF2*/(((T50*)b5))->_to_integer/*4*/));
/* from line 50 of ./window.e]*/
}/*]*/
r93write(C,10,10,r7_px_43(se_ms(18,"Import Buzz file: "),(/*RF2*/(C)->_filename/*24*/)));
}
T0*oBC17black=NULL;
int fBC17black=0;

T0* r93black(void){
if(fBC17black==0){fBC17black=1;{
{T50*n=new50();
oBC17black=((T0*)n);
r50make(n,0,0,0);
}
}}
return oBC17black;
}

T0* r170twin(T170* C){
T0* R=NULL;
R=((void*)new170());
*((T170*)R)=*C;
return R;
}

T0* r166twin(T166* C){
T0* R=NULL;
R=((void*)new166());
*((T166*)R)=*C;
return R;
}

void r48draw_text(T48* C,T2 a1,T2 a2,T0* a3){
T0* _text=NULL;
{T48*n=new48();
/*[IRF3.1make*//*]*/
_text=((T0*)n);
}
r48render_string(((T48*)_text),a3);
/*[IRF3.6blit_to*/{T48* C1=((T48*)_text);
T0* b1=(T0*)C;
T2 b2=a1;
T2 b3=a2;
/*[ from line 173 of ./image.e:*/
ext_blit_img_to((/*RF2*/(C1)->_ptr/*5*/),(/*RF2*/(((T48*)b1))->_ptr/*5*/),b2,b3);
/* from line 173 of ./image.e]*/
}/*]*/
r48free(((T48*)_text));
}

void r48render_string(T48* C,T0* a1){
(/*SFN*/C->_ptr/*5*/)=/*[ from line 149 of ./image.e:*/
render_text(r7to_external(((T7*)a1)))
/* from line 149 of ./image.e]*/
;
/*[IF*/
if((NULL!=(/*RF2*/(C)->_ptr/*5*/))){
(/*SFN*/C->_is_connected/*4*/)=1;
}
/*FI]*/
}

void r48rotozoom(T48* C,T0* a1,T5 a2,T5 a3){
(/*SFN*/C->_ptr/*5*/)=/*[ from line 193 of ./image.e:*/
rotozoomSurface((/*RF2*/(((T48*)a1))->_ptr/*5*/),a2,a3,1)
/* from line 193 of ./image.e]*/
;
/*[IF*/
if((NULL!=(/*RF2*/(C)->_ptr/*5*/))){
(/*SFN*/C->_is_connected/*4*/)=1;
}
/*FI]*/
}

void r48new(T48* C,T2 a1,T2 a2){
(/*SFN*/C->_ptr/*5*/)=/*[ from line 181 of ./image.e:*/
ext_new_surface(a1,a2)
/* from line 181 of ./image.e]*/
;
/*[IF*/
if((NULL!=(/*RF2*/(C)->_ptr/*5*/))){
(/*SFN*/C->_is_connected/*4*/)=1;
}
/*FI]*/
}

void r48new_arrow(T48* C){
(/*SFN*/C->_ptr/*5*/)=/*[ from line 189 of ./image.e:*/
draw_arrow_kludge()
/* from line 189 of ./image.e]*/
;
/*[IF*/
if((NULL!=(/*RF2*/(C)->_ptr/*5*/))){
(/*SFN*/C->_is_connected/*4*/)=1;
}
/*FI]*/
}

T2 r48height(T48* C){
T2 R=0;
R=/*[ from line 157 of ./image.e:*/
get_img_height((/*RF2*/(C)->_ptr/*5*/))
/* from line 157 of ./image.e]*/
;
return R;
}

T0* r48twin(T48* C){
T0* R=NULL;
R=((void*)new48());
*((T48*)R)=*C;
return R;
}

T2 r48width(T48* C){
T2 R=0;
R=/*[ from line 153 of ./image.e:*/
get_img_width((/*RF2*/(C)->_ptr/*5*/))
/* from line 153 of ./image.e]*/
;
return R;
}

void r48free(T48* C){
/*[IF*/
if((NULL!=(/*RF2*/(C)->_ptr/*5*/))){
(/*SFN*/C->_ptr/*5*/)=/*[ from line 144 of ./image.e:*/
free_img((/*RF2*/(C)->_ptr/*5*/))
/* from line 144 of ./image.e]*/
;
(/*SFN*/C->_is_connected/*4*/)=0;
}
/*FI]*/
}

