/*
ANSI C code generated by SmallEiffel The GNU Eiffel Compiler
Release -0.75 (July 16th 2001)
Copyright (C), 1994-2001 - LORIA - UHP - INRIA - FRANCE
Dominique COLNET and Suzanne COLLIN - SmallEiffel@loria.fr
http://SmallEiffel.loria.fr
*/
#ifdef __cplusplus
}
#endif
#include "main.h"
#ifdef __cplusplus
extern "C" {
#endif


void r132put_event_count(T132* C,T2 a1){
(/*SFN*/C->_event_count/*16*/)=a1;
{T143*n=new143();
r143make(n,0,(/*RF2*/(C)->_event_count/*16*/));
(/*SFN*/C->_eventpos/*8*/)=((T0*)n);
}
{T143*n=new143();
r143make(n,0,(/*RF2*/(C)->_event_count/*16*/));
(/*SFN*/C->_event/*12*/)=((T0*)n);
}
}


T0* r132twin(T132* C){
T0* R=NULL;
R=((void*)new132());
*((T132*)R)=*C;
return R;
}


void r52boom(T52* C,T2 a1){
T0* _it=NULL;
/*[IF*/
if(r55has_row((T55*)((/*RF2*/(C)->_commands/*8*/)),a1)){
_it=r120get_new_iterator((T120*)(r55get_row((T55*)((/*RF2*/(C)->_commands/*8*/)),a1)));
r123start(((T123*)_it));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T123*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
X35process_command((/*RF2*/(C)->_machine/*12*/),/*(IRF4.6item*/(/*RF2*/(((T121*)((/*RF2*/(((T123*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/);
r123next(((T123*)_it));
}
}
/*FI]*/
}


void r52make(T52* C,T0* a1,T0* a2){
(/*SFN*/C->_machine/*12*/)=a2;
{T55*n=new55();
r55make(n);
(/*SFN*/C->_commands/*8*/)=((T0*)n);
}
r52put_name(C,a1);
}


void r52instant_execute(T52* C){
T0* _it2=NULL;
T0* _it=NULL;
_it=r106get_new_iterator((T106*)(r55get_sorted_row_list((T55*)((/*RF2*/(C)->_commands/*8*/)))));
X97start(_it);
while (!(X97is_off(_it)))
{
_it2=r106get_new_iterator((T106*)(r55get_sorted_col_list((T55*)((/*RF2*/(C)->_commands/*8*/)),X97item(_it))));
X97start(_it2);
while (!(X97is_off(_it2)))
{
X35process_command((/*RF2*/(C)->_machine/*12*/),r55at((T55*)((/*RF2*/(C)->_commands/*8*/)),X97item(_it),X97item(_it2)));
X97next(_it2);
}
X97next(_it);
}
}


T0* r52twin(T52* C){
T0* R=NULL;
R=((void*)new52());
*((T52*)R)=*C;
return R;
}


void r52put_name(T52* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
}


T5 r200evaluate(T5 a1){
T5 R=0;
R=sin((a1)*(6.283185307));
return R;
}


T0* r200twin(T200* C){
T0* R=NULL;
R=((void*)new200());
*((T200*)R)=*C;
return R;
}


void r133make(T133* C,T2 a1,T2 a2,T2 a3,T2 a4){
(/*SFN*/C->_src/*4*/)=a1;
(/*SFN*/C->_dst/*8*/)=a2;
(/*SFN*/C->_amp/*12*/)=a3;
(/*SFN*/C->_pan/*16*/)=a4;
}


T0* r133twin(T133* C){
T0* R=NULL;
R=((void*)new133());
*((T133*)R)=*C;
return R;
}


T5 r202next_sample(T202* C){
T5 R=0;
r202next_t(C);
R=r200evaluate((/*RF2*/(C)->_t/*4*/));
return R;
}


T0* r202twin(T202* C){
T0* R=NULL;
R=((void*)new202());
*((T202*)R)=*C;
return R;
}


void r202next_t(T202* C){
(/*SFN*/C->_t/*4*/)=fast_next((/*RF2*/(C)->_t/*4*/),(/*RF2*/(C)->_freq/*12*/));
}


void r79boom(T79* C,T2 a1){
/*[IF*/
if(r57has((T57*)((/*RF2*/(C)->_commands/*8*/)),a1)){
(/*SFN*/C->_offset/*16*/)=a1;
r79process_command(C,r57at((T57*)((/*RF2*/(C)->_commands/*8*/)),a1));
}
/*FI]*/
/*[IF*/
if(((/*RF2*/(C)->_playing_pattern/*12*/))!=((void*)(NULL))){
r52boom((T52*)((/*RF2*/(C)->_playing_pattern/*12*/)),(a1)-((/*RF2*/(C)->_offset/*16*/)));
}
/*FI]*/
}


void r79make(T79* C,T0* a1){
(/*SFN*/C->_machine/*4*/)=a1;
{T57*n=new57();
/*[IRF3.4make*/r57with_capacity(n,193);
/*]*/
(/*SFN*/C->_commands/*8*/)=((T0*)n);
}
}


void r79process_command(T79* C,T0* a1){
/*[IF*/
if(r62has((T62*)(/*SSWARF2*//*X35pattern_table*/(/*RF2*/((T68*)((/*RF2*/(C)->_machine/*4*/)))->_pattern_table/*12*/)),a1)){
(/*SFN*/C->_playing_pattern/*12*/)=r62at((T62*)(/*SSWARF2*//*X35pattern_table*/(/*RF2*/((T68*)((/*RF2*/(C)->_machine/*4*/)))->_pattern_table/*12*/)),a1);
}
else{
(/*SFN*/C->_playing_pattern/*12*/)=NULL;
}
/*FI]*/
}


T0* r79twin(T79* C){
T0* R=NULL;
R=((void*)new79());
*((T79*)R)=*C;
return R;
}


void r79rewind(T79* C){
(/*SFN*/C->_offset/*16*/)=0;
(/*SFN*/C->_playing_pattern/*12*/)=NULL;
}


T0* r164twin(T164* C){
T0* R=NULL;
R=((void*)new164());
*((T164*)R)=*C;
return R;
}


T0* r74new_pattern_autoname(T74* C){
T0* R=NULL;
T2 _i=0;
while (!(!(r62has((T62*)((/*RF2*/(C)->_pattern_table/*12*/)),r2to_string(_i)))))
{
_i=(_i)+(1);
}
R=r74new_pattern(C,r2to_string(_i));
return R;
}


T0* r74blue(void){
if(fBC18blue==0){fBC18blue=1;{
{T51*n=new51();
oBC18blue=((T0*)n);
r51make(n,0,0,127);
}
}}
return oBC18blue;
}


void r74move_to(T74* C,T2 a1,T2 a2){
(/*SFN*/C->_posx/*28*/)=a1;
(/*SFN*/C->_posy/*24*/)=a2;
}


T5 r74next_sample(T74* C){
T5 R=0;
T0* _it=NULL;
_it=X194get_new_iterator_on_items((/*RF2*/(C)->_drum_table/*48*/));
X193start(_it);
while (!(X193is_off(_it)))
{
R=(R)+(X37next_sample(X193item(_it)));
X193next(_it);
}
return R;
}


T2 r74centerx(T74* C){
T2 R=0;
R=((/*RF2*/(C)->_posx/*28*/))+(((/*RF2*/(C)->_width/*32*/))/(2));
return R;
}


T2 r74centery(T74* C){
T2 R=0;
R=((/*RF2*/(C)->_posy/*24*/))+(((/*RF2*/(C)->_height/*36*/))/(2));
return R;
}


T0* r74new_pattern(T74* C,T0* a1){
T0* R=NULL;
{T52*n=new52();
r52make(n,a1,(T0*)C);
R=((T0*)n);
}
r62put((T62*)((/*RF2*/(C)->_pattern_table/*12*/)),R,a1);
r60add_last((T60*)((/*RF2*/(C)->_pattern_list/*16*/)),R);
return R;
}


void r74boom(T74* C){
/*[IF*/
if(((/*RF2*/(C)->_ttl/*44*/))>(0)){
(/*SFN*/C->_ttl/*44*/)=((/*RF2*/(C)->_ttl/*44*/))-(1);
/*[IF*/
if(((/*RF2*/(C)->_ttl/*44*/))==(0)){
X194remove((/*RF2*/(C)->_drum_table/*48*/),((T0*)ms74_17651));
}
/*FI]*/
}
/*FI]*/
}


T0* r74clone(T0* a1){
T0* R=NULL;
/*[IF*/
if((a1)!=((void*)(NULL))){
R=X10twin(a1);
}
/*FI]*/
return R;
}


T0* r74make_instance(T74* C,T0* a1){
T0* R=NULL;
R=r74clone((T0*)C);
r74put_name(((T74*)R),a1);
r74init_connection_lists(((T74*)R));
r74init_pattern_table(((T74*)R));
r74init_picture(((T74*)R));
r74init(((T74*)R));
return R;
}


void r74play_freq(T74* C,T5 a1){
T0* _s=NULL;
T0* _o=NULL;
{T200*n=new200();
/*[IRF3.1make*//*]*/
_s=((T0*)n);
}
{T202*n=new202();
/*[IRF3.3make*/((((T202*)(n)))->_periodicf/*20*/)=(_s);
/*]*/
_o=((T0*)n);
}
/*[IRF3.3put_freq*/((((T202*)(((T202*)_o))))->_freq/*12*/)=(a1);
/*]*/
(/*SFN*/C->_ttl/*44*/)=3;
X194put((/*RF2*/(C)->_drum_table/*48*/),_o,((T0*)ms74_17651a));
}


void r74snare_drum(T74* C){
T0* _rm=NULL;
T0* _c=NULL;
T0* _n=NULL;
{T206*n=new206();
r206make(n);
_n=((T0*)n);
}
r206put_freq(((T206*)_n),T2toT5(20000));
{T205*n=new205();
r205make(n,T4toT5(1.0),T4toT5(0.0));
_c=((T0*)n);
}
{T203*n=new203();
r203make(n,_n,_c);
_rm=((T0*)n);
}
X194put((/*RF2*/(C)->_drum_table/*48*/),_rm,((T0*)ms74_88721));
}


T6 r74is_note(T0* a1,T2 a2){
T6 R=0;
T2 _j=0;
_j=a2;
/*[IF*/
if(((((unsigned)(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))>=((unsigned)(((T3)'A')))))&&((((unsigned)(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))<=((unsigned)(((T3)'G')))))){
_j=(_j)+(1);
/*[IF*/
if(((_j)<=(/*(IRF4.3upper*/(/*RF2*/(((T7*)a1))->_count/*8*/)/*)*/))&&((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)==(((T3)'\43')))){
_j=(_j)+(1);
}
/*FI]*/
/*[IF*/
if(((_j)<=(/*(IRF4.3upper*/(/*RF2*/(((T7*)a1))->_count/*8*/)/*)*/))&&(r3is_digit(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))){
R=1;
}
/*FI]*/
}
/*FI]*/
return R;
}


void r74process_command(T74* C,T0* a1){
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms74_247323012,a1)),((T0*)ms74_10a)));
/*[IF*/
if(r74is_note(a1,1)){
r84put_string((T84*)(oBC1io),((T0*)ms74_2001008752));
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r2to_string(r74note_to_rank(a1,1))),((T0*)ms74_10)));
r74play_freq(C,X117item(r74note_freq_table(),r74note_to_rank(a1,1)));
}
 else if(r7is_equal(((T7*)a1),((T0*)ms74_443))){
r74kick_drum(C);
}
 else if(r7is_equal(((T7*)a1),((T0*)ms74_483))){
r74snare_drum(C);
}
/*FI]*/
}


void r74kick_drum(T74* C){
T0* _rm=NULL;
T0* _fm=NULL;
T0* _c=NULL;
T0* _o=NULL;
T0* _s=NULL;
{T200*n=new200();
/*[IRF3.1make*//*]*/
_s=((T0*)n);
}
{T202*n=new202();
/*[IRF3.3make*/((((T202*)(n)))->_periodicf/*20*/)=(_s);
/*]*/
_o=((T0*)n);
}
{T204*n=new204();
/*[IRF3.1make*//*]*/
_fm=((T0*)n);
}
/*[IRF3.3put_input*/((((T204*)(((T204*)_fm))))->_input/*4*/)=(_o);
/*]*/
{T205*n=new205();
r205make(n,T4toT5(330.0),T4toT5(0.0));
_c=((T0*)n);
}
/*[IRF3.3put_modulator*/((((T204*)(((T204*)_fm))))->_modulator/*8*/)=(_c);
/*]*/
{T205*n=new205();
r205make(n,T4toT5(1.0),T4toT5(0.0));
_c=((T0*)n);
}
{T203*n=new203();
r203make(n,_fm,_c);
_rm=((T0*)n);
}
X194put((/*RF2*/(C)->_drum_table/*48*/),_rm,((T0*)ms74_16602));
}


void r74init(T74* C){
{T194*n=new194();
r194make(n);
(/*SFN*/C->_drum_table/*48*/)=((T0*)n);
}
}


void r74init_connection_lists(T74* C){
{T66*n=new66();
r66make(n);
(/*SFN*/C->_in_connection/*8*/)=((T0*)n);
}
}


T0* r74note_rank_array(void){
if(fBC36note_rank_array==0){fBC36note_rank_array=1;{
oBC36note_rank_array=se_ma143(7,
0,
2,
4,
5,
7,
9,
11);
}}
return oBC36note_rank_array;
}


void r74init_pattern_table(T74* C){
{T62*n=new62();
/*[IRF3.4make*/r62with_capacity(n,193);
/*]*/
(/*SFN*/C->_pattern_table/*12*/)=((T0*)n);
}
{T60*n=new60();
r60make(n);
(/*SFN*/C->_pattern_list/*16*/)=((T0*)n);
}
{T52*n=new52();
r52make(n,((T0*)ms35_63105),(T0*)C);
(/*SFN*/C->_setup_pattern/*20*/)=((T0*)n);
}
}


T0* r74next_pattern(T74* C,T0* a1){
T0* R=NULL;
T2 _i=0;
_i=(r60fast_index_of((T60*)((/*RF2*/(C)->_pattern_list/*16*/)),a1))+(1);
/*[IF*/
if((_i)>((/*RF2*/((T60*)((/*RF2*/(C)->_pattern_list/*16*/)))->_upper/*4*/))){
_i=1;
}
/*FI]*/
R=r60_px_64((T60*)((/*RF2*/(C)->_pattern_list/*16*/)),_i);
return R;
}


T0* r74twin(T74* C){
T0* R=NULL;
R=((void*)new74());
*((T74*)R)=*C;
return R;
}


T0* r74note_freq_table(void){
if(fBC36note_freq_table==0){fBC36note_freq_table=1;{
T2 _i=0;
{T117*n=new117();
oBC36note_freq_table=((T0*)n);
r117make(n,0,127);
}
_i=0;
while (!((_i)>(127)))
{
X117put(oBC36note_freq_table,(T4toT5(220.0))*(r4pow(2.0,((T5)((_i)-(57)))/(12))),_i);
_i=(_i)+(1);
}
}}
return oBC36note_freq_table;
}


T0* r74white(void){
if(fBC18white==0){fBC18white=1;{
{T51*n=new51();
oBC18white=((T0*)n);
r51make(n,255,255,255);
}
}}
return oBC18white;
}


T2 r74note_to_rank(T0* a1,T2 a2){
T2 R=0;
T2 _j=0;
_j=a2;
R=(T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/))-(T3code(((T3)'C')));
/*[IF*/
if((R)<(0)){
R=(R)+(7);
}
/*FI]*/
R=r143item((T143*)(r74note_rank_array()),(R)+(1));
_j=(_j)+(1);
/*[IF*/
if((/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)==(((T3)'\43'))){
R=(R)+(1);
_j=(_j)+(1);
}
/*FI]*/
R=(R)+((12)*(r3value(/*(IRF4.6item*/((/*RF2*/(((T7*)a1))->_storage/*4*/))[(_j)-(1)]/*)*/)));
return R;
}


void r74put_name(T74* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
}


void r74init_picture(T74* C){
(/*SFN*/C->_posx/*28*/)=0;
(/*SFN*/C->_posy/*24*/)=0;
(/*SFN*/C->_width/*32*/)=70;
(/*SFN*/C->_height/*36*/)=25;
{T50*n=new50();
/*[IRF3.1make*//*]*/
(/*SFN*/C->_image/*40*/)=((T0*)n);
}
r50new((T50*)((/*RF2*/(C)->_image/*40*/)),(/*RF2*/(C)->_width/*32*/),(/*RF2*/(C)->_height/*36*/));
/*[IRF3.6box*/{T50* C1=(T50*)((/*RF2*/(C)->_image/*40*/));
T2 b1=0;
T2 b2=0;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(1);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(1);
T0* b5=r74white();
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
/*[IRF3.6box*/{T50* C1=(T50*)((/*RF2*/(C)->_image/*40*/));
T2 b1=2;
T2 b2=2;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(3);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(3);
T0* b5=/*(IRF4.8bgcolor*/r74blue()/*)*/;
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
/*[IRF3.5put_heading*/r50draw_text(((T50*)((/*RF2*/(C)->_image/*40*/))),4,6,(/*RF2*/(C)->_name/*4*/));
/*]*/
}


T6 r17poll_event(T17* C){
T6 R=0;
R=ext_poll_event();
/*[IF*/
if(R){
r23update((T23*)((/*RF2*/(C)->_last_event/*40*/)));
}
/*FI]*/
return R;
}


void r17main_loop(T17* C){
while (!(0))
{
r17draw_screen(C);
ext_update_screen();
SDL_LockAudio();
r17buffer_audio(C);
SDL_UnlockAudio();
/*[IF*/
if(r17poll_event(C)){
r17process_last_event(C);
}
/*FI]*/
}
}


T0* r17song(void){
if(fBC20song==0){fBC20song=1;{
{T33*n=new33();
oBC20song=((T0*)n);
r33make(n);
}
}}
return oBC20song;
}


void r17draw_screen(T17* C){
/*[IRF3.2blank_screen*//*[IRF3.6fill_rect*/{T2 b1=0;
T2 b2=0;
T2 b3=640;
T2 b4=480;
T0* b5=r17black();
ext_fill_rect(b1,b2,b3,b4,(/*RF2*/(((T51*)b5))->_to_integer/*4*/));
}/*]*/
/*]*/
r17vis_draw(C);
X32update((/*RF2*/(C)->_current_window/*44*/));
/*[IF*/
if(((/*RF2*/(C)->_modal/*20*/))!=((void*)(NULL))){
X32update((/*RF2*/(C)->_modal/*20*/));
}
/*FI]*/
}


void r17load_buzz_dialog(T17* C){
(/*SFN*/C->_modal/*20*/)=(/*RF2*/(C)->_import_buzz_window/*16*/);
}


void r17end_program(T17* C){
SDL_PauseAudio(1);
exit(0);
}


void r17make(T17* C){
(/*SFN*/C->_vis_upper/*32*/)=256;
{T117*n=new117();
r117make(n,1,(/*RF2*/(C)->_vis_upper/*32*/));
(/*SFN*/C->_vis/*28*/)=((T0*)n);
}
{T117*n=new117();
r117make(n,1,(/*RF2*/(C)->_vis_upper/*32*/));
(/*SFN*/C->_vis_snap/*24*/)=((T0*)n);
}
(/*SFN*/C->_vis_i/*36*/)=1;
init();
{T23*n=new23();
/*[IRF3.1make*//*]*/
(/*SFN*/C->_last_event/*40*/)=((T0*)n);
}
r33put_bpm_tpb((T33*)(r17song()),150,4);
{T94*n=new94();
/*[IRF3.6make*/{T94* C1=n;
T2 b1=1;
T2 b2=21;
T2 b3=638;
T2 b4=438;
r94put_geometry(C1,b1,b2,b3,b4);
}/*]*/
(/*SFN*/C->_machine_window/*8*/)=((T0*)n);
}
{T93*n=new93();
r93make(n,1,21,638,438);
(/*SFN*/C->_pattern_window/*4*/)=((T0*)n);
}
{T95*n=new95();
r95make(n,1,21,638,438);
(/*SFN*/C->_song_window/*12*/)=((T0*)n);
}
{T92*n=new92();
r92make(n,(T0*)C);
(/*SFN*/C->_import_buzz_window/*16*/)=((T0*)n);
}
r93put_machine((T93*)((/*RF2*/(C)->_pattern_window/*4*/)),(/*RF2*/((T33*)(r17song()))->_master/*4*/));
(/*SFN*/C->_current_window/*44*/)=(/*RF2*/(C)->_machine_window/*8*/);
SDL_PauseAudio(0);
r17main_loop(C);
}


void r17vis_draw(T17* C){
T2 _y=0;
T2 _x=0;
T2 _i=0;
_i=1;
while (!((_i)>((/*RF2*/(C)->_vis_upper/*32*/))))
{
_y=(100)-(r5rounded((X117item((/*RF2*/(C)->_vis_snap/*24*/),_i))*(T2toT5(50))));
_x=(_i)+(100);
/*[IRF3.6pixelcolor*/{T2 b1=_x;
T2 b2=_y;
T0* b3=r17white();
ext_pixelcolor(b1,b2,(/*RF2*/(((T51*)b3))->_to_gfx_integer/*8*/));
}/*]*/
_i=(_i)+(1);
}
}


void r17buffer_audio(T17* C){
T5 _d=0;
while (!(!(buffer_ready())))
{
_d=r33next_sample((T33*)(r17song()));
/*[IF*/
if(((/*RF2*/(C)->_vis_i/*36*/))>((/*RF2*/(C)->_vis_upper/*32*/))){
(/*SFN*/C->_vis_i/*36*/)=1;
while (!(((/*RF2*/(C)->_vis_i/*36*/))>((/*RF2*/(C)->_vis_upper/*32*/))))
{
X117put((/*RF2*/(C)->_vis_snap/*24*/),X117_px_64((/*RF2*/(C)->_vis/*28*/),(/*RF2*/(C)->_vis_i/*36*/)),(/*RF2*/(C)->_vis_i/*36*/));
(/*SFN*/C->_vis_i/*36*/)=((/*RF2*/(C)->_vis_i/*36*/))+(1);
}
(/*SFN*/C->_vis_i/*36*/)=1;
}
/*FI]*/
X117put((/*RF2*/(C)->_vis/*28*/),_d,(/*RF2*/(C)->_vis_i/*36*/));
(/*SFN*/C->_vis_i/*36*/)=((/*RF2*/(C)->_vis_i/*36*/))+(1);
next_frame(_d,_d);
}
}
T0*oBC17test_saver=NULL;
int fBC17test_saver=0;


T0* r17test_saver(void){
if(fBC17test_saver==0){fBC17test_saver=1;{
{T82*n=new82();
oBC17test_saver=((T0*)n);
/*[IRF3.3make*/((((T82*)(n)))->_os/*4*/)=(oBC1io);
/*]*/
}
}}
return oBC17test_saver;
}


T0* r17twin(T17* C){
T0* R=NULL;
R=((void*)new17());
*((T17*)R)=*C;
return R;
}


T0* r17white(void){
if(fBC18white==0){fBC18white=1;{
{T51*n=new51();
oBC18white=((T0*)n);
r51make(n,255,255,255);
}
}}
return oBC18white;
}


void r17process_last_event(T17* C){
r84put_string((T84*)(oBC1io),r7_px_43((T7*)((/*RF2*/((T23*)((/*RF2*/(C)->_last_event/*40*/)))->_desc/*12*/)),((T0*)ms17_322)));
r84put_integer((T84*)(oBC1io),(/*RF2*/((T23*)((/*RF2*/(C)->_last_event/*40*/)))->_i1/*20*/));
/*[IRF3.4put_new_line*//*[IRF3.6put_character*/{T84* C1=(T84*)(oBC1io);
T3 b1=((T3)'\n');
putc(b1,((FILE*)(stdout)));
}/*]*/
/*]*/
/*[IF*/
if(((/*RF2*/(C)->_modal/*20*/))!=((void*)(NULL))){
X32handle_event((/*RF2*/(C)->_modal/*20*/),(/*RF2*/(C)->_last_event/*40*/));
}
else{
/*[IF*/
if(r7is_equal((T7*)((/*RF2*/((T23*)((/*RF2*/(C)->_last_event/*40*/)))->_desc/*12*/)),((T0*)ms17_2079105))){
/*[IF*/
if(int_and((/*RF2*/((T23*)((/*RF2*/(C)->_last_event/*40*/)))->_kmod/*24*/),192)){
/*[INSPECT*/
{int z1=(/*RF2*/((T23*)((/*RF2*/(C)->_last_event/*40*/)))->_i1/*20*/);
switch(z1){
case 115:
r33save((T33*)(r17song()),r17test_saver());
break;
case 108:
r17load_buzz_dialog(C);
break;
case 110:
r33make((T33*)(r17song()));
break;
default:;
X32handle_event((/*RF2*/(C)->_current_window/*44*/),(/*RF2*/(C)->_last_event/*40*/));
}
}/*INSPECT]*/
}
else{
/*[INSPECT*/
{int z1=(/*RF2*/((T23*)((/*RF2*/(C)->_last_event/*40*/)))->_i1/*20*/);
switch(z1){
case 283:
(/*SFN*/C->_current_window/*44*/)=(/*RF2*/(C)->_pattern_window/*4*/);
break;
case 284:
(/*SFN*/C->_current_window/*44*/)=(/*RF2*/(C)->_machine_window/*8*/);
break;
case 285:
(/*SFN*/C->_current_window/*44*/)=(/*RF2*/(C)->_song_window/*12*/);
break;
case 27:
r17end_program(C);
break;
case 286:
/*[IRF3.3play*/((((T33*)((T33*)(r17song()))))->_play_flag/*8*/)=(1);
/*]*/
break;
case 287:
r33rewind((T33*)(r17song()));
break;
case 289:
/*[IRF3.3pause*/((((T33*)((T33*)(r17song()))))->_play_flag/*8*/)=(0);
/*]*/
break;
default:;
X32handle_event((/*RF2*/(C)->_current_window/*44*/),(/*RF2*/(C)->_last_event/*40*/));
}
}/*INSPECT]*/
}
/*FI]*/
}
else{
X32handle_event((/*RF2*/(C)->_current_window/*44*/),(/*RF2*/(C)->_last_event/*40*/));
}
/*FI]*/
}
/*FI]*/
}


T0* r17black(void){
if(fBC18black==0){fBC18black=1;{
{T51*n=new51();
oBC18black=((T0*)n);
r51make(n,0,0,0);
}
}}
return oBC18black;
}


T0* r27twin(T27* C){
T0* R=NULL;
R=((void*)new27());
*((T27*)R)=*C;
return R;
}


T2 r49prime_number_ceiling(T2 a1){
T2 R=0;
/*[IF*/
if((a1)<=(53)){
R=53;
}
 else if((a1)<=(97)){
R=97;
}
 else if((a1)<=(193)){
R=193;
}
 else if((a1)<=(389)){
R=389;
}
 else if((a1)<=(769)){
R=769;
}
 else if((a1)<=(1543)){
R=1543;
}
 else if((a1)<=(3079)){
R=3079;
}
 else if((a1)<=(6151)){
R=6151;
}
 else if((a1)<=(12289)){
R=12289;
}
 else if((a1)<=(24593)){
R=24593;
}
 else if((a1)<=(49157)){
R=49157;
}
 else if((a1)<=(98317)){
R=98317;
}
 else if((a1)<=(196613)){
R=196613;
}
 else if((a1)<=(393241)){
R=393241;
}
 else if((a1)<=(786433)){
R=786433;
}
 else if((a1)<=(1572869)){
R=1572869;
}
 else if((a1)<=(3145739)){
R=3145739;
}
 else if((a1)<=(6291469)){
R=6291469;
}
 else if((a1)<=(12582917)){
R=12582917;
}
 else if((a1)<=(25165843)){
R=25165843;
}
 else if((a1)<=(50331653)){
R=50331653;
}
 else if((a1)<=(100663319)){
R=100663319;
}
 else if((a1)<=(201326611)){
R=201326611;
}
 else if((a1)<=(402653189)){
R=402653189;
}
 else if((a1)<=(805306457)){
R=805306457;
}
else{
R=1610612741;
}
/*FI]*/
return R;
}
T17*eiffel_root_object=NULL;
int se_argc;
char**se_argv;


void initialize_eiffel_runtime(int argc,char*argv[]){
se_argc=argc;
se_argv=argv;
gcmt=((mch**)se_malloc((gcmt_max+1)*sizeof(void*)));
stack_bottom=((void**)(&argc));
#ifdef SIGINT
signal(SIGINT,se_signal_handler);
#endif
#ifdef SIGQUIT
signal(SIGQUIT,se_signal_handler);
#endif
#ifdef SIGTERM
signal(SIGTERM,se_signal_handler);
#endif
#ifdef SIGBREAK
signal(SIGBREAK,se_signal_handler);
#endif
#ifdef SIGKILL
signal(SIGKILL,se_signal_handler);
#endif
se_msi1();
/*PCO*/
oBC36scale_array=se_ma182(12,
((T0*)ms36_67),
((T0*)ms36_370),
((T0*)ms36_68),
((T0*)ms36_375),
((T0*)ms36_69),
((T0*)ms36_70),
((T0*)ms36_385),
((T0*)ms36_71),
((T0*)ms36_390),
((T0*)ms36_65),
((T0*)ms36_360),
((T0*)ms36_66));
/*PCO*/
{T7*n=new7();
oBC8string_buffer=((T0*)n);
r7make(n,64);
}
/*PCO*/
{T84*n=new84();
oBC1io=((T0*)n);
/*[IRF3.1make*//*]*/
}
/*PCO*/
{T7*n=new7();
oBC83tmp_string=((T0*)n);
r7make(n,512);
}
/*PCO*/
{T7*n=new7();
oBC2tmp_string=((T0*)n);
r7make(n,128);
}
/*PCO*/
gc_is_off=0;
eiffel_root_object=((T17*)se_malloc(sizeof(double)+sizeof(*eiffel_root_object)));
*eiffel_root_object=M17;
}
int main(int argc,char*argv[]){
initialize_eiffel_runtime(argc,argv);
{T17*n=eiffel_root_object;
r17make(n);
}
exit(0);
return 0;}
T7*ms126_39610347;
T7*ms92_58545095;
T7*ms127_1849750926;
T7*ms36_70;
T7*ms36_65;
T7*ms36_71;
T7*ms36_66;
T7*ms36_67;
T7*ms36_68;
T7*ms36_69;
T7*ms134_1812835366;
T7*ms127_10aaaaaaa;
T7*ms82_420719;
T7*ms74_17651a;
T7*ms126_10;
T7*ms163_690;
T7*ms127_10;
T7*ms72_319144;
T7*ms128_10;
T7*ms95_248415980;
T7*ms134_10;
T7*ms93_41083572;
T7*ms127_1137;
T7*ms127_248893247;
T7*ms36_360;
T7*ms36_370;
T7*ms36_375;
T7*ms36_385;
T7*ms36_390;
T7*ms127_10aa;
T7*ms74_16602;
T7*ms164_1658706155;
T7*ms126_2048762;
T7*ms128_27351412;
T7*ms68_33463794;
T7*ms74_17651;
T7*ms127_393297;
T7*ms162_1386254719;
T7*ms127_10aaaaaaaaa;
T7*ms127_443097;
T7*ms127_430299720;
T7*ms17_322;
T7*ms127_10aaaaaa;
T7*ms93_39610347;
T7*ms127_525854605;
T7*ms82_34a;
T7*ms158_2425;
T7*ms82_632;
T7*ms82_637;
T7*ms128_56900637;
T7*ms82_600314783;
T7*ms165_2425;
T7*ms73_247323012;
T7*ms68_247323012;
T7*ms165_581741755;
T7*ms126_10a;
T7*ms126_252;
T7*ms126_322;
T7*ms95_2079105;
T7*ms82_52110219;
T7*ms35_63105;
T7*ms93_2079105;
T7*ms163_33463794;
T7*ms128_10313637;
T7*ms166_1325625;
T7*ms73_10;
T7*ms68_10;
T7*ms82_3175;
T7*ms74_10;
T7*ms163_83;
T7*ms33_319144a;
T7*ms163_84;
T7*ms163_86;
T7*ms94_1325625;
T7*ms127_180;
T7*ms127_10a;
T7*ms82_34aa;
T7*ms82_4992;
T7*ms74_265794;
T7*ms158_1578465704;
T7*ms126_545547512;
T7*ms94_265794;
T7*ms82_34;
T7*ms93_574977583;
T7*ms82_0a;
T7*ms126_21902512;
T7*ms94_248415980;
T7*ms166_76;
T7*ms166_86;
T7*ms126_569302452;
T7*ms82_0;
T7*ms127_2143930291;
T7*ms128_10a;
T7*ms128_1237804547;
T7*ms17_2079105;
T7*ms82_1962444;
T7*ms94_10;
T7*ms94_39;
T7*ms127_2062822;
T7*ms127_10aaaaa;
T7*ms74_2001008752;
T7*ms95_10;
T7*ms95_48;
T7*ms95_49;
T7*ms127_10818;
T7*ms127_12129;
T7*ms127_11657;
T7*ms126_10aa;
T7*ms127_11907;
T7*ms127_13014;
T7*ms82_1597872847;
T7*ms127_12590;
T7*ms128_10aa;
T7*ms94_27092;
T7*ms127_12999;
T7*ms95_10527487;
T7*ms127_2052472;
T7*ms127_2247022;
T7*ms127_266568097;
T7*ms126_7487;
T7*ms166_1658653172;
T7*ms33_319144;
T7*ms162_2425;
T7*ms164_2425;
T7*ms70_2425;
T7*ms127_890392572;
T7*ms94_2079105;
T7*ms127_647764604;
T7*ms127_10aaa;
T7*ms92_2079105;
T7*ms127_10aaaaaaaa;
T7*ms82_3175a;
T7*ms94_2425;
T7*ms94_9936697;
T7*ms163_296345362;
T7*ms74_88721;
T7*ms74_247323012;
T7*ms74_10a;
T7*ms127_271144;
T7*ms74_443;
T7*ms127_10aaaa;
T7*ms74_483;
T7*ms94_205;
T7*ms73_1325625;
T7*ms92_266664786;


T7*se_ms(int c,char*e){
/* Allocation of a Manifest STRING.*/
T7*s=((T7*)se_malloc(sizeof(gc7)));
((gc7*)s)->header.flag=FSOH_MARKED;
s->id=7;
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return s;}


T7*se_string(char*e){
/* Creation of an Eiffel STRING by copying C char*e */
int c=strlen(e);
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return s;}


void se_msi1(void){
ms126_39610347=se_ms(9,"Machine: ");
ms92_58545095=se_ms(18,"Import Buzz file: ");
ms127_1849750926=se_ms(12,"attr count: ");
ms36_70=se_ms(1,"F");
ms36_65=se_ms(1,"A");
ms36_71=se_ms(1,"G");
ms36_66=se_ms(1,"B");
ms36_67=se_ms(1,"C");
ms36_68=se_ms(1,"D");
ms36_69=se_ms(1,"E");
ms134_1812835366=se_ms(19,"Unhandled machine: ");
ms127_10aaaaaaa=se_ms(1,"\n");
ms82_420719=se_ms(6,"name \"");
ms74_17651a=se_ms(4,"sine");
ms126_10=se_ms(1,"\n");
ms163_690=se_ms(2,"vd");
ms127_10=se_ms(1,"\n");
ms72_319144=se_ms(6,"Master");
ms128_10=se_ms(1,"\n");
ms95_248415980=se_ms(10,"buttondown");
ms134_10=se_ms(1,"\n");
ms93_41083572=se_ms(9,"Pattern: ");
ms127_1137=se_ms(3," = ");
ms127_248893247=se_ms(10,"cur off : ");
ms36_360=se_ms(2,"A#");
ms36_370=se_ms(2,"C#");
ms36_375=se_ms(2,"D#");
ms36_385=se_ms(2,"F#");
ms36_390=se_ms(2,"G#");
ms127_10aa=se_ms(1,"\n");
ms74_16602=se_ms(4,"kick");
ms164_1658706155=se_ms(14,"Jeskola Reverb");
ms126_2048762=se_ms(7,"x, y = ");
ms128_27351412=se_ms(9,": put at ");
ms68_33463794=se_ms(9,"BLTracker");
ms74_17651=se_ms(4,"sine");
ms127_393297=se_ms(6,"attr: ");
ms162_1386254719=se_ms(13,"Jeskola Delay");
ms127_10aaaaaaaaa=se_ms(1,"\n");
ms127_443097=se_ms(6,"size: ");
ms127_430299720=se_ms(21,"n > buzz.wave_count!\n");
ms17_322=se_ms(2,": ");
ms127_10aaaaaa=se_ms(1,"\n");
ms93_39610347=se_ms(9,"Machine: ");
ms127_525854605=se_ms(29,"can\'t handle this wav format\n");
ms82_34a=se_ms(1,"\"");
ms158_2425=se_ms(3,"NOP");
ms82_632=se_ms(2,"x ");
ms82_637=se_ms(2,"y ");
ms128_56900637=se_ms(9,"volume = ");
se_msi2();
}


void se_msi2(void){
ms82_600314783=se_ms(13,"start machine");
ms165_2425=se_ms(3,"NOP");
ms73_247323012=se_ms(10,"command = ");
ms68_247323012=se_ms(10,"command = ");
ms165_581741755=se_ms(12,"Jeskola EQ-3");
ms126_10a=se_ms(1,"\n");
ms126_252=se_ms(2,", ");
ms126_322=se_ms(2,": ");
ms95_2079105=se_ms(7,"keydown");
ms82_52110219=se_ms(9,"machine \"");
ms35_63105=se_ms(5,"SETUP");
ms93_2079105=se_ms(7,"keydown");
ms163_33463794=se_ms(9,"BLTracker");
ms128_10313637=se_ms(8,"index = ");
ms166_1325625=se_ms(7,"BLBass2");
ms73_10=se_ms(1,"\n");
ms68_10=se_ms(1,"\n");
ms82_3175=se_ms(3,"end");
ms74_10=se_ms(1,"\n");
ms163_83=se_ms(1,"S");
ms33_319144a=se_ms(6,"Master");
ms163_84=se_ms(1,"T");
ms163_86=se_ms(1,"V");
ms94_1325625=se_ms(7,"BLBass2");
ms127_180=se_ms(2,"\"\n");
ms127_10a=se_ms(1,"\n");
ms82_34aa=se_ms(1,"\"");
ms82_4992=se_ms(4,"    ");
ms74_265794=se_ms(6,"BLDrum");
ms158_1578465704=se_ms(18,"Jeskola Distortion");
ms126_545547512=se_ms(11,", offset = ");
ms94_265794=se_ms(6,"BLDrum");
ms82_34=se_ms(1,"\"");
ms93_574977583=se_ms(41,"Press Ctrl-Enter to create a new pattern.");
ms82_0a=se_ms(0,"");
ms126_21902512=se_ms(9,", size = ");
ms94_248415980=se_ms(10,"buttondown");
ms166_76=se_ms(1,"L");
ms166_86=se_ms(1,"V");
ms126_569302452=se_ms(16,"connection from ");
ms82_0=se_ms(0,"");
ms127_2143930291=se_ms(12,"index /= i!\n");
ms128_10a=se_ms(1,"\n");
ms128_1237804547=se_ms(11,"converting ");
ms17_2079105=se_ms(7,"keydown");
ms82_1962444=se_ms(7,"class \"");
ms94_10=se_ms(1,"\n");
ms94_39=se_ms(1,"\'");
ms127_2062822=se_ms(7,"index: ");
ms127_10aaaaa=se_ms(1,"\n");
se_msi3();
}


void se_msi3(void){
ms74_2001008752=se_ms(22,"command is noteworthy\n");
ms95_10=se_ms(1,"\n");
ms95_48=se_ms(1,"0");
ms95_49=se_ms(1,"1");
ms127_10818=se_ms(4,"CONN");
ms127_12129=se_ms(4,"PATT");
ms127_11657=se_ms(4,"MACH");
ms126_10aa=se_ms(1,"\n");
ms127_11907=se_ms(4,"Buzz");
ms127_13014=se_ms(4,"WAVT");
ms82_1597872847=se_ms(12,"start zorder");
ms127_12590=se_ms(4,"SEQU");
ms128_10aa=se_ms(1,"\n");
ms94_27092=se_ms(5," --> ");
ms127_12999=se_ms(4,"WAVE");
ms95_10527487=se_ms(8,"jump to ");
ms127_2052472=se_ms(7,"gsize: ");
ms127_2247022=se_ms(7,"total: ");
ms127_266568097=se_ms(10,"msd size: ");
ms126_7487=se_ms(4," to ");
ms166_1658653172=se_ms(14,"Jeskola Bass 2");
ms33_319144=se_ms(6,"Master");
ms162_2425=se_ms(3,"NOP");
ms164_2425=se_ms(3,"NOP");
ms70_2425=se_ms(3,"NOP");
ms127_890392572=se_ms(13,"parsing MACH\n");
ms94_2079105=se_ms(7,"keydown");
ms127_647764604=se_ms(25,"didn\'t reach end of file\n");
ms127_10aaa=se_ms(1,"\n");
ms92_2079105=se_ms(7,"keydown");
ms127_10aaaaaaaa=se_ms(1,"\n");
ms82_3175a=se_ms(3,"end");
ms94_2425=se_ms(3,"NOP");
ms94_9936697=se_ms(8,"buttonup");
ms163_296345362=se_ms(15,"Jeskola Tracker");
ms74_88721=se_ms(5,"snare");
ms74_247323012=se_ms(10,"command = ");
ms74_10a=se_ms(1,"\n");
ms127_271144=se_ms(6,"DLL: \"");
ms74_443=se_ms(2,"KD");
ms127_10aaaa=se_ms(1,"\n");
ms74_483=se_ms(2,"SD");
ms94_205=se_ms(2,"\'\n");
ms73_1325625=se_ms(7,"BLBass2");
ms92_266664786=se_ms(19,"error loading file\n");
}


void manifest_string_mark1(void){
((rsoh*)(ms126_39610347->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms92_58545095->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_1849750926->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_70->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_65->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_71->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_66->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_67->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_68->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_69->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms134_1812835366->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaaaaaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_420719->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_17651a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms163_690->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms72_319144->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms95_248415980->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms134_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms93_41083572->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_1137->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_248893247->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_360->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_370->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_375->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_385->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms36_390->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_16602->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms164_1658706155->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_2048762->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_27351412->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms68_33463794->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_17651->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_393297->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms162_1386254719->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaaaaaaaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_443097->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_430299720->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms17_322->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaaaaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms93_39610347->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_525854605->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_34a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms158_2425->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_632->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_637->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_56900637->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_600314783->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms165_2425->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms73_247323012->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms68_247323012->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms165_581741755->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_10a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_252->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_322->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms95_2079105->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_52110219->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms35_63105->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms93_2079105->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms163_33463794->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_10313637->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms166_1325625->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms73_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms68_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_3175->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms163_83->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms33_319144a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms163_84->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms163_86->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_1325625->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_180->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_34aa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_4992->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_265794->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms158_1578465704->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_545547512->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_265794->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_34->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms93_574977583->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_0a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_21902512->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_248415980->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms166_76->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms166_86->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_569302452->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_0->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_2143930291->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_10a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_1237804547->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms17_2079105->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_1962444->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_39->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_2062822->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaaaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_2001008752->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms95_10->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms95_48->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms95_49->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10818->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_12129->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_11657->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_10aa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_11907->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_13014->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_1597872847->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_12590->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms128_10aa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_27092->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_12999->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms95_10527487->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_2052472->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_2247022->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_266568097->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms126_7487->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms166_1658653172->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms33_319144->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms162_2425->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms164_2425->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms70_2425->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_890392572->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_2079105->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_647764604->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms92_2079105->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaaaaaaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms82_3175a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_2425->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_9936697->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms163_296345362->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_88721->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_247323012->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_10a->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_271144->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_443->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms127_10aaaa->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms74_483->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms94_205->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms73_1325625->_storage)-1)->header.magic_flag=RSOH_MARKED;
((rsoh*)(ms92_266664786->_storage)-1)->header.magic_flag=RSOH_MARKED;
}


void once_function_mark(void){
if(NULL!=oBC36scale_array)gc_mark182((T182*)(oBC36scale_array));
if(NULL!=oBC130hex255table)gc_mark182((T182*)(oBC130hex255table));
if(NULL!=oBC8string_buffer)gc_mark7((T7*)(oBC8string_buffer));
if(NULL!=oBC1io)gc_mark84((T84*)(oBC1io));
if(NULL!=oBC36note_rank_array)gc_mark143((T143*)(oBC36note_rank_array));
if(NULL!=oBC36note_freq_table)Xgc_mark117((T0*)(oBC36note_freq_table));
if(NULL!=oBC20song)gc_mark33((T33*)(oBC20song));
if(NULL!=oBC18white)gc_mark51((T51*)(oBC18white));
if(NULL!=oBC18blue)gc_mark51((T51*)(oBC18blue));
if(NULL!=oBC73saw_table)Xgc_mark117((T0*)(oBC73saw_table));
if(NULL!=oBC18red)gc_mark51((T51*)(oBC18red));
if(NULL!=oBC18green)gc_mark51((T51*)(oBC18green));
if(NULL!=oBC73fade_table)Xgc_mark117((T0*)(oBC73fade_table));
if(NULL!=oBC94arrow_image)gc_mark50((T50*)(oBC94arrow_image));
if(NULL!=oBC18black)gc_mark51((T51*)(oBC18black));
if(NULL!=oBC129conv_table)gc_mark159((T159*)(oBC129conv_table));
if(NULL!=oBC5sprintf_double_buffer)gc_mark9((oBC5sprintf_double_buffer));
if(NULL!=oBC83tmp_string)gc_mark7((T7*)(oBC83tmp_string));
if(NULL!=oBC2tmp_string)gc_mark7((T7*)(oBC2tmp_string));
if(NULL!=oBC17test_saver)gc_mark82((T82*)(oBC17test_saver));
if(NULL!=oBC34machine_class_table)gc_mark45((T45*)(oBC34machine_class_table));
}
/*
-- This file is  free  software, which  comes  along  with  SmallEiffel. This
-- software  is  distributed  in the hope that it will be useful, but WITHOUT 
-- ANY  WARRANTY;  without  even  the  implied warranty of MERCHANTABILITY or
-- FITNESS  FOR A PARTICULAR PURPOSE. You can modify it as you want, provided
-- this header is kept unaltered, and a notification of the changes is added.
-- You  are  allowed  to  redistribute  it and sell it, alone or as a part of 
-- another product.
--          Copyright (C) 1994-98 LORIA - UHP - CRIN - INRIA - FRANCE
--            Dominique COLNET and Suzanne COLLIN - colnet@loria.fr 
--                       http://www.loria.fr/SmallEiffel
--
*/
/* 
   Stack and Registers traversal for PC Linux with gcc.
   Addresses decrease as the stack grows.
   Registers are saved using SETJMP().
   A little correction of the non-accurate `stack_bottom' seams to 
   be necessary here.
*/

void mark_stack_and_registers (void) {
  void** max = stack_bottom + 10; /* stack_bottom correction here. */
  void** stack_pointer;
  jmp_buf registers;

  (void)setjmp(registers);
  stack_pointer = ((void**)(&registers));
  while (stack_pointer < max) {
    gc_mark(*(stack_pointer++));
  }
}


void gc_start(void){
if(gc_is_off)return;
if(garbage_delayed())return;
gcmt_tail_addr=(((char*)(gcmt[gcmt_used-1]))+(gcmt[gcmt_used-1])->size);
((gc17*)eiffel_root_object)->header.flag=FSOH_UNMARKED;
gc_free84=NULL;
gc_free95=NULL;
if(na_env157.store_left>0){
na_env157.store->header.size=na_env157.store_left;
na_env157.store->header.magic_flag=RSOH_FREE;
na_env157.store_left=0;
}
na_env157.chunk_list=NULL;
na_env157.store_chunk=NULL;
gc_free196=NULL;
gc_free73=NULL;
gc_free171=NULL;
gc_free162=NULL;
if(na_env149.store_left>0){
na_env149.store->header.size=na_env149.store_left;
na_env149.store->header.magic_flag=RSOH_FREE;
na_env149.store_left=0;
}
na_env149.chunk_list=NULL;
na_env149.store_chunk=NULL;
gc_free176=NULL;
gc_free131=NULL;
gc_free158=NULL;
gc_free143=NULL;
if(na_env217.store_left>0){
na_env217.store->header.size=na_env217.store_left;
na_env217.store->header.magic_flag=RSOH_FREE;
na_env217.store_left=0;
}
na_env217.chunk_list=NULL;
na_env217.store_chunk=NULL;
if(na_env161.store_left>0){
na_env161.store->header.size=na_env161.store_left;
na_env161.store->header.magic_flag=RSOH_FREE;
na_env161.store_left=0;
}
na_env161.chunk_list=NULL;
na_env161.store_chunk=NULL;
gc_free135=NULL;
if(na_env139.store_left>0){
na_env139.store->header.size=na_env139.store_left;
na_env139.store->header.magic_flag=RSOH_FREE;
na_env139.store_left=0;
}
na_env139.chunk_list=NULL;
na_env139.store_chunk=NULL;
gc_free128=NULL;
gc_free113=NULL;
gc_free68=NULL;
gc_free17=NULL;
gc_free206=NULL;
if(na_env221.store_left>0){
na_env221.store->header.size=na_env221.store_left;
na_env221.store->header.magic_flag=RSOH_FREE;
na_env221.store_left=0;
}
na_env221.chunk_list=NULL;
na_env221.store_chunk=NULL;
gc_free137=NULL;
gc_free27=NULL;
gc_free45=NULL;
gc_free60=NULL;
gc_free62=NULL;
gc_free121=NULL;
gc_free160=NULL;
gc_free165=NULL;
gc_free98=NULL;
gc_free80=NULL;
gc_free134=NULL;
gc_free92=NULL;
gc_free167=NULL;
gc_free50=NULL;
gc_free172=NULL;
gc_free70=NULL;
if(na_env169.store_left>0){
na_env169.store->header.size=na_env169.store_left;
na_env169.store->header.magic_flag=RSOH_FREE;
na_env169.store_left=0;
}
na_env169.chunk_list=NULL;
na_env169.store_chunk=NULL;
gc_free207=NULL;
gc_free51=NULL;
if(na_env118.store_left>0){
na_env118.store->header.size=na_env118.store_left;
na_env118.store->header.magic_flag=RSOH_FREE;
na_env118.store_left=0;
}
na_env118.chunk_list=NULL;
na_env118.store_chunk=NULL;
gc_free81=NULL;
if(na_env152.store_left>0){
na_env152.store->header.size=na_env152.store_left;
na_env152.store->header.magic_flag=RSOH_FREE;
na_env152.store_left=0;
}
na_env152.chunk_list=NULL;
na_env152.store_chunk=NULL;
if(na_env59.store_left>0){
na_env59.store->header.size=na_env59.store_left;
na_env59.store->header.magic_flag=RSOH_FREE;
na_env59.store_left=0;
}
na_env59.chunk_list=NULL;
na_env59.store_chunk=NULL;
gc_free67=NULL;
gc_free146=NULL;
gc_free72=NULL;
if(na_env189.store_left>0){
na_env189.store->header.size=na_env189.store_left;
na_env189.store->header.magic_flag=RSOH_FREE;
na_env189.store_left=0;
}
na_env189.chunk_list=NULL;
na_env189.store_chunk=NULL;
gc_free187=NULL;
gc_free126=NULL;
gc_free163=NULL;
gc_free159=NULL;
gc_free120=NULL;
gc_free76=NULL;
gc_free65=NULL;
if(na_env99.store_left>0){
na_env99.store->header.size=na_env99.store_left;
na_env99.store->header.magic_flag=RSOH_FREE;
na_env99.store_left=0;
}
na_env99.chunk_list=NULL;
na_env99.store_chunk=NULL;
if(na_env142.store_left>0){
na_env142.store->header.size=na_env142.store_left;
na_env142.store->header.magic_flag=RSOH_FREE;
na_env142.store_left=0;
}
na_env142.chunk_list=NULL;
na_env142.store_chunk=NULL;
gc_free150=NULL;
if(na_env181.store_left>0){
na_env181.store->header.size=na_env181.store_left;
na_env181.store->header.magic_flag=RSOH_FREE;
na_env181.store_left=0;
}
na_env181.chunk_list=NULL;
na_env181.store_chunk=NULL;
if(na_env174.store_left>0){
na_env174.store->header.size=na_env174.store_left;
na_env174.store->header.magic_flag=RSOH_FREE;
na_env174.store_left=0;
}
na_env174.chunk_list=NULL;
na_env174.store_chunk=NULL;
if(na_env78.store_left>0){
na_env78.store->header.size=na_env78.store_left;
na_env78.store->header.magic_flag=RSOH_FREE;
na_env78.store_left=0;
}
na_env78.chunk_list=NULL;
na_env78.store_chunk=NULL;
gc_free184=NULL;
gc_free43=NULL;
gc_free110=NULL;
gc_free205=NULL;
gc_free56=NULL;
gc_free108=NULL;
gc_free58=NULL;
gc_free66=NULL;
gc_free166=NULL;
gc_free204=NULL;
gc_free136=NULL;
if(na_env177.store_left>0){
na_env177.store->header.size=na_env177.store_left;
na_env177.store->header.magic_flag=RSOH_FREE;
na_env177.store_left=0;
}
na_env177.chunk_list=NULL;
na_env177.store_chunk=NULL;
gc_free7=NULL;
gc_free170=NULL;
gc_free55=NULL;
gc_free57=NULL;
gc_free127=NULL;
gc_free82=NULL;
gc_free194=NULL;
gc_free155=NULL;
if(na_env9.store_left>0){
na_env9.store->header.size=na_env9.store_left;
na_env9.store->header.magic_flag=RSOH_FREE;
na_env9.store_left=0;
}
na_env9.chunk_list=NULL;
na_env9.store_chunk=NULL;
gc_free198=NULL;
gc_free203=NULL;
gc_free94=NULL;
gc_free47=NULL;
gc_free77=NULL;
if(na_env64.store_left>0){
na_env64.store->header.size=na_env64.store_left;
na_env64.store->header.magic_flag=RSOH_FREE;
na_env64.store_left=0;
}
na_env64.chunk_list=NULL;
na_env64.store_chunk=NULL;
gc_free188=NULL;
gc_free93=NULL;
gc_free75=NULL;
gc_free23=NULL;
gc_free140=NULL;
gc_free147=NULL;
gc_free190=NULL;
gc_free33=NULL;
if(na_env199.store_left>0){
na_env199.store->header.size=na_env199.store_left;
na_env199.store->header.magic_flag=RSOH_FREE;
na_env199.store_left=0;
}
na_env199.chunk_list=NULL;
na_env199.store_chunk=NULL;
gc_free132=NULL;
gc_free180=NULL;
gc_free182=NULL;
gc_free52=NULL;
gc_free61=NULL;
if(na_env48.store_left>0){
na_env48.store->header.size=na_env48.store_left;
na_env48.store->header.magic_flag=RSOH_FREE;
na_env48.store_left=0;
}
na_env48.chunk_list=NULL;
na_env48.store_chunk=NULL;
gc_free200=NULL;
if(na_env154.store_left>0){
na_env154.store->header.size=na_env154.store_left;
na_env154.store->header.magic_flag=RSOH_FREE;
na_env154.store_left=0;
}
na_env154.chunk_list=NULL;
na_env154.store_chunk=NULL;
gc_free133=NULL;
if(na_env145.store_left>0){
na_env145.store->header.size=na_env145.store_left;
na_env145.store->header.magic_flag=RSOH_FREE;
na_env145.store_left=0;
}
na_env145.chunk_list=NULL;
na_env145.store_chunk=NULL;
gc_free202=NULL;
gc_free91=NULL;
gc_free112=NULL;
gc_free41=NULL;
gc_free123=NULL;
gc_free106=NULL;
if(na_env223.store_left>0){
na_env223.store->header.size=na_env223.store_left;
na_env223.store->header.magic_flag=RSOH_FREE;
na_env223.store_left=0;
}
na_env223.chunk_list=NULL;
na_env223.store_chunk=NULL;
gc_free79=NULL;
gc_free63=NULL;
gc_free117=NULL;
gc_free164=NULL;
gc_free218=NULL;
gc_free175=NULL;
gc_free74=NULL;
gc_mark17(eiffel_root_object);
manifest_string_mark1();
once_function_mark();
mark_stack_and_registers();
gc_sweep();
gc_start_count++;
}
gc84*store84=NULL;
int store_left84=0;
fsoc*store_chunk84=NULL;
gc84*gc_free84=NULL;
gc95*store95=NULL;
int store_left95=0;
fsoc*store_chunk95=NULL;
gc95*gc_free95=NULL;
na_env na_env157={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark157};
gc196*store196=NULL;
int store_left196=0;
fsoc*store_chunk196=NULL;
gc196*gc_free196=NULL;
gc73*store73=NULL;
int store_left73=0;
fsoc*store_chunk73=NULL;
gc73*gc_free73=NULL;
gc171*store171=NULL;
int store_left171=0;
fsoc*store_chunk171=NULL;
gc171*gc_free171=NULL;
gc162*store162=NULL;
int store_left162=0;
fsoc*store_chunk162=NULL;
gc162*gc_free162=NULL;
na_env na_env149={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark149};
gc176*store176=NULL;
int store_left176=0;
fsoc*store_chunk176=NULL;
gc176*gc_free176=NULL;
gc131*store131=NULL;
int store_left131=0;
fsoc*store_chunk131=NULL;
gc131*gc_free131=NULL;
gc158*store158=NULL;
int store_left158=0;
fsoc*store_chunk158=NULL;
gc158*gc_free158=NULL;
gc143*store143=NULL;
int store_left143=0;
fsoc*store_chunk143=NULL;
gc143*gc_free143=NULL;
na_env na_env217={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark217};
na_env na_env161={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark161};
gc135*store135=NULL;
int store_left135=0;
fsoc*store_chunk135=NULL;
gc135*gc_free135=NULL;
na_env na_env139={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark139};
gc128*store128=NULL;
int store_left128=0;
fsoc*store_chunk128=NULL;
gc128*gc_free128=NULL;
gc113*store113=NULL;
int store_left113=0;
fsoc*store_chunk113=NULL;
gc113*gc_free113=NULL;
gc68*store68=NULL;
int store_left68=0;
fsoc*store_chunk68=NULL;
gc68*gc_free68=NULL;
gc17*store17=NULL;
int store_left17=0;
fsoc*store_chunk17=NULL;
gc17*gc_free17=NULL;
gc206*store206=NULL;
int store_left206=0;
fsoc*store_chunk206=NULL;
gc206*gc_free206=NULL;
na_env na_env221={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark221};
gc137*store137=NULL;
int store_left137=0;
fsoc*store_chunk137=NULL;
gc137*gc_free137=NULL;
gc27*store27=NULL;
int store_left27=0;
fsoc*store_chunk27=NULL;
gc27*gc_free27=NULL;
gc45*store45=NULL;
int store_left45=0;
fsoc*store_chunk45=NULL;
gc45*gc_free45=NULL;
gc60*store60=NULL;
int store_left60=0;
fsoc*store_chunk60=NULL;
gc60*gc_free60=NULL;
gc62*store62=NULL;
int store_left62=0;
fsoc*store_chunk62=NULL;
gc62*gc_free62=NULL;
gc121*store121=NULL;
int store_left121=0;
fsoc*store_chunk121=NULL;
gc121*gc_free121=NULL;
gc160*store160=NULL;
int store_left160=0;
fsoc*store_chunk160=NULL;
gc160*gc_free160=NULL;
gc165*store165=NULL;
int store_left165=0;
fsoc*store_chunk165=NULL;
gc165*gc_free165=NULL;
gc98*store98=NULL;
int store_left98=0;
fsoc*store_chunk98=NULL;
gc98*gc_free98=NULL;
gc80*store80=NULL;
int store_left80=0;
fsoc*store_chunk80=NULL;
gc80*gc_free80=NULL;
gc134*store134=NULL;
int store_left134=0;
fsoc*store_chunk134=NULL;
gc134*gc_free134=NULL;
gc92*store92=NULL;
int store_left92=0;
fsoc*store_chunk92=NULL;
gc92*gc_free92=NULL;
gc167*store167=NULL;
int store_left167=0;
fsoc*store_chunk167=NULL;
gc167*gc_free167=NULL;
gc50*store50=NULL;
int store_left50=0;
fsoc*store_chunk50=NULL;
gc50*gc_free50=NULL;
gc172*store172=NULL;
int store_left172=0;
fsoc*store_chunk172=NULL;
gc172*gc_free172=NULL;
gc70*store70=NULL;
int store_left70=0;
fsoc*store_chunk70=NULL;
gc70*gc_free70=NULL;
na_env na_env169={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark169};
gc207*store207=NULL;
int store_left207=0;
fsoc*store_chunk207=NULL;
gc207*gc_free207=NULL;
gc51*store51=NULL;
int store_left51=0;
fsoc*store_chunk51=NULL;
gc51*gc_free51=NULL;
na_env na_env118={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark118};
gc81*store81=NULL;
int store_left81=0;
fsoc*store_chunk81=NULL;
gc81*gc_free81=NULL;
na_env na_env152={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark152};
na_env na_env59={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark59};
gc67*store67=NULL;
int store_left67=0;
fsoc*store_chunk67=NULL;
gc67*gc_free67=NULL;
gc146*store146=NULL;
int store_left146=0;
fsoc*store_chunk146=NULL;
gc146*gc_free146=NULL;
gc72*store72=NULL;
int store_left72=0;
fsoc*store_chunk72=NULL;
gc72*gc_free72=NULL;
na_env na_env189={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark189};
gc187*store187=NULL;
int store_left187=0;
fsoc*store_chunk187=NULL;
gc187*gc_free187=NULL;
gc126*store126=NULL;
int store_left126=0;
fsoc*store_chunk126=NULL;
gc126*gc_free126=NULL;
gc163*store163=NULL;
int store_left163=0;
fsoc*store_chunk163=NULL;
gc163*gc_free163=NULL;
gc159*store159=NULL;
int store_left159=0;
fsoc*store_chunk159=NULL;
gc159*gc_free159=NULL;
gc120*store120=NULL;
int store_left120=0;
fsoc*store_chunk120=NULL;
gc120*gc_free120=NULL;
gc76*store76=NULL;
int store_left76=0;
fsoc*store_chunk76=NULL;
gc76*gc_free76=NULL;
gc65*store65=NULL;
int store_left65=0;
fsoc*store_chunk65=NULL;
gc65*gc_free65=NULL;
na_env na_env99={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark99};
na_env na_env142={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark142};
gc150*store150=NULL;
int store_left150=0;
fsoc*store_chunk150=NULL;
gc150*gc_free150=NULL;
na_env na_env181={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark181};
na_env na_env174={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark174};
na_env na_env78={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark78};
gc184*store184=NULL;
int store_left184=0;
fsoc*store_chunk184=NULL;
gc184*gc_free184=NULL;
gc43*store43=NULL;
int store_left43=0;
fsoc*store_chunk43=NULL;
gc43*gc_free43=NULL;
gc110*store110=NULL;
int store_left110=0;
fsoc*store_chunk110=NULL;
gc110*gc_free110=NULL;
gc205*store205=NULL;
int store_left205=0;
fsoc*store_chunk205=NULL;
gc205*gc_free205=NULL;
gc56*store56=NULL;
int store_left56=0;
fsoc*store_chunk56=NULL;
gc56*gc_free56=NULL;
gc108*store108=NULL;
int store_left108=0;
fsoc*store_chunk108=NULL;
gc108*gc_free108=NULL;
gc58*store58=NULL;
int store_left58=0;
fsoc*store_chunk58=NULL;
gc58*gc_free58=NULL;
gc66*store66=NULL;
int store_left66=0;
fsoc*store_chunk66=NULL;
gc66*gc_free66=NULL;
gc166*store166=NULL;
int store_left166=0;
fsoc*store_chunk166=NULL;
gc166*gc_free166=NULL;
gc204*store204=NULL;
int store_left204=0;
fsoc*store_chunk204=NULL;
gc204*gc_free204=NULL;
gc136*store136=NULL;
int store_left136=0;
fsoc*store_chunk136=NULL;
gc136*gc_free136=NULL;
na_env na_env177={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark177};
gc7*store7=NULL;
int store_left7=0;
fsoc*store_chunk7=NULL;
gc7*gc_free7=NULL;
gc170*store170=NULL;
int store_left170=0;
fsoc*store_chunk170=NULL;
gc170*gc_free170=NULL;
gc55*store55=NULL;
int store_left55=0;
fsoc*store_chunk55=NULL;
gc55*gc_free55=NULL;
gc57*store57=NULL;
int store_left57=0;
fsoc*store_chunk57=NULL;
gc57*gc_free57=NULL;
gc127*store127=NULL;
int store_left127=0;
fsoc*store_chunk127=NULL;
gc127*gc_free127=NULL;
gc82*store82=NULL;
int store_left82=0;
fsoc*store_chunk82=NULL;
gc82*gc_free82=NULL;
gc194*store194=NULL;
int store_left194=0;
fsoc*store_chunk194=NULL;
gc194*gc_free194=NULL;
gc155*store155=NULL;
int store_left155=0;
fsoc*store_chunk155=NULL;
gc155*gc_free155=NULL;
na_env na_env9={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark9};
gc198*store198=NULL;
int store_left198=0;
fsoc*store_chunk198=NULL;
gc198*gc_free198=NULL;
gc203*store203=NULL;
int store_left203=0;
fsoc*store_chunk203=NULL;
gc203*gc_free203=NULL;
gc94*store94=NULL;
int store_left94=0;
fsoc*store_chunk94=NULL;
gc94*gc_free94=NULL;
gc47*store47=NULL;
int store_left47=0;
fsoc*store_chunk47=NULL;
gc47*gc_free47=NULL;
gc77*store77=NULL;
int store_left77=0;
fsoc*store_chunk77=NULL;
gc77*gc_free77=NULL;
na_env na_env64={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark64};
gc188*store188=NULL;
int store_left188=0;
fsoc*store_chunk188=NULL;
gc188*gc_free188=NULL;
gc93*store93=NULL;
int store_left93=0;
fsoc*store_chunk93=NULL;
gc93*gc_free93=NULL;
gc75*store75=NULL;
int store_left75=0;
fsoc*store_chunk75=NULL;
gc75*gc_free75=NULL;
gc23*store23=NULL;
int store_left23=0;
fsoc*store_chunk23=NULL;
gc23*gc_free23=NULL;
gc140*store140=NULL;
int store_left140=0;
fsoc*store_chunk140=NULL;
gc140*gc_free140=NULL;
gc147*store147=NULL;
int store_left147=0;
fsoc*store_chunk147=NULL;
gc147*gc_free147=NULL;
gc190*store190=NULL;
int store_left190=0;
fsoc*store_chunk190=NULL;
gc190*gc_free190=NULL;
gc33*store33=NULL;
int store_left33=0;
fsoc*store_chunk33=NULL;
gc33*gc_free33=NULL;
na_env na_env199={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark199};
gc132*store132=NULL;
int store_left132=0;
fsoc*store_chunk132=NULL;
gc132*gc_free132=NULL;
gc180*store180=NULL;
int store_left180=0;
fsoc*store_chunk180=NULL;
gc180*gc_free180=NULL;
gc182*store182=NULL;
int store_left182=0;
fsoc*store_chunk182=NULL;
gc182*gc_free182=NULL;
gc52*store52=NULL;
int store_left52=0;
fsoc*store_chunk52=NULL;
gc52*gc_free52=NULL;
gc61*store61=NULL;
int store_left61=0;
fsoc*store_chunk61=NULL;
gc61*gc_free61=NULL;
na_env na_env48={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark48};
gc200*store200=NULL;
int store_left200=0;
fsoc*store_chunk200=NULL;
gc200*gc_free200=NULL;
na_env na_env154={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark154};
gc133*store133=NULL;
int store_left133=0;
fsoc*store_chunk133=NULL;
gc133*gc_free133=NULL;
na_env na_env145={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark145};
gc202*store202=NULL;
int store_left202=0;
fsoc*store_chunk202=NULL;
gc202*gc_free202=NULL;
gc91*store91=NULL;
int store_left91=0;
fsoc*store_chunk91=NULL;
gc91*gc_free91=NULL;
gc112*store112=NULL;
int store_left112=0;
fsoc*store_chunk112=NULL;
gc112*gc_free112=NULL;
gc41*store41=NULL;
int store_left41=0;
fsoc*store_chunk41=NULL;
gc41*gc_free41=NULL;
gc123*store123=NULL;
int store_left123=0;
fsoc*store_chunk123=NULL;
gc123*gc_free123=NULL;
gc106*store106=NULL;
int store_left106=0;
fsoc*store_chunk106=NULL;
gc106*gc_free106=NULL;
na_env na_env223={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark223};
gc79*store79=NULL;
int store_left79=0;
fsoc*store_chunk79=NULL;
gc79*gc_free79=NULL;
gc63*store63=NULL;
int store_left63=0;
fsoc*store_chunk63=NULL;
gc63*gc_free63=NULL;
gc117*store117=NULL;
int store_left117=0;
fsoc*store_chunk117=NULL;
gc117*gc_free117=NULL;
gc164*store164=NULL;
int store_left164=0;
fsoc*store_chunk164=NULL;
gc164*gc_free164=NULL;
gc218*store218=NULL;
int store_left218=0;
fsoc*store_chunk218=NULL;
gc218*gc_free218=NULL;
gc175*store175=NULL;
int store_left175=0;
fsoc*store_chunk175=NULL;
gc175*gc_free175=NULL;
gc74*store74=NULL;
int store_left74=0;
fsoc*store_chunk74=NULL;
gc74*gc_free74=NULL;


void gc_sweep84(fsoc*c){
gc84*o1,*o2,*flt,flh;
o1=((gc84*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store84;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free84;
gc_free84=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free84;
gc_free84=flh.header.next;
}
}
}


void gc_mark84(T84*o){
((gc84*)o)->header.flag=FSOH_MARKED;
}


void gc_align_mark84(fsoc*c,gc84*p){
gc84*b=((gc84*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store84)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T84*o=(&(p->object));
((gc84*)o)->header.flag=FSOH_MARKED;
}
}
}
fsoc H84={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark84,
(void(*)(mch*))gc_sweep84},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc84))-1)};


T84*new84(void){
gc84*n;
fsoc*c;
if(store_left84>1){
store_left84--;
n=store84++;
}
else if(gc_free84!=NULL){
n=gc_free84;
gc_free84=n->header.next;
}
else if(store_left84==1){
store_left84=0;
store_chunk84->header.state_type=FSO_USED_CHUNK;
n=store84++;
}
else{
c=gc_fsoc_get1();
if(gc_free84!=NULL){
n=gc_free84;
gc_free84=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk84=c;
*store_chunk84=H84;
store84=((gc84*)(&(store_chunk84->first_object)));
store_left84=H84.count_minus_one;
n=store84++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M84;
return((T84*)n);
}


void gc_sweep95(fsoc*c){
gc95*o1,*o2,*flt,flh;
o1=((gc95*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store95;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free95;
gc_free95=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free95;
gc_free95=flh.header.next;
}
}
}


void gc_mark95(T95*o){
((gc95*)o)->header.flag=FSOH_MARKED;
}


void gc_align_mark95(fsoc*c,gc95*p){
gc95*b=((gc95*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store95)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T95*o=(&(p->object));
((gc95*)o)->header.flag=FSOH_MARKED;
}
}
}
fsoc H95={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark95,
(void(*)(mch*))gc_sweep95},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc95))-1)};


T95*new95(void){
gc95*n;
fsoc*c;
if(store_left95>1){
store_left95--;
n=store95++;
}
else if(gc_free95!=NULL){
n=gc_free95;
gc_free95=n->header.next;
}
else if(store_left95==1){
store_left95=0;
store_chunk95->header.state_type=FSO_USED_CHUNK;
n=store95++;
}
else{
c=gc_fsoc_get1();
if(gc_free95!=NULL){
n=gc_free95;
gc_free95=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk95=c;
*store_chunk95=H95;
store95=((gc95*)(&(store_chunk95->first_object)));
store_left95=H95.count_minus_one;
n=store95++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M95;
return((T95*)n);
}


void gc_mark157(T157 o){
rsoh*h=((rsoh*)o)-1;
if((h->header.magic_flag)==RSOH_UNMARKED){
h->header.magic_flag=RSOH_MARKED;
{T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark132((T132*)(e));

}
}
}}


T157 new157(int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
if((size%sizeof(double))!=0)size+=(sizeof(double)-(size%sizeof(double)));
if (size<=(na_env157.store_left)){
rsoh*r=na_env157.store;
na_env157.store_left-=size;
if(na_env157.store_left>sizeof(rsoh)){
r->header.size=size;
na_env157.store=((rsoh*)(((char*)(na_env157.store))+size));
}
else {
r->header.size=size+na_env157.store_left;
na_env157.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T157)(r+1));
}
return((T157)new_na(&na_env157,size));
}


void gc_sweep196(fsoc*c){
gc196*o1,*o2,*flt,flh;
o1=((gc196*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store196;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free196;
gc_free196=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free196;
gc_free196=flh.header.next;
}
}
}


void gc_mark196(T196*o){
if(((gc196*)o)->header.flag==FSOH_UNMARKED){
((gc196*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_dictionary/*4*/)Xgc_mark197((T0*)(o->_dictionary/*4*/));
}}


void gc_align_mark196(fsoc*c,gc196*p){
gc196*b=((gc196*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store196)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T196*o=(&(p->object));
((gc196*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_dictionary/*4*/)Xgc_mark197((T0*)(o->_dictionary/*4*/));
}
}
}
fsoc H196={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark196,
(void(*)(mch*))gc_sweep196},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc196))-1)};


T196*new196(void){
gc196*n;
fsoc*c;
if(store_left196>1){
store_left196--;
n=store196++;
}
else if(gc_free196!=NULL){
n=gc_free196;
gc_free196=n->header.next;
}
else if(store_left196==1){
store_left196=0;
store_chunk196->header.state_type=FSO_USED_CHUNK;
n=store196++;
}
else{
c=gc_fsoc_get1();
if(gc_free196!=NULL){
n=gc_free196;
gc_free196=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk196=c;
*store_chunk196=H196;
store196=((gc196*)(&(store_chunk196->first_object)));
store_left196=H196.count_minus_one;
n=store196++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M196;
return((T196*)n);
}


void gc_sweep73(fsoc*c){
gc73*o1,*o2,*flt,flh;
o1=((gc73*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store73;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free73;
gc_free73=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free73;
gc_free73=flh.header.next;
}
}
}


void gc_mark73(T73*o){
if(((gc73*)o)->header.flag==FSOH_UNMARKED){
((gc73*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_wave_table/*66*/)Xgc_mark117((T0*)(o->_wave_table/*66*/));
if(NULL!=o->_image/*40*/)gc_mark50((T50*)(o->_image/*40*/));
if(NULL!=o->_setup_pattern/*20*/)gc_mark52((T52*)(o->_setup_pattern/*20*/));
if(NULL!=o->_pattern_list/*16*/)gc_mark60((T60*)(o->_pattern_list/*16*/));
if(NULL!=o->_pattern_table/*12*/)gc_mark62((T62*)(o->_pattern_table/*12*/));
if(NULL!=o->_in_connection/*8*/)gc_mark66((T66*)(o->_in_connection/*8*/));
if(NULL!=o->_name/*4*/)gc_mark7((T7*)(o->_name/*4*/));
}}


void gc_align_mark73(fsoc*c,gc73*p){
gc73*b=((gc73*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store73)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T73*o=(&(p->object));
((gc73*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_wave_table/*66*/)Xgc_mark117((T0*)(o->_wave_table/*66*/));
if(NULL!=o->_image/*40*/)gc_mark50((T50*)(o->_image/*40*/));
if(NULL!=o->_setup_pattern/*20*/)gc_mark52((T52*)(o->_setup_pattern/*20*/));
if(NULL!=o->_pattern_list/*16*/)gc_mark60((T60*)(o->_pattern_list/*16*/));
if(NULL!=o->_pattern_table/*12*/)gc_mark62((T62*)(o->_pattern_table/*12*/));
if(NULL!=o->_in_connection/*8*/)gc_mark66((T66*)(o->_in_connection/*8*/));
if(NULL!=o->_name/*4*/)gc_mark7((T7*)(o->_name/*4*/));
}
}
}
fsoc H73={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark73,
(void(*)(mch*))gc_sweep73},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc73))-1)};


T73*new73(void){
gc73*n;
fsoc*c;
if(store_left73>1){
store_left73--;
n=store73++;
}
else if(gc_free73!=NULL){
n=gc_free73;
gc_free73=n->header.next;
}
else if(store_left73==1){
store_left73=0;
store_chunk73->header.state_type=FSO_USED_CHUNK;
n=store73++;
}
else{
c=gc_fsoc_get1();
if(gc_free73!=NULL){
n=gc_free73;
gc_free73=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk73=c;
*store_chunk73=H73;
store73=((gc73*)(&(store_chunk73->first_object)));
store_left73=H73.count_minus_one;
n=store73++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M73;
return((T73*)n);
}


void gc_sweep171(fsoc*c){
gc171*o1,*o2,*flt,flh;
o1=((gc171*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store171;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free171;
gc_free171=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free171;
gc_free171=flh.header.next;
}
}
}


void gc_mark171(T171*o){
if(((gc171*)o)->header.flag==FSOH_UNMARKED){
((gc171*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_name/*4*/)gc_mark7((T7*)(o->_name/*4*/));
}}


void gc_align_mark171(fsoc*c,gc171*p){
gc171*b=((gc171*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store171)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T171*o=(&(p->object));
((gc171*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_name/*4*/)gc_mark7((T7*)(o->_name/*4*/));
}
}
}
fsoc H171={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark171,
(void(*)(mch*))gc_sweep171},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc171))-1)};


T171*new171(void){
gc171*n;
fsoc*c;
if(store_left171>1){
store_left171--;
n=store171++;
}
else if(gc_free171!=NULL){
n=gc_free171;
gc_free171=n->header.next;
}
else if(store_left171==1){
store_left171=0;
store_chunk171->header.state_type=FSO_USED_CHUNK;
n=store171++;
}
else{
c=gc_fsoc_get1();
if(gc_free171!=NULL){
n=gc_free171;
gc_free171=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk171=c;
*store_chunk171=H171;
store171=((gc171*)(&(store_chunk171->first_object)));
store_left171=H171.count_minus_one;
n=store171++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M171;
return((T171*)n);
}


void gc_sweep162(fsoc*c){
gc162*o1,*o2,*flt,flh;
o1=((gc162*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store162;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free162;
gc_free162=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free162;
gc_free162=flh.header.next;
}
}
}


void gc_mark162(T162*o){
((gc162*)o)->header.flag=FSOH_MARKED;
}


void gc_align_mark162(fsoc*c,gc162*p){
gc162*b=((gc162*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store162)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T162*o=(&(p->object));
((gc162*)o)->header.flag=FSOH_MARKED;
}
}
}
fsoc H162={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark162,
(void(*)(mch*))gc_sweep162},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc162))-1)};


T162*new162(void){
gc162*n;
fsoc*c;
if(store_left162>1){
store_left162--;
n=store162++;
}
else if(gc_free162!=NULL){
n=gc_free162;
gc_free162=n->header.next;
}
else if(store_left162==1){
store_left162=0;
store_chunk162->header.state_type=FSO_USED_CHUNK;
n=store162++;
}
else{
c=gc_fsoc_get1();
if(gc_free162!=NULL){
n=gc_free162;
gc_free162=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk162=c;
*store_chunk162=H162;
store162=((gc162*)(&(store_chunk162->first_object)));
store_left162=H162.count_minus_one;
n=store162++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M162;
return((T162*)n);
}


void gc_mark149(T149 o){
rsoh*h=((rsoh*)o)-1;
if((h->header.magic_flag)==RSOH_UNMARKED){
h->header.magic_flag=RSOH_MARKED;
{T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark146((T146*)(e));

}
}
}}


T149 new149(int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
if((size%sizeof(double))!=0)size+=(sizeof(double)-(size%sizeof(double)));
if (size<=(na_env149.store_left)){
rsoh*r=na_env149.store;
na_env149.store_left-=size;
if(na_env149.store_left>sizeof(rsoh)){
r->header.size=size;
na_env149.store=((rsoh*)(((char*)(na_env149.store))+size));
}
else {
r->header.size=size+na_env149.store_left;
na_env149.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T149)(r+1));
}
return((T149)new_na(&na_env149,size));
}


void gc_sweep176(fsoc*c){
gc176*o1,*o2,*flt,flh;
o1=((gc176*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store176;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free176;
gc_free176=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free176;
gc_free176=flh.header.next;
}
}
}


void gc_mark176(T176*o){
begin:
if(((gc176*)o)->header.flag==FSOH_UNMARKED){
((gc176*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_item/*4*/)gc_mark171((T171*)(o->_item/*4*/));
o=(void*)o->_next;
if((o!=NULL))goto begin;
}}


void gc_align_mark176(fsoc*c,gc176*p){
gc176*b=((gc176*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store176)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T176*o=(&(p->object));
begin:
((gc176*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_item/*4*/)gc_mark171((T171*)(o->_item/*4*/));
o=(void*)o->_next;
if((o!=NULL)&&(((gc176*)o)->header.flag==FSOH_UNMARKED))goto begin;
}
}
}
fsoc H176={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark176,
(void(*)(mch*))gc_sweep176},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc176))-1)};


T176*new176(void){
gc176*n;
fsoc*c;
if(store_left176>1){
store_left176--;
n=store176++;
}
else if(gc_free176!=NULL){
n=gc_free176;
gc_free176=n->header.next;
}
else if(store_left176==1){
store_left176=0;
store_chunk176->header.state_type=FSO_USED_CHUNK;
n=store176++;
}
else{
c=gc_fsoc_get1();
if(gc_free176!=NULL){
n=gc_free176;
gc_free176=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk176=c;
*store_chunk176=H176;
store176=((gc176*)(&(store_chunk176->first_object)));
store_left176=H176.count_minus_one;
n=store176++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M176;
return((T176*)n);
}


void gc_sweep131(fsoc*c){
gc131*o1,*o2,*flt,flh;
o1=((gc131*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store131;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free131;
gc_free131=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free131;
gc_free131=flh.header.next;
}
}
}


void gc_mark131(T131*o){
if(((gc131*)o)->header.flag==FSOH_UNMARKED){
((gc131*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_storage/*4*/)gc_mark154((o->_storage/*4*/));
}}


void gc_align_mark131(fsoc*c,gc131*p){
gc131*b=((gc131*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store131)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T131*o=(&(p->object));
((gc131*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_storage/*4*/)gc_mark154((o->_storage/*4*/));
}
}
}
fsoc H131={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark131,
(void(*)(mch*))gc_sweep131},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc131))-1)};


T131*new131(void){
gc131*n;
fsoc*c;
if(store_left131>1){
store_left131--;
n=store131++;
}
else if(gc_free131!=NULL){
n=gc_free131;
gc_free131=n->header.next;
}
else if(store_left131==1){
store_left131=0;
store_chunk131->header.state_type=FSO_USED_CHUNK;
n=store131++;
}
else{
c=gc_fsoc_get1();
if(gc_free131!=NULL){
n=gc_free131;
gc_free131=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk131=c;
*store_chunk131=H131;
store131=((gc131*)(&(store_chunk131->first_object)));
store_left131=H131.count_minus_one;
n=store131++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M131;
return((T131*)n);
}


void gc_sweep158(fsoc*c){
gc158*o1,*o2,*flt,flh;
o1=((gc158*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store158;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free158;
gc_free158=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free158;
gc_free158=flh.header.next;
}
}
}


void gc_mark158(T158*o){
((gc158*)o)->header.flag=FSOH_MARKED;
}


void gc_align_mark158(fsoc*c,gc158*p){
gc158*b=((gc158*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store158)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T158*o=(&(p->object));
((gc158*)o)->header.flag=FSOH_MARKED;
}
}
}
fsoc H158={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark158,
(void(*)(mch*))gc_sweep158},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc158))-1)};


T158*new158(void){
gc158*n;
fsoc*c;
if(store_left158>1){
store_left158--;
n=store158++;
}
else if(gc_free158!=NULL){
n=gc_free158;
gc_free158=n->header.next;
}
else if(store_left158==1){
store_left158=0;
store_chunk158->header.state_type=FSO_USED_CHUNK;
n=store158++;
}
else{
c=gc_fsoc_get1();
if(gc_free158!=NULL){
n=gc_free158;
gc_free158=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk158=c;
*store_chunk158=H158;
store158=((gc158*)(&(store_chunk158->first_object)));
store_left158=H158.count_minus_one;
n=store158++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M158;
return((T158*)n);
}


void gc_sweep143(fsoc*c){
gc143*o1,*o2,*flt,flh;
o1=((gc143*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store143;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free143;
gc_free143=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free143;
gc_free143=flh.header.next;
}
}
}


void gc_mark143(T143*o){
if(((gc143*)o)->header.flag==FSOH_UNMARKED){
((gc143*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_storage/*4*/)gc_mark145((o->_storage/*4*/));
}}


void gc_align_mark143(fsoc*c,gc143*p){
gc143*b=((gc143*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store143)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T143*o=(&(p->object));
((gc143*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_storage/*4*/)gc_mark145((o->_storage/*4*/));
}
}
}
fsoc H143={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark143,
(void(*)(mch*))gc_sweep143},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc143))-1)};


T143*new143(void){
gc143*n;
fsoc*c;
if(store_left143>1){
store_left143--;
n=store143++;
}
else if(gc_free143!=NULL){
n=gc_free143;
gc_free143=n->header.next;
}
else if(store_left143==1){
store_left143=0;
store_chunk143->header.state_type=FSO_USED_CHUNK;
n=store143++;
}
else{
c=gc_fsoc_get1();
if(gc_free143!=NULL){
n=gc_free143;
gc_free143=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk143=c;
*store_chunk143=H143;
store143=((gc143*)(&(store_chunk143->first_object)));
store_left143=H143.count_minus_one;
n=store143++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M143;
return((T143*)n);
}


void gc_mark217(T217 o){
rsoh*h=((rsoh*)o)-1;
if((h->header.magic_flag)==RSOH_UNMARKED){
h->header.magic_flag=RSOH_MARKED;
{T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)Xgc_mark216((T0*)(e));

}
}
}}


T217 new217(int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
if((size%sizeof(double))!=0)size+=(sizeof(double)-(size%sizeof(double)));
if (size<=(na_env217.store_left)){
rsoh*r=na_env217.store;
na_env217.store_left-=size;
if(na_env217.store_left>sizeof(rsoh)){
r->header.size=size;
na_env217.store=((rsoh*)(((char*)(na_env217.store))+size));
}
else {
r->header.size=size+na_env217.store_left;
na_env217.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T217)(r+1));
}
return((T217)new_na(&na_env217,size));
}


void gc_mark161(T161 o){
rsoh*h=((rsoh*)o)-1;
if((h->header.magic_flag)==RSOH_UNMARKED){
h->header.magic_flag=RSOH_MARKED;
{T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark160((T160*)(e));

}
}
}}


T161 new161(int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
if((size%sizeof(double))!=0)size+=(sizeof(double)-(size%sizeof(double)));
if (size<=(na_env161.store_left)){
rsoh*r=na_env161.store;
na_env161.store_left-=size;
if(na_env161.store_left>sizeof(rsoh)){
r->header.size=size;
na_env161.store=((rsoh*)(((char*)(na_env161.store))+size));
}
else {
r->header.size=size+na_env161.store_left;
na_env161.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T161)(r+1));
}
return((T161)new_na(&na_env161,size));
}


void gc_sweep135(fsoc*c){
gc135*o1,*o2,*flt,flh;
o1=((gc135*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store135;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free135;
gc_free135=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free135;
gc_free135=flh.header.next;
}
}
}


void gc_mark135(T135*o){
if(((gc135*)o)->header.flag==FSOH_UNMARKED){
((gc135*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_data/*16*/)gc_mark184((T184*)(o->_data/*16*/));
}}


void gc_align_mark135(fsoc*c,gc135*p){
gc135*b=((gc135*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store135)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T135*o=(&(p->object));
((gc135*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_data/*16*/)gc_mark184((T184*)(o->_data/*16*/));
}
}
}
fsoc H135={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark135,
(void(*)(mch*))gc_sweep135},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc135))-1)};


T135*new135(void){
gc135*n;
fsoc*c;
if(store_left135>1){
store_left135--;
n=store135++;
}
else if(gc_free135!=NULL){
n=gc_free135;
gc_free135=n->header.next;
}
else if(store_left135==1){
store_left135=0;
store_chunk135->header.state_type=FSO_USED_CHUNK;
n=store135++;
}
else{
c=gc_fsoc_get1();
if(gc_free135!=NULL){
n=gc_free135;
gc_free135=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk135=c;
*store_chunk135=H135;
store135=((gc135*)(&(store_chunk135->first_object)));
store_left135=H135.count_minus_one;
n=store135++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M135;
return((T135*)n);
}


void gc_mark139(T139 o){
rsoh*h=((rsoh*)o)-1;
if((h->header.magic_flag)==RSOH_UNMARKED){
h->header.magic_flag=RSOH_MARKED;
{T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark135((T135*)(e));

}
}
}}


T139 new139(int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
if((size%sizeof(double))!=0)size+=(sizeof(double)-(size%sizeof(double)));
if (size<=(na_env139.store_left)){
rsoh*r=na_env139.store;
na_env139.store_left-=size;
if(na_env139.store_left>sizeof(rsoh)){
r->header.size=size;
na_env139.store=((rsoh*)(((char*)(na_env139.store))+size));
}
else {
r->header.size=size+na_env139.store_left;
na_env139.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T139)(r+1));
}
return((T139)new_na(&na_env139,size));
}


void gc_sweep128(fsoc*c){
gc128*o1,*o2,*flt,flh;
o1=((gc128*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store128;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free128;
gc_free128=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free128;
gc_free128=flh.header.next;
}
}
}


void gc_mark128(T128*o){
((gc128*)o)->header.flag=FSOH_MARKED;
}


void gc_align_mark128(fsoc*c,gc128*p){
gc128*b=((gc128*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store128)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T128*o=(&(p->object));
((gc128*)o)->header.flag=FSOH_MARKED;
}
}
}
fsoc H128={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark128,
(void(*)(mch*))gc_sweep128},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc128))-1)};


T128*new128(void){
gc128*n;
fsoc*c;
if(store_left128>1){
store_left128--;
n=store128++;
}
else if(gc_free128!=NULL){
n=gc_free128;
gc_free128=n->header.next;
}
else if(store_left128==1){
store_left128=0;
store_chunk128->header.state_type=FSO_USED_CHUNK;
n=store128++;
}
else{
c=gc_fsoc_get1();
if(gc_free128!=NULL){
n=gc_free128;
gc_free128=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk128=c;
*store_chunk128=H128;
store128=((gc128*)(&(store_chunk128->first_object)));
store_left128=H128.count_minus_one;
n=store128++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M128;
return((T128*)n);
}


void gc_sweep113(fsoc*c){
gc113*o1,*o2,*flt,flh;
o1=((gc113*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store113;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free113;
gc_free113=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free113;
gc_free113=flh.header.next;
}
}
}


void gc_mark113(T113*o){
if(((gc113*)o)->header.flag==FSOH_UNMARKED){
((gc113*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_current_link/*8*/)gc_mark81((T81*)(o->_current_link/*8*/));
if(NULL!=o->_linked_list/*4*/)gc_mark80((T80*)(o->_linked_list/*4*/));
}}


void gc_align_mark113(fsoc*c,gc113*p){
gc113*b=((gc113*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store113)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T113*o=(&(p->object));
((gc113*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_current_link/*8*/)gc_mark81((T81*)(o->_current_link/*8*/));
if(NULL!=o->_linked_list/*4*/)gc_mark80((T80*)(o->_linked_list/*4*/));
}
}
}
fsoc H113={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark113,
(void(*)(mch*))gc_sweep113},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc113))-1)};


T113*new113(void){
gc113*n;
fsoc*c;
if(store_left113>1){
store_left113--;
n=store113++;
}
else if(gc_free113!=NULL){
n=gc_free113;
gc_free113=n->header.next;
}
else if(store_left113==1){
store_left113=0;
store_chunk113->header.state_type=FSO_USED_CHUNK;
n=store113++;
}
else{
c=gc_fsoc_get1();
if(gc_free113!=NULL){
n=gc_free113;
gc_free113=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk113=c;
*store_chunk113=H113;
store113=((gc113*)(&(store_chunk113->first_object)));
store_left113=H113.count_minus_one;
n=store113++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M113;
return((T113*)n);
}


void gc_sweep68(fsoc*c){
gc68*o1,*o2,*flt,flh;
o1=((gc68*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store68;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free68;
gc_free68=o1;
}
}
}
else{
int dead=1;
flh.header.next=NULL;
flt=&flh;
o2=o1+c->count_minus_one;
for(;o1<=o2;o2--){
if((o2->header.flag)==FSOH_MARKED){
o2->header.flag=FSOH_UNMARKED;
dead=0;}
else{
flt->header.next=o2;
flt=o2;
}
}
if (dead){
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
else if(flh.header.next!=NULL){
flt->header.next=gc_free68;
gc_free68=flh.header.next;
}
}
}


void gc_mark68(T68*o){
if(((gc68*)o)->header.flag==FSOH_UNMARKED){
((gc68*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_track_array/*44*/)gc_mark189((o->_track_array/*44*/));
if(NULL!=o->_image/*40*/)gc_mark50((T50*)(o->_image/*40*/));
if(NULL!=o->_setup_pattern/*20*/)gc_mark52((T52*)(o->_setup_pattern/*20*/));
if(NULL!=o->_pattern_list/*16*/)gc_mark60((T60*)(o->_pattern_list/*16*/));
if(NULL!=o->_pattern_table/*12*/)gc_mark62((T62*)(o->_pattern_table/*12*/));
if(NULL!=o->_in_connection/*8*/)gc_mark66((T66*)(o->_in_connection/*8*/));
if(NULL!=o->_name/*4*/)gc_mark7((T7*)(o->_name/*4*/));
}}


void gc_align_mark68(fsoc*c,gc68*p){
gc68*b=((gc68*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store68)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T68*o=(&(p->object));
((gc68*)o)->header.flag=FSOH_MARKED;
if(NULL!=o->_track_array/*44*/)gc_mark189((o->_track_array/*44*/));
if(NULL!=o->_image/*40*/)gc_mark50((T50*)(o->_image/*40*/));
if(NULL!=o->_setup_pattern/*20*/)gc_mark52((T52*)(o->_setup_pattern/*20*/));
if(NULL!=o->_pattern_list/*16*/)gc_mark60((T60*)(o->_pattern_list/*16*/));
if(NULL!=o->_pattern_table/*12*/)gc_mark62((T62*)(o->_pattern_table/*12*/));
if(NULL!=o->_in_connection/*8*/)gc_mark66((T66*)(o->_in_connection/*8*/));
if(NULL!=o->_name/*4*/)gc_mark7((T7*)(o->_name/*4*/));
}
}
}
fsoc H68={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark68,
(void(*)(mch*))gc_sweep68},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc68))-1)};


T68*new68(void){
gc68*n;
fsoc*c;
if(store_left68>1){
store_left68--;
n=store68++;
}
else if(gc_free68!=NULL){
n=gc_free68;
gc_free68=n->header.next;
}
else if(store_left68==1){
store_left68=0;
store_chunk68->header.state_type=FSO_USED_CHUNK;
n=store68++;
}
else{
c=gc_fsoc_get1();
if(gc_free68!=NULL){
n=gc_free68;
gc_free68=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk68=c;
*store_chunk68=H68;
store68=((gc68*)(&(store_chunk68->first_object)));
store_left68=H68.count_minus_one;
n=store68++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M68;
return((T68*)n);
}

