/*
ANSI C code generated by SmallEiffel The GNU Eiffel Compiler
Release -0.75 (July 16th 2001)
Copyright (C), 1994-2001 - LORIA - UHP - INRIA - FRANCE
Dominique COLNET and Suzanne COLLIN - SmallEiffel@loria.fr
http://SmallEiffel.loria.fr
*/
#ifdef __cplusplus
}
#endif
#include "main.h"
#ifdef __cplusplus
extern "C" {
#endif


void r51make(T51* C,T2 a1,T2 a2,T2 a3){
(/*SFN*/C->_pointer/*12*/)=ext_make_color(a1,a2,a3);
(/*SFN*/C->_to_integer/*4*/)=ext_convert_color(a1,a2,a3);
(/*SFN*/C->_to_gfx_integer/*8*/)=((((((a1)*(256))*(256))*(256))+(((a2)*(256))*(256)))+((a3)*(256)))+(255);
}


T0* r51twin(T51* C){
T0* R=NULL;
R=((void*)new51());
*((T51*)R)=*C;
return R;
}


void r146put_row_count(T146* C,T2 a1){
(/*SFN*/C->_row_count/*16*/)=a1;
/*[IF*/
if(((/*RF2*/(C)->_track_count/*20*/))>(0)){
{T180*n=new180();
r180make(n,0,((/*RF2*/(C)->_track_count/*20*/))-(1),0,((/*RF2*/(C)->_row_count/*16*/))-(1));
(/*SFN*/C->_data/*12*/)=((T0*)n);
}
}
/*FI]*/
{T182*n=new182();
r182make(n,0,((/*RF2*/(C)->_row_count/*16*/))-(1));
(/*SFN*/C->_global_data/*8*/)=((T0*)n);
}
}


void r146put_global_data(T146* C,T0* a1,T2 a2){
T0* _s=NULL;
{T7*n=new7();
r7copy(n,a1);
_s=((T0*)n);
}
/*[IRF3.6put*/{T182* C1=(T182*)((/*RF2*/(C)->_global_data/*8*/));
T0* b1=_s;
T2 b2=a2;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
}


void r146make(T146* C,T0* a1,T2 a2){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
(/*SFN*/C->_track_count/*20*/)=a2;
}


void r146put_data(T146* C,T0* a1,T2 a2,T2 a3){
T0* _s=NULL;
{T7*n=new7();
r7copy(n,a1);
_s=((T0*)n);
}
/*[IRF3.6put*/{T180* C1=(T180*)((/*RF2*/(C)->_data/*12*/));
T0* b1=_s;
T2 b2=a2;
T2 b3=a3;
((/*RF2*/(C1)->_storage/*20*/))[((((b2)-((/*RF2*/(C1)->_lower1/*16*/)))*(r180count2(C1)))+(b3))-((/*RF2*/(C1)->_lower2/*12*/))]=(b1);
}/*]*/
}


T0* r146twin(T146* C){
T0* R=NULL;
R=((void*)new146());
*((T146*)R)=*C;
return R;
}


T0* r72new_pattern_autoname(T72* C){
T0* R=NULL;
T2 _i=0;
while (!(!(r62has((T62*)((/*RF2*/(C)->_pattern_table/*12*/)),r2to_string(_i)))))
{
_i=(_i)+(1);
}
R=r72new_pattern(C,r2to_string(_i));
return R;
}


void r72move_to(T72* C,T2 a1,T2 a2){
(/*SFN*/C->_posx/*28*/)=a1;
(/*SFN*/C->_posy/*24*/)=a2;
}


T5 r72next_sample(T72* C){
T5 R=0;
T0* _it=NULL;
{T190*n=new190();
r190make(n,/*(IRF4.3input_list*/(/*RF2*/(C)->_in_connection/*8*/)/*)*/);
_it=((T0*)n);
}
while (!(/*SSFRF4*//*X190is_off*//*(IRF4.7is_off*/((/*RF2*/(((T91*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
R=(R)+(X37next_sample(X190item(_it)));
/*SSPRF3*//*X190next*/r91next(((T91*)_it));
}
return R;
}


T2 r72centerx(T72* C){
T2 R=0;
R=((/*RF2*/(C)->_posx/*28*/))+(((/*RF2*/(C)->_width/*32*/))/(2));
return R;
}


T2 r72centery(T72* C){
T2 R=0;
R=((/*RF2*/(C)->_posy/*24*/))+(((/*RF2*/(C)->_height/*36*/))/(2));
return R;
}


T0* r72new_pattern(T72* C,T0* a1){
T0* R=NULL;
{T52*n=new52();
r52make(n,a1,(T0*)C);
R=((T0*)n);
}
r62put((T62*)((/*RF2*/(C)->_pattern_table/*12*/)),R,a1);
r60add_last((T60*)((/*RF2*/(C)->_pattern_list/*16*/)),R);
return R;
}


T0* r72clone(T0* a1){
T0* R=NULL;
/*[IF*/
if((a1)!=((void*)(NULL))){
R=X10twin(a1);
}
/*FI]*/
return R;
}


T0* r72make_instance(T72* C,T0* a1){
T0* R=NULL;
R=r72clone((T0*)C);
r72put_name(((T72*)R),a1);
r72init_connection_lists(((T72*)R));
r72init_pattern_table(((T72*)R));
r72init_picture(((T72*)R));
/*[IRF3.1init*//*]*/
return R;
}


void r72init_connection_lists(T72* C){
{T66*n=new66();
r66make(n);
(/*SFN*/C->_in_connection/*8*/)=((T0*)n);
}
}


void r72init_pattern_table(T72* C){
{T62*n=new62();
/*[IRF3.4make*/r62with_capacity(n,193);
/*]*/
(/*SFN*/C->_pattern_table/*12*/)=((T0*)n);
}
{T60*n=new60();
r60make(n);
(/*SFN*/C->_pattern_list/*16*/)=((T0*)n);
}
{T52*n=new52();
r52make(n,((T0*)ms35_63105),(T0*)C);
(/*SFN*/C->_setup_pattern/*20*/)=((T0*)n);
}
}


T0* r72next_pattern(T72* C,T0* a1){
T0* R=NULL;
T2 _i=0;
_i=(r60fast_index_of((T60*)((/*RF2*/(C)->_pattern_list/*16*/)),a1))+(1);
/*[IF*/
if((_i)>((/*RF2*/((T60*)((/*RF2*/(C)->_pattern_list/*16*/)))->_upper/*4*/))){
_i=1;
}
/*FI]*/
R=r60_px_64((T60*)((/*RF2*/(C)->_pattern_list/*16*/)),_i);
return R;
}


T0* r72twin(T72* C){
T0* R=NULL;
R=((void*)new72());
*((T72*)R)=*C;
return R;
}


T0* r72white(void){
if(fBC18white==0){fBC18white=1;{
{T51*n=new51();
oBC18white=((T0*)n);
r51make(n,255,255,255);
}
}}
return oBC18white;
}
T0*oBC18red=NULL;
int fBC18red=0;


T0* r72red(void){
if(fBC18red==0){fBC18red=1;{
{T51*n=new51();
oBC18red=((T0*)n);
r51make(n,127,0,0);
}
}}
return oBC18red;
}


void r72put_name(T72* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*4*/)=((T0*)n);
}
}


void r72init_picture(T72* C){
(/*SFN*/C->_posx/*28*/)=0;
(/*SFN*/C->_posy/*24*/)=0;
(/*SFN*/C->_width/*32*/)=70;
(/*SFN*/C->_height/*36*/)=25;
{T50*n=new50();
/*[IRF3.1make*//*]*/
(/*SFN*/C->_image/*40*/)=((T0*)n);
}
r50new((T50*)((/*RF2*/(C)->_image/*40*/)),(/*RF2*/(C)->_width/*32*/),(/*RF2*/(C)->_height/*36*/));
/*[IRF3.6box*/{T50* C1=(T50*)((/*RF2*/(C)->_image/*40*/));
T2 b1=0;
T2 b2=0;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(1);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(1);
T0* b5=r72white();
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
/*[IRF3.6box*/{T50* C1=(T50*)((/*RF2*/(C)->_image/*40*/));
T2 b1=2;
T2 b2=2;
T2 b3=((/*RF2*/(C)->_width/*32*/))-(3);
T2 b4=((/*RF2*/(C)->_height/*36*/))-(3);
T0* b5=/*(IRF4.8bgcolor*/r72red()/*)*/;
ext_box((/*RF2*/(C1)->_ptr/*5*/),b1,b2,b3,b4,(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
/*[IRF3.5put_heading*/r50draw_text(((T50*)((/*RF2*/(C)->_image/*40*/))),4,6,(/*RF2*/(C)->_name/*4*/));
/*]*/
}


void r126put_dir_count(T126* C,T2 a1){
(/*SFN*/C->_dir_count/*24*/)=a1;
{T172*n=new172();
r172make(n,0,((/*RF2*/(C)->_dir_count/*24*/))-(1));
(/*SFN*/C->_dir/*16*/)=((T0*)n);
}
{T175*n=new175();
/*[IRF3.4make*/r175with_capacity(n,193);
/*]*/
(/*SFN*/C->_dir_table/*20*/)=((T0*)n);
}
}


void r126put_entry(T126* C,T0* a1,T2 a2){
/*[IRF3.6put*/{T172* C1=(T172*)((/*RF2*/(C)->_dir/*16*/));
T0* b1=a1;
T2 b2=a2;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
r175put((T175*)((/*RF2*/(C)->_dir_table/*20*/)),a1,(/*RF2*/(((T171*)a1))->_offset/*8*/));
}


void r126dump(T126* C){
T0* _c=NULL;
T0* _m=NULL;
T0* _e=NULL;
T2 _i=0;
_i=0;
while (!((_i)==((/*RF2*/(C)->_dir_count/*24*/))))
{
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r2to_string(_i)),((T0*)ms126_322)));
_e=r172_px_64((T172*)((/*RF2*/(C)->_dir/*16*/)),_i);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms126_545547512)));
r84put_integer((T84*)(oBC1io),(/*RF2*/(((T171*)_e))->_offset/*8*/));
r84put_string((T84*)(oBC1io),((T0*)ms126_21902512));
r84put_integer((T84*)(oBC1io),(/*RF2*/(((T171*)_e))->_size/*12*/));
r84put_string((T84*)(oBC1io),((T0*)ms126_10aa));
_i=(_i)+(1);
}
_i=0;
while (!((_i)==((/*RF2*/(C)->_machine_count/*40*/))))
{
_m=r150_px_64((T150*)((/*RF2*/(C)->_machine/*36*/)),_i);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms126_39610347,(/*RF2*/(((T134*)_m))->_name/*4*/))),((T0*)ms126_10a)));
r84put_string((T84*)(oBC1io),r7_px_43(ms126_2048762,r4to_string((/*RF2*/(((T134*)_m))->_x/*20*/))));
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms126_252,r4to_string((/*RF2*/(((T134*)_m))->_y/*16*/)))),((T0*)ms126_10)));
_i=(_i)+(1);
}
_i=0;
while (!((_i)==((/*RF2*/(C)->_connection_count/*48*/))))
{
_c=r167_px_64((T167*)((/*RF2*/(C)->_connection/*44*/)),_i);
r84put_string((T84*)(oBC1io),((T0*)ms126_569302452));
r84put_integer((T84*)(oBC1io),(/*RF2*/(((T133*)_c))->_src/*4*/));
r84put_string((T84*)(oBC1io),((T0*)ms126_7487));
r84put_integer((T84*)(oBC1io),(/*RF2*/(((T133*)_c))->_dst/*8*/));
/*[IRF3.4put_new_line*//*[IRF3.6put_character*/{T84* C1=(T84*)(oBC1io);
T3 b1=((T3)'\n');
putc(b1,((FILE*)(stdout)));
}/*]*/
/*]*/
_i=(_i)+(1);
}
}


void r126put_sequence_count(T126* C,T2 a1){
(/*SFN*/C->_sequence_count/*56*/)=a1;
{T155*n=new155();
r155make(n,0,((/*RF2*/(C)->_sequence_count/*56*/))-(1));
(/*SFN*/C->_sequence/*52*/)=((T0*)n);
}
}


void r126put_wave_count(T126* C,T2 a1){
(/*SFN*/C->_wave_count/*32*/)=a1;
{T140*n=new140();
r140make(n,0,((/*RF2*/(C)->_wave_count/*32*/))-(1));
(/*SFN*/C->_wavetable/*28*/)=((T0*)n);
}
}


void r126put_connection_count(T126* C,T2 a1){
(/*SFN*/C->_connection_count/*48*/)=a1;
{T167*n=new167();
r167make(n,0,(/*RF2*/(C)->_connection_count/*48*/));
(/*SFN*/C->_connection/*44*/)=((T0*)n);
}
}


T0* r126twin(T126* C){
T0* R=NULL;
R=((void*)new126());
*((T126*)R)=*C;
return R;
}


void r126put_connection(T126* C,T0* a1,T2 a2){
/*[IRF3.6put*/{T167* C1=(T167*)((/*RF2*/(C)->_connection/*44*/));
T0* b1=a1;
T2 b2=a2;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
r134increment_in_count((T134*)(r150item((T150*)((/*RF2*/(C)->_machine/*36*/)),(/*RF2*/(((T133*)a1))->_dst/*8*/))));
}


void r126put_machine_count(T126* C,T2 a1){
(/*SFN*/C->_machine_count/*40*/)=a1;
{T150*n=new150();
r150make(n,0,((/*RF2*/(C)->_machine_count/*40*/))-(1));
(/*SFN*/C->_machine/*36*/)=((T0*)n);
}
}


void r126put_song_info(T126* C,T2 a1,T2 a2,T2 a3){
(/*SFN*/C->_song_end/*12*/)=a1;
(/*SFN*/C->_loop_begin/*8*/)=a2;
(/*SFN*/C->_loop_end/*4*/)=a3;
}
T0*oBC130hex255table=NULL;
int fBC130hex255table=0;


T0* r163hex255table(void){
if(fBC130hex255table==0){fBC130hex255table=1;{
T0* _s=NULL;
T2 _j=0;
T2 _i=0;
{T182*n=new182();
oBC130hex255table=((T0*)n);
r182make(n,0,255);
}
_i=0;
while (!((_i)==(16)))
{
_j=0;
while (!((_j)==(16)))
{
{T7*n=new7();
r7make(n,2);
_s=((T0*)n);
}
r7add_last(((T7*)_s),r2hexadecimal_digit(_i));
r7add_last(((T7*)_s),r2hexadecimal_digit(_j));
/*[IRF3.6put*/{T182* C1=((T182*)oBC130hex255table);
T0* b1=_s;
T2 b2=((_i)*(16))+(_j);
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
_j=(_j)+(1);
}
_i=(_i)+(1);
}
}}
return oBC130hex255table;
}


T0* r163to_note(T3 a1){
T0* R=NULL;
T2 _i=0;
{T7*n=new7();
r7make(n,3);
R=((T0*)n);
}
_i=(T3code(a1))%(16);
r7copy(((T7*)R),r182_px_64((T182*)(oBC36scale_array),_i));
_i=(T3code(a1))/(16);
r7add_last(((T7*)R),r2digit(_i));
return R;
}


void r163convert_patterns(T0* a1,T0* a2){
T6 _exists_event=0;
T0* _s=NULL;
T0* _p=NULL;
T0* _bp=NULL;
T2 _t=0;
T2 _r=0;
T2 _i=0;
_i=0;
while (!((_i)==((/*RF2*/(((T134*)a2))->_pattern_count/*36*/))))
{
_bp=r147item((T147*)((/*RF2*/(((T134*)a2))->_pattern/*32*/)),_i);
_p=X35new_pattern(a1,(/*RF2*/(((T146*)_bp))->_name/*4*/));
_r=0;
while (!((_r)==((/*RF2*/(((T146*)_bp))->_row_count/*16*/))))
{
_t=0;
while (!((_t)==((/*RF2*/(((T146*)_bp))->_track_count/*20*/))))
{
_exists_event=0;
_s=r180item((T180*)((/*RF2*/(((T146*)_bp))->_data/*12*/)),_t,_r);
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(1)-(1)]/*)*/))!=(0)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r163to_note(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(1)-(1)]/*)*/),_r,((_t)*(6))+(1));
/*]*/
_exists_event=1;
}
/*FI]*/
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(2)-(1)]/*)*/))!=(0)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r7_px_43(ms163_83,r182item((T182*)(r163hex255table()),T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(2)-(1)]/*)*/))),_r,((_t)*(6))+(2));
/*]*/
_exists_event=1;
}
/*FI]*/
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(3)-(1)]/*)*/))!=(255)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r7_px_43(ms163_86,r182item((T182*)(r163hex255table()),T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(3)-(1)]/*)*/))),_r,((_t)*(6))+(3));
/*]*/
_exists_event=1;
}
/*FI]*/
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(4)-(1)]/*)*/))!=(0)){
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(4)-(1)]/*)*/))==(1)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r7_px_43(ms163_690,r182item((T182*)(r163hex255table()),T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(5)-(1)]/*)*/))),_r,((_t)*(6))+(4));
/*]*/
}
/*FI]*/
_exists_event=1;
}
/*FI]*/
/*[IF*/
if(_exists_event){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r7_px_43(ms163_84,r2to_string(_t)),_r,(_t)*(6));
/*]*/
}
/*FI]*/
_t=(_t)+(1);
}
_r=(_r)+(1);
}
_i=(_i)+(1);
}
}
T0*oBC36scale_array=NULL;


T0* r163twin(T163* C){
T0* R=NULL;
R=((void*)new163());
*((T163*)R)=*C;
return R;
}


T5 r65next_sample(T65* C){
T5 R=0;
R=(1.0)*(X35next_sample((/*RF2*/(C)->_src/*8*/)));
return R;
}


void r65make(T65* C,T0* a1,T0* a2){
(/*SFN*/C->_src/*8*/)=a1;
(/*SFN*/C->_dst/*4*/)=a2;
}


void r65put_xy(T65* C,T2 a1,T2 a2){
(/*SFN*/C->_x/*16*/)=a1;
(/*SFN*/C->_y/*12*/)=a2;
}


T0* r65twin(T65* C){
T0* R=NULL;
R=((void*)new65());
*((T65*)R)=*C;
return R;
}


T5 r205next_sample(T205* C){
T5 R=0;
(/*SFN*/C->_t/*32*/)=((/*RF2*/(C)->_t/*32*/))+(T4toT5((1.0)/(44100.0)));
R=((/*RF2*/(C)->_x0/*12*/))+(((/*RF2*/(C)->_diff/*20*/))*(pow((/*RF2*/(C)->_t/*32*/),T4toT5(0.1))));
/*[IF*/
if((r5sign(((/*RF2*/(C)->_x1/*4*/))-(R)))!=((/*RF2*/(C)->_original_sign/*28*/))){
R=(/*RF2*/(C)->_x1/*4*/);
}
/*FI]*/
return R;
}


void r205make(T205* C,T5 a1,T5 a2){
(/*SFN*/C->_x0/*12*/)=a1;
(/*SFN*/C->_x1/*4*/)=a2;
(/*SFN*/C->_diff/*20*/)=((/*RF2*/(C)->_x1/*4*/))-((/*RF2*/(C)->_x0/*12*/));
(/*SFN*/C->_original_sign/*28*/)=r5sign((/*RF2*/(C)->_diff/*20*/));
}


T0* r205twin(T205* C){
T0* R=NULL;
R=((void*)new205());
*((T205*)R)=*C;
return R;
}


T0* r166hex255table(void){
if(fBC130hex255table==0){fBC130hex255table=1;{
T0* _s=NULL;
T2 _j=0;
T2 _i=0;
{T182*n=new182();
oBC130hex255table=((T0*)n);
r182make(n,0,255);
}
_i=0;
while (!((_i)==(16)))
{
_j=0;
while (!((_j)==(16)))
{
{T7*n=new7();
r7make(n,2);
_s=((T0*)n);
}
r7add_last(((T7*)_s),r2hexadecimal_digit(_i));
r7add_last(((T7*)_s),r2hexadecimal_digit(_j));
/*[IRF3.6put*/{T182* C1=((T182*)oBC130hex255table);
T0* b1=_s;
T2 b2=((_i)*(16))+(_j);
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
_j=(_j)+(1);
}
_i=(_i)+(1);
}
}}
return oBC130hex255table;
}


T0* r166to_note(T3 a1){
T0* R=NULL;
T2 _i=0;
{T7*n=new7();
r7make(n,3);
R=((T0*)n);
}
_i=(T3code(a1))%(16);
r7copy(((T7*)R),r182_px_64((T182*)(oBC36scale_array),_i));
_i=(T3code(a1))/(16);
r7add_last(((T7*)R),r2digit(_i));
return R;
}


void r166convert_patterns(T0* a1,T0* a2){
T0* _s=NULL;
T0* _p=NULL;
T0* _bp=NULL;
T2 _t=0;
T2 _r=0;
T2 _i=0;
_i=0;
while (!((_i)==((/*RF2*/(((T134*)a2))->_pattern_count/*36*/))))
{
_bp=r147item((T147*)((/*RF2*/(((T134*)a2))->_pattern/*32*/)),_i);
_p=X35new_pattern(a1,(/*RF2*/(((T146*)_bp))->_name/*4*/));
_r=0;
while (!((_r)==((/*RF2*/(((T146*)_bp))->_row_count/*16*/))))
{
_t=0;
while (!((_t)==((/*RF2*/(((T146*)_bp))->_track_count/*20*/))))
{
_s=r180item((T180*)((/*RF2*/(((T146*)_bp))->_data/*12*/)),_t,_r);
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(6)-(1)]/*)*/))!=(0)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r166to_note(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(6)-(1)]/*)*/),_r,6);
/*]*/
}
/*FI]*/
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(7)-(1)]/*)*/))!=(255)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r7_px_43(ms166_86,r182item((T182*)(r166hex255table()),T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(7)-(1)]/*)*/))),_r,7);
/*]*/
}
/*FI]*/
/*[IF*/
if((T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(8)-(1)]/*)*/))!=(0)){
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/(((T52*)_p))->_commands/*8*/))),r7_px_43(ms166_76,r2to_string(T3code(/*(IRF4.6item*/((/*RF2*/(((T7*)_s))->_storage/*4*/))[(8)-(1)]/*)*/))),_r,8);
/*]*/
}
/*FI]*/
_t=(_t)+(1);
}
_r=(_r)+(1);
}
_i=(_i)+(1);
}
}


T0* r166twin(T166* C){
T0* R=NULL;
R=((void*)new166());
*((T166*)R)=*C;
return R;
}


T5 r204next_sample(T204* C){
T5 R=0;
/*[IRF3.3put_freq*/((((T202*)((T202*)((/*RF2*/(C)->_input/*4*/)))))->_freq/*12*/)=(X37next_sample((/*RF2*/(C)->_modulator/*8*/)));
/*]*/
R=r202next_sample((T202*)((/*RF2*/(C)->_input/*4*/)));
return R;
}


T0* r204twin(T204* C){
T0* R=NULL;
R=((void*)new204());
*((T204*)R)=*C;
return R;
}


void r136put_filename(T136* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_filename/*16*/)=((T0*)n);
}
}


void r136put_level_count(T136* C,T2 a1){
(/*SFN*/C->_level_count/*28*/)=a1;
{T137*n=new137();
r137make(n,0,((/*RF2*/(C)->_level_count/*28*/))-(1));
(/*SFN*/C->_level_table/*24*/)=((T0*)n);
}
}


T0* r136twin(T136* C){
T0* R=NULL;
R=((void*)new136());
*((T136*)R)=*C;
return R;
}


void r136put_name(T136* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*20*/)=((T0*)n);
}
}


void r170disconnect(T170* C){
fclose((/*RF2*/(C)->_input_stream/*9*/));
(/*SFN*/C->_path/*5*/)=NULL;
}


void r170read_character(T170* C){
/*[IF*/
if((/*RF2*/(C)->_push_back_flag/*4*/)){
(/*SFN*/C->_push_back_flag/*4*/)=0;
}
else{
(/*SFN*/C->_memory/*13*/)=getc((FILE*)((/*RF2*/(C)->_input_stream/*9*/)));
}
/*FI]*/
}


T6 r170end_of_input(T170* C){
T6 R=0;
/*[IF*/
if(!((/*RF2*/(C)->_push_back_flag/*4*/))){
R=((/*RF2*/(C)->_memory/*13*/))==((EOF));
}
/*FI]*/
return R;
}


void r170connect_to(T170* C,T0* a1){
T8 _p=NULL;
_p=r7to_external(((T7*)a1));
(/*SFN*/C->_input_stream/*9*/)=fopen((char*)_p,"r");
/*[IF*/
if((NULL!=(/*RF2*/(C)->_input_stream/*9*/))){
(/*SFN*/C->_push_back_flag/*4*/)=0;
(/*SFN*/C->_memory/*13*/)=T3code(((T3)'\40'));
(/*SFN*/C->_path/*5*/)=a1;
}
/*FI]*/
}


T0* r170twin(T170* C){
T0* R=NULL;
R=((void*)new170());
*((T170*)R)=*C;
return R;
}


void r127get_char(T127* C){
X87read_character((/*RF2*/(C)->_in/*4*/));
(/*SFN*/C->_offset/*12*/)=((/*RF2*/(C)->_offset/*12*/))+(1);
}


void r127parse_wavetable_section(T127* C){
T0* _bl=NULL;
T0* _e=NULL;
T2 _j=0;
T2 _i=0;
r127read_word(C);
r126put_wave_count((T126*)((/*RF2*/(C)->_buzz/*8*/)),(/*RF2*/(C)->_last_integer/*20*/));
_i=0;
while (!((_i)==((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_wave_count/*32*/))))
{
r127read_word(C);
r84put_string((T84*)(oBC1io),((T0*)ms127_2062822));
r84put_integer((T84*)(oBC1io),(/*RF2*/(C)->_last_integer/*20*/));
r84put_string((T84*)(oBC1io),((T0*)ms127_10aaaaaaa));
/*[IF*/
if(((/*RF2*/(C)->_last_integer/*20*/))!=(_i)){
r84put_string((T84*)(oBC1io),((T0*)ms127_2143930291));
exit(1);
}
/*FI]*/
{T136*n=new136();
/*[IRF3.3make*/((((T136*)(n)))->_index/*4*/)=((/*RF2*/(C)->_last_integer/*20*/));
/*]*/
_e=((T0*)n);
}
r127read_asciiz(C);
r136put_filename(((T136*)_e),(/*RF2*/(C)->_last_string/*16*/));
r127read_asciiz(C);
r136put_name(((T136*)_e),(/*RF2*/(C)->_last_string/*16*/));
r127read_float(C);
/*[IRF3.3put_volume*/((((T136*)(((T136*)_e))))->_volume/*8*/)=(((T5)((/*RF2*/(C)->_last_real/*24*/))));
/*]*/
r127read_byte(C);
r127read_byte(C);
r136put_level_count(((T136*)_e),(/*RF2*/(C)->_last_integer/*20*/));
_j=0;
while (!((_j)==((/*RF2*/(((T136*)_e))->_level_count/*28*/))))
{
r127read_dword(C);
{T135*n=new135();
/*[IRF3.3make*/((((T135*)(n)))->_length/*4*/)=((/*RF2*/(C)->_last_integer/*20*/));
/*]*/
_bl=((T0*)n);
}
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_443097,r2to_string((/*RF2*/(C)->_last_integer/*20*/)))),((T0*)ms127_10aaaaaa)));
r127read_dword(C);
r127read_dword(C);
r127read_dword(C);
r127get_char(C);
/*[IRF3.3put_root_freq*/((((T135*)(((T135*)_bl))))->_root_freq/*8*/)=(r127buzz_note_to_freq(r127last_char(C)));
/*]*/
/*[IRF3.6put*/{T137* C1=(T137*)((/*RF2*/(((T136*)_e))->_level_table/*24*/));
T0* b1=_bl;
T2 b2=_j;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
_j=(_j)+(1);
}
/*[IRF3.5put_wavetable_entry*//*[IRF3.6put*/{T140* C1=((T140*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_wavetable/*28*/)));
T0* b1=_e;
T2 b2=(/*RF2*/(((T136*)_e))->_index/*4*/);
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
/*]*/
_i=(_i)+(1);
}
}


void r127read_asciiz(T127* C){
/*[IRF3.3clear*/((((T7*)((T7*)((/*RF2*/(C)->_last_string/*16*/)))))->_count/*8*/)=(0);
/*]*/
r127get_char(C);
while (!((T3code(r127last_char(C)))==(0)))
{
r7add_last((T7*)((/*RF2*/(C)->_last_string/*16*/)),r127last_char(C));
r127get_char(C);
}
}


void r127parse_machine_section(T127* C){
T2 _i=0;
r84put_string((T84*)(oBC1io),((T0*)ms127_890392572));
r127read_word(C);
r126put_machine_count((T126*)((/*RF2*/(C)->_buzz/*8*/)),(/*RF2*/(C)->_last_integer/*20*/));
_i=0;
while (!((_i)==((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_machine_count/*40*/))))
{
/*[IRF3.5put_machine*//*[IRF3.6put*/{T150* C1=((T150*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_machine/*36*/)));
T0* b1=r127parse_machine(C);
T2 b2=_i;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
/*]*/
_i=(_i)+(1);
}
}


void r127parse_wavedata_section(T127* C){
T2 _total=0;
T0* _bl=NULL;
T0* _e=NULL;
T2 _n=0;
T2 _k=0;
T2 _j=0;
T2 _i=0;
r127read_word(C);
_n=(/*RF2*/(C)->_last_integer/*20*/);
/*[IF*/
if((_n)>((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_wave_count/*32*/))){
r84put_string((T84*)(oBC1io),((T0*)ms127_430299720));
exit(1);
}
/*FI]*/
_i=0;
while (!((_i)==(_n)))
{
r127read_word(C);
_e=r140item((T140*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_wavetable/*28*/)),(/*RF2*/(C)->_last_integer/*20*/));
r127read_byte(C);
/*[IF*/
if(((/*RF2*/(C)->_last_integer/*20*/))!=(0)){
exit(1);
r84put_string((T84*)(oBC1io),((T0*)ms127_525854605));
}
/*FI]*/
r127read_dword(C);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_2247022,r2to_string((/*RF2*/(C)->_last_integer/*20*/)))),((T0*)ms127_10aaaaaaaa)));
_total=(/*RF2*/(C)->_last_integer/*20*/);
_j=0;
while (!((_j)==((/*RF2*/(((T136*)_e))->_level_count/*28*/))))
{
_bl=r137_px_64((T137*)((/*RF2*/(((T136*)_e))->_level_table/*24*/)),_j);
r135init_data(((T135*)_bl),((/*RF2*/(((T135*)_bl))->_length/*4*/))*(2));
_k=0;
while (!((_k)==((/*RF2*/(((T135*)_bl))->_length/*4*/))))
{
r127get_char(C);
/*[IRF3.6put*/{T184* C1=(T184*)((/*RF2*/(((T135*)_bl))->_data/*16*/));
T3 b1=r127last_char(C);
T2 b2=(2)*(_k);
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
r127get_char(C);
/*[IRF3.6put*/{T184* C1=(T184*)((/*RF2*/(((T135*)_bl))->_data/*16*/));
T3 b1=r127last_char(C);
T2 b2=((2)*(_k))+(1);
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
_k=(_k)+(1);
}
_j=(_j)+(1);
}
_i=(_i)+(1);
}
}


T0* r127load(T127* C,T0* a1){
T0* R=NULL;
T0* _sfr=NULL;
{T170*n=new170();
r170connect_to(n,a1);
_sfr=((T0*)n);
}
/*[IF*/
if(/*(IRF4.7is_connected*/((/*RF2*/(((T170*)_sfr))->_path/*5*/))!=(NULL)/*)*/){
(/*SFN*/C->_in/*4*/)=_sfr;
{T126*n=new126();
/*[IRF3.1make*//*]*/
(/*SFN*/C->_buzz/*8*/)=((T0*)n);
}
r127parse(C);
r126dump((T126*)((/*RF2*/(C)->_buzz/*8*/)));
r170disconnect(((T170*)_sfr));
R=(/*RF2*/(C)->_buzz/*8*/);
}
/*FI]*/
return R;
}


void r127parse_pattern_section(T127* C){
T0* _p=NULL;
T0* _m=NULL;
T2 _track_count=0;
T2 _j=0;
T2 _i=0;
_i=0;
while (!((_i)==((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_machine_count/*40*/))))
{
_m=r150item((T150*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_machine/*36*/)),_i);
r127read_word(C);
r134put_pattern_count(((T134*)_m),(/*RF2*/(C)->_last_integer/*20*/));
r127read_word(C);
_track_count=(/*RF2*/(C)->_last_integer/*20*/);
_j=0;
while (!((_j)==((/*RF2*/(((T134*)_m))->_pattern_count/*36*/))))
{
r127read_asciiz(C);
{T146*n=new146();
r146make(n,(/*RF2*/(C)->_last_string/*16*/),_track_count);
_p=((T0*)n);
}
r127read_word(C);
r146put_row_count(((T146*)_p),(/*RF2*/(C)->_last_integer/*20*/));
r127parse_pattern_data(C,_p,_m);
/*[IRF3.5put_pattern*//*[IRF3.6put*/{T147* C1=((T147*)((/*RF2*/(((T134*)_m))->_pattern/*32*/)));
T0* b1=_p;
T2 b2=_j;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
/*]*/
_j=(_j)+(1);
}
_i=(_i)+(1);
}
}


void r127read_float(T127* C){
r127read_dword(C);
(/*SFN*/C->_last_real/*24*/)=ext_int_to_float((/*RF2*/(C)->_last_integer/*20*/));
}


void r127read_dword(T127* C){
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=T3code(r127last_char(C));
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=((/*RF2*/(C)->_last_integer/*20*/))+((T3code(r127last_char(C)))*(256));
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=((/*RF2*/(C)->_last_integer/*20*/))+(((T3code(r127last_char(C)))*(256))*(256));
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=((/*RF2*/(C)->_last_integer/*20*/))+((((T3code(r127last_char(C)))*(256))*(256))*(256));
}


void r127read_byte(T127* C){
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=T3code(r127last_char(C));
}


T5 r127buzz_note_to_freq(T3 a1){
T5 R=0;
T2 _i=0;
_i=((T3code(a1))%(16))-(1);
_i=(_i)+(((T3code(a1))/(16))*(12));
R=X117item(r127note_freq_table(),_i);
return R;
}


void r127make(T127* C){
{T7*n=new7();
r7make(n,16);
(/*SFN*/C->_last_string/*16*/)=((T0*)n);
}
}


void r127parse_header(T127* C){
T0* _e=NULL;
T2 _size=0;
T2 _off=0;
T2 _i=0;
r127read_string(C,4);
/*[IF*/
if(r7is_equal((T7*)((/*RF2*/(C)->_last_string/*16*/)),((T0*)ms127_11907))){
r127read_dword(C);
r126put_dir_count((T126*)((/*RF2*/(C)->_buzz/*8*/)),(/*RF2*/(C)->_last_integer/*20*/));
_i=0;
while (!((_i)==((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_dir_count/*24*/))))
{
r127read_string(C,4);
r127read_dword(C);
_off=(/*RF2*/(C)->_last_integer/*20*/);
r127read_dword(C);
_size=(/*RF2*/(C)->_last_integer/*20*/);
{T171*n=new171();
r171make(n,(/*RF2*/(C)->_last_string/*16*/),_off,_size);
_e=((T0*)n);
}
r126put_entry((T126*)((/*RF2*/(C)->_buzz/*8*/)),_e,_i);
_i=(_i)+(1);
}
while (!((_i)==(31)))
{
r127read_string(C,12);
_i=(_i)+(1);
}
}
/*FI]*/
}


void r127parse_pattern_data(T127* C,T0* a1,T0* a2){
T2 _tlen=0;
T2 _glen=0;
T2 _in_count=0;
T2 _j=0;
T2 _i=0;
_tlen=(/*RF2*/(((T134*)a2))->_track_parm_size/*44*/);
_glen=(/*RF2*/(((T134*)a2))->_global_parm_size/*40*/);
_in_count=(/*RF2*/(((T134*)a2))->_in_count/*48*/);
_j=0;
while (!((_j)==(_in_count)))
{
r127read_word(C);
_i=0;
while (!((_i)==((/*RF2*/(((T146*)a1))->_row_count/*16*/))))
{
r127read_word(C);
r127read_word(C);
_i=(_i)+(1);
}
_j=(_j)+(1);
}
_i=0;
while (!((_i)==((/*RF2*/(((T146*)a1))->_row_count/*16*/))))
{
r127read_string(C,_glen);
r146put_global_data(((T146*)a1),(/*RF2*/(C)->_last_string/*16*/),_i);
_i=(_i)+(1);
}
_j=0;
while (!((_j)==((/*RF2*/(((T146*)a1))->_track_count/*20*/))))
{
_i=0;
while (!((_i)==((/*RF2*/(((T146*)a1))->_row_count/*16*/))))
{
r127read_string(C,_tlen);
r146put_data(((T146*)a1),(/*RF2*/(C)->_last_string/*16*/),_j,_i);
_i=(_i)+(1);
}
_j=(_j)+(1);
}
}


void r127read_bytes(T127* C,T2 a1){
T2 _pwr256=0;
T2 _i=0;
_pwr256=1;
(/*SFN*/C->_last_integer/*20*/)=0;
_i=0;
while (!((_i)==(a1)))
{
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=((/*RF2*/(C)->_last_integer/*20*/))+((T3code(r127last_char(C)))*(_pwr256));
_pwr256=(_pwr256)*(256);
_i=(_i)+(1);
}
}


void r127read_word(T127* C){
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=T3code(r127last_char(C));
r127get_char(C);
(/*SFN*/C->_last_integer/*20*/)=((/*RF2*/(C)->_last_integer/*20*/))+((T3code(r127last_char(C)))*(256));
}


void r127read_string(T127* C,T2 a1){
T2 _i=0;
/*[IRF3.3clear*/((((T7*)((T7*)((/*RF2*/(C)->_last_string/*16*/)))))->_count/*8*/)=(0);
/*]*/
_i=0;
while (!((_i)==(a1)))
{
r127get_char(C);
r7add_last((T7*)((/*RF2*/(C)->_last_string/*16*/)),r127last_char(C));
_i=(_i)+(1);
}
}


T0* r127parse_machine(T127* C){
T0* R=NULL;
T4 _y=0;
T4 _x=0;
T2 _i=0;
r127read_asciiz(C);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)((/*RF2*/(C)->_last_string/*16*/)),((T0*)ms127_10aaaaa)));
{T134*n=new134();
r134make(n,(/*RF2*/(C)->_last_string/*16*/));
R=((T0*)n);
}
r127read_byte(C);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r2to_string((/*RF2*/(C)->_last_integer/*20*/))),((T0*)ms127_10aaaa)));
r134put_type(((T134*)R),(/*RF2*/(C)->_last_integer/*20*/));
/*[IF*/
if(((/*RF2*/(C)->_last_integer/*20*/))>(0)){
r127read_asciiz(C);
r134put_dll(((T134*)R),(/*RF2*/(C)->_last_string/*16*/));
}
/*FI]*/
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_271144,(/*RF2*/(C)->_last_string/*16*/))),((T0*)ms127_180)));
r127read_float(C);
_x=(/*RF2*/(C)->_last_real/*24*/);
r127read_float(C);
_y=(/*RF2*/(C)->_last_real/*24*/);
r134put_xy(((T134*)R),_x,_y);
r127read_dword(C);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_266568097,r2to_string((/*RF2*/(C)->_last_integer/*20*/)))),((T0*)ms127_10aaa)));
r127read_string(C,(/*RF2*/(C)->_last_integer/*20*/));
r127read_word(C);
/*[IRF3.3put_attr_count*/((((T134*)(((T134*)R))))->_attr_count/*24*/)=((/*RF2*/(C)->_last_integer/*20*/));
/*]*/
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_1849750926,r2to_string((/*RF2*/(C)->_last_integer/*20*/)))),((T0*)ms127_10aa)));
_i=0;
while (!((_i)==((/*RF2*/(((T134*)R))->_attr_count/*24*/))))
{
r127read_asciiz(C);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_393297,(/*RF2*/(C)->_last_string/*16*/))),((T0*)ms127_1137)));
r127read_dword(C);
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r2to_string((/*RF2*/(C)->_last_integer/*20*/))),((T0*)ms127_10a)));
_i=(_i)+(1);
}
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_2052472,r2to_string((/*RF2*/(((T134*)R))->_global_parm_size/*40*/)))),((T0*)ms127_10)));
r127read_string(C,(/*RF2*/(((T134*)R))->_global_parm_size/*40*/));
r127read_word(C);
/*[IRF3.3put_sequence_count*/((((T134*)(((T134*)R))))->_sequence_count/*28*/)=((/*RF2*/(C)->_last_integer/*20*/));
/*]*/
_i=0;
while (!((_i)==((/*RF2*/(((T134*)R))->_sequence_count/*28*/))))
{
r127read_string(C,(/*RF2*/(((T134*)R))->_track_parm_size/*44*/));
_i=(_i)+(1);
}
return R;
}


void r127parse_sequence_section(T127* C){
T2 _bpe=0;
T2 _bppos=0;
T0* _seq=NULL;
T2 _k=0;
T2 _j=0;
T2 _i=0;
r127read_dword(C);
_i=(/*RF2*/(C)->_last_integer/*20*/);
r127read_dword(C);
_j=(/*RF2*/(C)->_last_integer/*20*/);
r127read_dword(C);
_k=(/*RF2*/(C)->_last_integer/*20*/);
r126put_song_info((T126*)((/*RF2*/(C)->_buzz/*8*/)),_i,_j,_k);
r127read_word(C);
r126put_sequence_count((T126*)((/*RF2*/(C)->_buzz/*8*/)),(/*RF2*/(C)->_last_integer/*20*/));
_i=0;
while (!((_i)==((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_sequence_count/*56*/))))
{
r127read_word(C);
{T132*n=new132();
/*[IRF3.3make*/((((T132*)(n)))->_machine_index/*4*/)=((/*RF2*/(C)->_last_integer/*20*/));
/*]*/
_seq=((T0*)n);
}
r127read_dword(C);
r132put_event_count(((T132*)_seq),(/*RF2*/(C)->_last_integer/*20*/));
r127read_byte(C);
_bppos=(/*RF2*/(C)->_last_integer/*20*/);
r127read_byte(C);
_bpe=(/*RF2*/(C)->_last_integer/*20*/);
_j=0;
while (!((_j)==((/*RF2*/(((T132*)_seq))->_event_count/*16*/))))
{
r127read_bytes(C,_bppos);
/*[IRF3.5put_eventpos*//*[IRF3.6put*/{T143* C1=((T143*)((/*RF2*/(((T132*)_seq))->_eventpos/*8*/)));
T2 b1=(/*RF2*/(C)->_last_integer/*20*/);
T2 b2=_j;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
/*]*/
r127read_bytes(C,_bpe);
/*[IRF3.5put_event*//*[IRF3.6put*/{T143* C1=((T143*)((/*RF2*/(((T132*)_seq))->_event/*12*/)));
T2 b1=(/*RF2*/(C)->_last_integer/*20*/);
T2 b2=_j;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
/*]*/
_j=(_j)+(1);
}
/*[IRF3.5put_sequence*//*[IRF3.6put*/{T155* C1=((T155*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_sequence/*52*/)));
T0* b1=_seq;
T2 b2=_i;
((/*RF2*/(C1)->_storage/*4*/))[(b2)-((/*RF2*/(C1)->_lower/*16*/))]=(b1);
}/*]*/
/*]*/
_i=(_i)+(1);
}
}


T3 r127last_char(T127* C){
T3 R=0;
R=X87last_character((/*RF2*/(C)->_in/*4*/));
return R;
}


void r127parse(T127* C){
T0* _e=NULL;
(/*SFN*/C->_offset/*12*/)=0;
r127parse_header(C);
while (!(!(/*(IRF4.6entry_has_offset*/r175has(((T175*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_dir_table/*20*/))),(/*RF2*/(C)->_offset/*12*/))/*)*/)))
{
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms127_248893247,r2to_string((/*RF2*/(C)->_offset/*12*/)))),((T0*)ms127_10aaaaaaaaa)));
_e=/*(IRF4.6entry_at_offset*/r175at(((T175*)((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_dir_table/*20*/))),(/*RF2*/(C)->_offset/*12*/))/*)*/;
/*[IF*/
if(r7is_equal((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms127_11657))){
r127parse_machine_section(C);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms127_10818))){
r127parse_connection_section(C);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms127_12590))){
r127parse_sequence_section(C);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms127_12129))){
r127parse_pattern_section(C);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms127_13014))){
r127parse_wavetable_section(C);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T171*)_e))->_name/*4*/)),((T0*)ms127_12999))){
r127parse_wavedata_section(C);
}
else{
r127read_string(C,(/*RF2*/(((T171*)_e))->_size/*12*/));
}
/*FI]*/
}
r127get_char(C);
/*[IF*/
if(!(X87end_of_input((/*RF2*/(C)->_in/*4*/)))){
r84put_string((T84*)(oBC1io),((T0*)ms127_647764604));
}
/*FI]*/
}


T0* r127twin(T127* C){
T0* R=NULL;
R=((void*)new127());
*((T127*)R)=*C;
return R;
}


T0* r127note_freq_table(void){
if(fBC36note_freq_table==0){fBC36note_freq_table=1;{
T2 _i=0;
{T117*n=new117();
oBC36note_freq_table=((T0*)n);
r117make(n,0,127);
}
_i=0;
while (!((_i)>(127)))
{
X117put(oBC36note_freq_table,(T4toT5(220.0))*(r4pow(2.0,((T5)((_i)-(57)))/(12))),_i);
_i=(_i)+(1);
}
}}
return oBC36note_freq_table;
}


void r127parse_connection_section(T127* C){
T0* _bc=NULL;
T2 _pan=0;
T2 _amp=0;
T2 _dst=0;
T2 _src=0;
T2 _i=0;
r127read_word(C);
r126put_connection_count((T126*)((/*RF2*/(C)->_buzz/*8*/)),(/*RF2*/(C)->_last_integer/*20*/));
_i=0;
while (!((_i)==((/*RF2*/((T126*)((/*RF2*/(C)->_buzz/*8*/)))->_connection_count/*48*/))))
{
r127read_word(C);
_src=(/*RF2*/(C)->_last_integer/*20*/);
r127read_word(C);
_dst=(/*RF2*/(C)->_last_integer/*20*/);
r127read_word(C);
_amp=(/*RF2*/(C)->_last_integer/*20*/);
r127read_word(C);
_pan=(/*RF2*/(C)->_last_integer/*20*/);
{T133*n=new133();
r133make(n,_src,_dst,_amp,_pan);
_bc=((T0*)n);
}
r126put_connection((T126*)((/*RF2*/(C)->_buzz/*8*/)),_bc,_i);
_i=(_i)+(1);
}
}


void r82put_machine_pos(T82* C,T2 a1,T2 a2){
r82put_line(C,r7_px_43(ms82_632,r2to_string(a1)));
r82put_line(C,r7_px_43(ms82_637,r2to_string(a2)));
}


void r82end_machine(T82* C){
(/*SFN*/C->_tabs/*8*/)=((/*RF2*/(C)->_tabs/*8*/))-(1);
r82put_line(C,((T0*)ms82_3175a));
}


void r82start_machine(T82* C,T0* a1){
r82put_line(C,((T0*)ms82_0a));
r82put_line(C,((T0*)ms82_600314783));
(/*SFN*/C->_tabs/*8*/)=((/*RF2*/(C)->_tabs/*8*/))+(1);
r82put_line(C,r7_px_43((T7*)(r7_px_43(ms82_420719,a1)),((T0*)ms82_34aa)));
}


void r82start_zorder(T82* C){
r82put_line(C,((T0*)ms82_0));
r82put_line(C,((T0*)ms82_1597872847));
(/*SFN*/C->_tabs/*8*/)=((/*RF2*/(C)->_tabs/*8*/))+(1);
}


void r82put_line(T82* C,T0* a1){
T2 _i=0;
_i=(/*RF2*/(C)->_tabs/*8*/);
while (!((_i)==(0)))
{
r84put_string((T84*)((/*RF2*/(C)->_os/*4*/)),((T0*)ms82_4992));
_i=(_i)-(1);
}
r84put_string((T84*)((/*RF2*/(C)->_os/*4*/)),a1);
/*[IRF3.4put_new_line*//*[IRF3.6put_character*/{T84* C1=(T84*)((/*RF2*/(C)->_os/*4*/));
T3 b1=((T3)'\n');
putc(b1,((FILE*)(stdout)));
}/*]*/
/*]*/
}


T0* r82twin(T82* C){
T0* R=NULL;
R=((void*)new82());
*((T82*)R)=*C;
return R;
}


void r82end_zorder(T82* C){
(/*SFN*/C->_tabs/*8*/)=((/*RF2*/(C)->_tabs/*8*/))-(1);
r82put_line(C,((T0*)ms82_3175));
}


T5 r203next_sample(T203* C){
T5 R=0;
R=(X37next_sample((/*RF2*/(C)->_input1/*4*/)))*(X37next_sample((/*RF2*/(C)->_input2/*8*/)));
return R;
}


void r203make(T203* C,T0* a1,T0* a2){
/*[IRF3.3put_input1*/((((T203*)(C)))->_input1/*4*/)=(a1);
/*]*/
/*[IRF3.3put_input2*/((((T203*)(C)))->_input2/*8*/)=(a2);
/*]*/
}


T0* r203twin(T203* C){
T0* R=NULL;
R=((void*)new203());
*((T203*)R)=*C;
return R;
}


void r94handle_event(T94* C,T0* a1){
/*[IRF3.3put_x*/((((T23*)(((T23*)a1))))->_x/*8*/)=(((/*RF2*/(((T23*)a1))->_x/*8*/))-((/*RF2*/(C)->_offsetx/*4*/)));
/*]*/
/*[IRF3.3put_y*/((((T23*)(((T23*)a1))))->_y/*4*/)=(((/*RF2*/(((T23*)a1))->_y/*4*/))-((/*RF2*/(C)->_offsety/*8*/)));
/*]*/
r94process_event(C,a1);
}


void r94process_buttonup(T94* C,T0* a1){
/*[INSPECT*/
{int z1=(/*RF2*/(((T23*)a1))->_i1/*20*/);
switch(z1){
case 1:
/*[IF*/
if((/*RF2*/(C)->_moving_flag/*21*/)){
r94place_selection(C,(/*RF2*/(((T23*)a1))->_x/*8*/),(/*RF2*/(((T23*)a1))->_y/*4*/));
}
 else if((/*RF2*/(C)->_connecting_flag/*20*/)){
r94connect_selection(C,(/*RF2*/(((T23*)a1))->_x/*8*/),(/*RF2*/(((T23*)a1))->_y/*4*/));
}
/*FI]*/
break;
}
}/*INSPECT]*/
}


void r94select_machine_for_move(T94* C,T2 a1,T2 a2){
T2 _i=0;
_i=r94select_machine(a1,a2);
/*[IF*/
if((_i)>=(1)){
(/*SFN*/C->_selection/*22*/)=r41_px_64((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/),_i);
r41remove((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/),_i);
r41add_last((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/),(/*RF2*/(C)->_selection/*22*/));
(/*SFN*/C->_moving_flag/*21*/)=1;
(/*SFN*/C->_movestartx/*26*/)=(a1)-(/*SSWARF2*//*X35posx*/(/*RF2*/((T68*)((/*RF2*/(C)->_selection/*22*/)))->_posx/*28*/));
(/*SFN*/C->_movestarty/*30*/)=(a2)-(/*SSWARF2*//*X35posy*/(/*RF2*/((T68*)((/*RF2*/(C)->_selection/*22*/)))->_posy/*24*/));
}
else{
(/*SFN*/C->_selection/*22*/)=NULL;
}
/*FI]*/
}


void r94process_key(T94* C,T2 a1){
T0* _m=NULL;
/*[INSPECT*/
{int z1=a1;
switch(z1){
case 98:
_m=r33new_machine_autoname((T33*)(r94song()),((T0*)ms94_1325625));
r33add_track((T33*)(r94song()),_m);
ext_get_mouse_state();
r94clipped_move(C,_m,(r94last_mouse_x(C))-((/*SSWARF2*//*X35width*/(/*RF2*/(((T68*)_m))->_width/*32*/))/(2)),(r94last_mouse_y(C))-((/*SSWARF2*//*X35height*/(/*RF2*/(((T68*)_m))->_height/*36*/))/(2)));
break;
case 110:
_m=r33new_machine_autoname((T33*)(r94song()),((T0*)ms94_265794));
r33add_track((T33*)(r94song()),_m);
ext_get_mouse_state();
r94clipped_move(C,_m,(r94last_mouse_x(C))-((/*SSWARF2*//*X35width*/(/*RF2*/(((T68*)_m))->_width/*32*/))/(2)),(r94last_mouse_y(C))-((/*SSWARF2*//*X35height*/(/*RF2*/(((T68*)_m))->_height/*36*/))/(2)));
break;
case 111:
_m=r33new_machine_autoname((T33*)(r94song()),((T0*)ms94_2425));
r33add_track((T33*)(r94song()),_m);
ext_get_mouse_state();
r94clipped_move(C,_m,(r94last_mouse_x(C))-((/*SSWARF2*//*X35width*/(/*RF2*/(((T68*)_m))->_width/*32*/))/(2)),(r94last_mouse_y(C))-((/*SSWARF2*//*X35height*/(/*RF2*/(((T68*)_m))->_height/*36*/))/(2)));
break;
}
}/*INSPECT]*/
}


void r94select_machine_for_connect(T94* C,T2 a1,T2 a2){
T2 _i=0;
_i=r94select_machine(a1,a2);
/*[IF*/
if((_i)>=(1)){
(/*SFN*/C->_selection/*22*/)=r41_px_64((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/),_i);
(/*SFN*/C->_connecting_flag/*20*/)=1;
}
/*FI]*/
}


T2 r94last_mouse_y(T94* C){
T2 R=0;
R=(get_last_mouse_y())-((/*RF2*/(C)->_offsety/*8*/));
return R;
}


T2 r94last_mouse_x(T94* C){
T2 R=0;
R=(get_last_mouse_x())-((/*RF2*/(C)->_offsetx/*4*/));
return R;
}


T0* r94song(void){
if(fBC20song==0){fBC20song=1;{
{T33*n=new33();
oBC20song=((T0*)n);
r33make(n);
}
}}
return oBC20song;
}


void r94attempt_connect(T0* a1,T0* a2){
/*[IF*/
if((X35is_sink(a2))&&(X35is_source(a1))){
r33connect((T33*)(r94song()),a1,a2);
}
/*FI]*/
}


T2 r94select_machine(T2 a1,T2 a2){
T2 R=0;
T0* _m=NULL;
T2 _i=0;
_i=(/*RF2*/((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/))->_upper/*4*/);
while (!((_i)<(1)))
{
_m=r41item((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/),_i);
/*[IF*/
if(((((a1)>=(/*SSWARF2*//*X35posx*/(/*RF2*/(((T68*)_m))->_posx/*28*/)))&&((a1)<=((/*SSWARF2*//*X35posx*/(/*RF2*/(((T68*)_m))->_posx/*28*/))+(/*SSWARF2*//*X35width*/(/*RF2*/(((T68*)_m))->_width/*32*/)))))&&((a2)>=(/*SSWARF2*//*X35posy*/(/*RF2*/(((T68*)_m))->_posy/*24*/))))&&((a2)<=((/*SSWARF2*//*X35posy*/(/*RF2*/(((T68*)_m))->_posy/*24*/))+(/*SSWARF2*//*X35height*/(/*RF2*/(((T68*)_m))->_height/*36*/))))){
R=_i;
_i=(1)-(1);
}
else{
_i=(_i)-(1);
}
/*FI]*/
}
return R;
}


void r94connect_selection(T94* C,T2 a1,T2 a2){
T0* _m=NULL;
T2 _i=0;
(/*SFN*/C->_connecting_flag/*20*/)=0;
_i=r94select_machine(a1,a2);
/*[IF*/
if((_i)>=(1)){
_m=r41_px_64((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/),_i);
r94attempt_connect((/*RF2*/(C)->_selection/*22*/),_m);
}
/*FI]*/
}


void r94draw_connection(T94* C,T0* a1){
T0* _m2=NULL;
T0* _m1=NULL;
T5 _angle=0;
T0* _img=NULL;
T2 _dy=0;
T2 _dx=0;
T2 _y2=0;
T2 _x2=0;
T2 _y1=0;
T2 _x1=0;
_m1=(/*RF2*/(((T65*)a1))->_src/*8*/);
_m2=(/*RF2*/(((T65*)a1))->_dst/*4*/);
_x1=/*SSFRF4*//*X35centerx*/r68centerx(((T68*)_m1));
_y1=/*SSFRF4*//*X35centery*/r68centery(((T68*)_m1));
_x2=/*SSFRF4*//*X35centerx*/r68centerx(((T68*)_m2));
_y2=/*SSFRF4*//*X35centery*/r68centery(((T68*)_m2));
/*[IRF3.6aalinecolor*/{T94* C1=C;
T2 b1=_x1;
T2 b2=_y1;
T2 b3=_x2;
T2 b4=_y2;
T0* b5=r94white();
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
_dy=(_y2)-(_y1);
_dx=(_x2)-(_x1);
/*[IF*/
if((_dx)==(0)){
_angle=T2toT5(90);
}
else{
_angle=atan(((T5)(_dy))/(_dx));
_angle=((_angle)*(T2toT5(180)))/(T4toT5(3.14159265358979323846));
}
/*FI]*/
_angle=-(_angle);
/*[IF*/
if((_dx)<(0)){
_angle=(_angle)+(T2toT5(180));
}
/*FI]*/
_x1=((_x1)+(_x2))/(2);
_y1=((_y1)+(_y2))/(2);
r65put_xy(((T65*)a1),_x1,_y1);
/*[IRF3.6filledcirclecolor*/{T94* C1=C;
T2 b1=_x1;
T2 b2=_y1;
T2 b3=10;
T0* b4=r94white();
ext_filledcirclecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),b3,(/*RF2*/(((T51*)b4))->_to_gfx_integer/*8*/));
}/*]*/
/*[IRF3.6filledcirclecolor*/{T94* C1=C;
T2 b1=_x1;
T2 b2=_y1;
T2 b3=8;
T0* b4=r94green();
ext_filledcirclecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),b3,(/*RF2*/(((T51*)b4))->_to_gfx_integer/*8*/));
}/*]*/
{T50*n=new50();
/*[IRF3.1make*//*]*/
_img=((T0*)n);
}
r50rotozoom(((T50*)_img),r94arrow_image(),_angle,T4toT5(1.0));
_x2=(_x1)-((r50width(((T50*)_img)))/(2));
_y2=(_y1)-((r50height(((T50*)_img)))/(2));
/*[IRF3.6blit*/{T94* C1=C;
T0* b1=_img;
T2 b2=_x2;
T2 b3=_y2;
/*[IRF3.6blit*/{T50* C2=((T50*)b1);
T2 c1=(b2)+((/*RF2*/(C1)->_offsetx/*4*/));
T2 c2=(b3)+((/*RF2*/(C1)->_offsety/*8*/));
ext_blit_img((/*RF2*/(C2)->_ptr/*5*/),c1,c2);
}/*]*/
}/*]*/
r50free(((T50*)_img));
}


void r94clipped_move(T94* C,T0* a1,T2 a2,T2 a3){
T2 _y=0;
T2 _x=0;
_x=a2;
_y=a3;
/*[IF*/
if((_x)<(0)){
_x=0;
}
 else if((_x)>(((/*RF2*/(C)->_width/*12*/))-(/*SSWARF2*//*X35width*/(/*RF2*/(((T68*)a1))->_width/*32*/)))){
_x=((/*RF2*/(C)->_width/*12*/))-(/*SSWARF2*//*X35width*/(/*RF2*/(((T68*)a1))->_width/*32*/));
}
/*FI]*/
/*[IF*/
if((_y)<(0)){
_y=0;
}
 else if((_y)>(((/*RF2*/(C)->_height/*16*/))-(/*SSWARF2*//*X35height*/(/*RF2*/(((T68*)a1))->_height/*36*/)))){
_y=((/*RF2*/(C)->_height/*16*/))-(/*SSWARF2*//*X35height*/(/*RF2*/(((T68*)a1))->_height/*36*/));
}
/*FI]*/
((/*UT*/(void)((T33*)(r94song()))),r33move_to(a1,_x,_y));
}


void r94place_selection(T94* C,T2 a1,T2 a2){
(/*SFN*/C->_moving_flag/*21*/)=0;
r94clipped_move(C,(/*RF2*/(C)->_selection/*22*/),(a1)-((/*RF2*/(C)->_movestartx/*26*/)),(a2)-((/*RF2*/(C)->_movestarty/*30*/)));
}


T0* r94green(void){
if(fBC18green==0){fBC18green=1;{
{T51*n=new51();
oBC18green=((T0*)n);
r51make(n,0,127,0);
}
}}
return oBC18green;
}


void r94put_geometry(T94* C,T2 a1,T2 a2,T2 a3,T2 a4){
(/*SFN*/C->_offsetx/*4*/)=a1;
(/*SFN*/C->_offsety/*8*/)=a2;
(/*SFN*/C->_width/*12*/)=a3;
(/*SFN*/C->_height/*16*/)=a4;
}


void r94process_event(T94* C,T0* a1){
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43(ms94_39,(/*RF2*/(((T23*)a1))->_desc/*12*/))),((T0*)ms94_205)));
/*[IF*/
if(r7is_equal((T7*)((/*RF2*/(((T23*)a1))->_desc/*12*/)),((T0*)ms94_248415980))){
r94process_buttondown(C,a1);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T23*)a1))->_desc/*12*/)),((T0*)ms94_9936697))){
r94process_buttonup(C,a1);
}
 else if(r7is_equal((T7*)((/*RF2*/(((T23*)a1))->_desc/*12*/)),((T0*)ms94_2079105))){
r94process_key(C,(/*RF2*/(((T23*)a1))->_i1/*20*/));
}
/*FI]*/
}


T0* r94twin(T94* C){
T0* R=NULL;
R=((void*)new94());
*((T94*)R)=*C;
return R;
}


T0* r94white(void){
if(fBC18white==0){fBC18white=1;{
{T51*n=new51();
oBC18white=((T0*)n);
r51make(n,255,255,255);
}
}}
return oBC18white;
}
T0*oBC94arrow_image=NULL;
int fBC94arrow_image=0;


T0* r94arrow_image(void){
if(fBC94arrow_image==0){fBC94arrow_image=1;{
{T50*n=new50();
oBC94arrow_image=((T0*)n);
/*[IRF3.1make*//*]*/
}
r50new_arrow(((T50*)oBC94arrow_image));
}}
return oBC94arrow_image;
}


void r94select_edge(T2 a1,T2 a2){
T6 _done=0;
T2 _d=0;
T2 _r=0;
T0* _it=NULL;
_it=r66get_new_iterator((T66*)((/*RF2*/((T33*)(r94song()))->_connection_list/*21*/)));
r187start(((T187*)_it));
/*[IF*/
if(/*(IRF4.7is_off*/((/*RF2*/(((T187*)_it))->_current_link/*8*/))==(NULL)/*)*/){
_done=1;
}
/*FI]*/
while (!(_done))
{
_d=((/*RF2*/((T65*)(/*(IRF4.6item*/(/*RF2*/(((T67*)((/*RF2*/(((T187*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_x/*16*/))-(a1);
_r=(_d)*(_d);
_d=((/*RF2*/((T65*)(/*(IRF4.6item*/(/*RF2*/(((T67*)((/*RF2*/(((T187*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_y/*12*/))-(a2);
_r=((_d)*(_d))+(_r);
/*[IF*/
if((_r)<((10)*(10))){
r84put_string((T84*)(oBC1io),r7_px_43((T7*)(r7_px_43((T7*)(r7_px_43((T7*)(/*SSWARF2*//*X35name*/(/*RF2*/((T68*)((/*RF2*/((T65*)(/*(IRF4.6item*/(/*RF2*/(((T67*)((/*RF2*/(((T187*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_src/*8*/)))->_name/*4*/)),((T0*)ms94_27092))),/*SSWARF2*//*X35name*/(/*RF2*/((T68*)((/*RF2*/((T65*)(/*(IRF4.6item*/(/*RF2*/(((T67*)((/*RF2*/(((T187*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_dst/*4*/)))->_name/*4*/))),((T0*)ms94_10)));
r33delete_edge((T33*)(r94song()),/*(IRF4.6item*/(/*RF2*/(((T67*)((/*RF2*/(((T187*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/);
_done=1;
}
else{
r187next(((T187*)_it));
/*[IF*/
if(/*(IRF4.7is_off*/((/*RF2*/(((T187*)_it))->_current_link/*8*/))==(NULL)/*)*/){
_done=1;
}
/*FI]*/
}
/*FI]*/
}
}


void r94update(T94* C){
T0* _m=NULL;
T0* _it2=NULL;
T0* _it=NULL;
/*[IF*/
if((/*RF2*/(C)->_moving_flag/*21*/)){
ext_get_mouse_state();
r94clipped_move(C,(/*RF2*/(C)->_selection/*22*/),(r94last_mouse_x(C))-((/*RF2*/(C)->_movestartx/*26*/)),(r94last_mouse_y(C))-((/*RF2*/(C)->_movestarty/*30*/)));
}
 else if((/*RF2*/(C)->_connecting_flag/*20*/)){
ext_get_mouse_state();
/*[IRF3.6aalinecolor*/{T94* C1=C;
T2 b1=/*SSFRF4*//*X35centerx*/r68centerx((T68*)((/*RF2*/(C)->_selection/*22*/)));
T2 b2=/*SSFRF4*//*X35centery*/r68centery((T68*)((/*RF2*/(C)->_selection/*22*/)));
T2 b3=r94last_mouse_x(C);
T2 b4=r94last_mouse_y(C);
T0* b5=r94white();
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
}
/*FI]*/
_it2=r66get_new_iterator((T66*)((/*RF2*/((T33*)(r94song()))->_connection_list/*21*/)));
r187start(((T187*)_it2));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T187*)_it2))->_current_link/*8*/))==(NULL)/*)*/))
{
r94draw_connection(C,/*(IRF4.6item*/(/*RF2*/(((T67*)((/*RF2*/(((T187*)_it2))->_current_link/*8*/))))->_item/*4*/)/*)*/);
r187next(((T187*)_it2));
}
_it=r41get_new_iterator((T41*)(/*(IRF4.9machine_zorder*/(/*RF2*/((T33*)(r94song()))->_machine_zorder/*17*/)/*)*/));
X89start(_it);
while (!(X89is_off(_it)))
{
_m=X89item(_it);
/*[IRF3.6blit*/{T94* C1=C;
T0* b1=/*SSWARF2*//*X35image*/(/*RF2*/(((T68*)_m))->_image/*40*/);
T2 b2=/*SSWARF2*//*X35posx*/(/*RF2*/(((T68*)_m))->_posx/*28*/);
T2 b3=/*SSWARF2*//*X35posy*/(/*RF2*/(((T68*)_m))->_posy/*24*/);
/*[IRF3.6blit*/{T50* C2=((T50*)b1);
T2 c1=(b2)+((/*RF2*/(C1)->_offsetx/*4*/));
T2 c2=(b3)+((/*RF2*/(C1)->_offsety/*8*/));
ext_blit_img((/*RF2*/(C2)->_ptr/*5*/),c1,c2);
}/*]*/
}/*]*/
X89next(_it);
}
}


void r94process_buttondown(T94* C,T0* a1){
/*[INSPECT*/
{int z1=(/*RF2*/(((T23*)a1))->_i1/*20*/);
switch(z1){
case 1:
/*[IF*/
if(int_and((/*RF2*/(((T23*)a1))->_kmod/*24*/),3)){
r94select_machine_for_connect(C,(/*RF2*/(((T23*)a1))->_x/*8*/),(/*RF2*/(((T23*)a1))->_y/*4*/));
}
else{
r94select_machine_for_move(C,(/*RF2*/(((T23*)a1))->_x/*8*/),(/*RF2*/(((T23*)a1))->_y/*4*/));
/*[IF*/
if(((/*RF2*/(C)->_selection/*22*/))==((void*)(NULL))){
r94select_edge((/*RF2*/(((T23*)a1))->_x/*8*/),(/*RF2*/(((T23*)a1))->_y/*4*/));
}
/*FI]*/
}
/*FI]*/
break;
}
}/*INSPECT]*/
}


void r188put_wave_index(T188* C,T2 a1){
(/*SFN*/C->_wave_index/*28*/)=a1;
(/*SFN*/C->_wave/*24*/)=r76at((T76*)((/*RF2*/((T33*)(r188song()))->_wave_table/*29*/)),(/*RF2*/(C)->_wave_index/*28*/));
(/*SFN*/C->_wave_length/*32*/)=(/*RF2*/((T75*)((/*RF2*/(C)->_wave/*24*/)))->_length/*20*/);
(/*SFN*/C->_modulus/*36*/)=((/*RF2*/(C)->_wave_length/*32*/))*(1024);
(/*SFN*/C->_freq/*20*/)=r5rounded(((T2toT5(1024))*((/*RF2*/(C)->_d_cache/*4*/)))/((/*RF2*/((T75*)((/*RF2*/(C)->_wave/*24*/)))->_root_freq/*4*/)));
}


void r188volslidedown(T188* C,T2 a1){
(/*SFN*/C->_volslide/*45*/)=((T5)(-(a1)))/((256)*(512));
}


T5 r188next_sample(T188* C){
T5 R=0;
/*[IF*/
if((/*RF2*/(C)->_playing/*40*/)){
R=(r75get_data_double((T75*)((/*RF2*/(C)->_wave/*24*/)),((/*RF2*/(C)->_x/*41*/))/(1024)))*((/*RF2*/(C)->_vol/*12*/));
(/*SFN*/C->_vol/*12*/)=((/*RF2*/(C)->_vol/*12*/))+((/*RF2*/(C)->_volslide/*45*/));
/*[IF*/
if(((/*RF2*/(C)->_vol/*12*/))<(T4toT5(0.0))){
(/*SFN*/C->_vol/*12*/)=T4toT5(0.0);
}
/*FI]*/
(/*SFN*/C->_x/*41*/)=((/*RF2*/(C)->_x/*41*/))+((/*RF2*/(C)->_freq/*20*/));
/*[IF*/
if(((/*RF2*/(C)->_x/*41*/))>=((/*RF2*/(C)->_modulus/*36*/))){
(/*SFN*/C->_playing/*40*/)=0;
}
/*FI]*/
}
/*FI]*/
return R;
}


T0* r188song(void){
if(fBC20song==0){fBC20song=1;{
{T33*n=new33();
oBC20song=((T0*)n);
r33make(n);
}
}}
return oBC20song;
}


void r188play_freq(T188* C,T5 a1){
(/*SFN*/C->_playing/*40*/)=1;
/*[IRF3.3put_freq*/((((T188*)(C)))->_d_cache/*4*/)=(a1);
/*]*/
/*[IRF3.3put_vol*/((((T188*)(C)))->_vol/*12*/)=(T4toT5(1.0));
/*]*/
(/*SFN*/C->_volslide/*45*/)=T4toT5(0.0);
(/*SFN*/C->_x/*41*/)=0;
}


T0* r188twin(T188* C){
T0* R=NULL;
R=((void*)new188());
*((T188*)R)=*C;
return R;
}


void r93process_text_edit_key(T93* C,T2 a1){
/*[IF*/
if(((a1)>=(48))&&((a1)<=(57))){
r93text_append(C,((T3)(a1)));
}
 else if(((a1)>=(97))&&((a1)<=(122))){
r93text_append(C,((T3)((a1)-(32))));
}
 else if((a1)==(8)){
r93text_remove_last(C);
}
/*FI]*/
}


T0* r93blue(void){
if(fBC18blue==0){fBC18blue=1;{
{T51*n=new51();
oBC18blue=((T0*)n);
r51make(n,0,0,127);
}
}}
return oBC18blue;
}


void r93handle_event(T93* C,T0* a1){
/*[IRF3.3put_x*/((((T23*)(((T23*)a1))))->_x/*8*/)=(((/*RF2*/(((T23*)a1))->_x/*8*/))-((/*RF2*/(C)->_offsetx/*4*/)));
/*]*/
/*[IRF3.3put_y*/((((T23*)(((T23*)a1))))->_y/*4*/)=(((/*RF2*/(((T23*)a1))->_y/*4*/))-((/*RF2*/(C)->_offsety/*8*/)));
/*]*/
r93process_event(C,a1);
}


void r93process_key(T93* C,T0* a1){
/*[IF*/
if(int_and((/*RF2*/(((T23*)a1))->_kmod/*24*/),192)){
/*[INSPECT*/
{int z1=(/*RF2*/(((T23*)a1))->_i1/*20*/);
switch(z1){
case 109:
r93put_machine(C,r33next_machine((T33*)(r93song()),(/*RF2*/(C)->_machine/*44*/)));
break;
case 112:
/*[IF*/
if(((/*RF2*/(C)->_pattern/*48*/))!=((void*)(NULL))){
(/*SFN*/C->_pattern/*48*/)=/*SSFRF4*//*X35next_pattern*/r68next_pattern((T68*)((/*RF2*/(C)->_machine/*44*/)),(/*RF2*/(C)->_pattern/*48*/));
}
/*FI]*/
break;
case 48:
(/*SFN*/C->_pattern/*48*/)=/*SSWARF2*//*X35setup_pattern*/(/*RF2*/((T68*)((/*RF2*/(C)->_machine/*44*/)))->_setup_pattern/*20*/);
break;
case 13:
(/*SFN*/C->_pattern/*48*/)=X35new_pattern_autoname((/*RF2*/(C)->_machine/*44*/));
break;
}
}/*INSPECT]*/
}
else{
/*[IF*/
if(((/*RF2*/(C)->_pattern/*48*/))!=((void*)(NULL))){
r93process_edit_key(C,(/*RF2*/(((T23*)a1))->_i1/*20*/));
}
/*FI]*/
}
/*FI]*/
}


void r93draw_spreadsheet(T93* C){
T0* _it=NULL;
T2 _c=0;
T2 _r=0;
/*[IRF3.6fill_rect*/{T93* C1=C;
T2 b1=(30)+(((/*RF2*/(C)->_cursorc/*32*/))*(50));
T2 b2=(40)+(((/*RF2*/(C)->_cursorr/*28*/))*(20));
T2 b3=50;
T2 b4=20;
T0* b5=r93blue();
ext_fill_rect((b1)+((/*RF2*/(C1)->_offsetx/*4*/)),(b2)+((/*RF2*/(C1)->_offsety/*8*/)),b3,b4,(/*RF2*/(((T51*)b5))->_to_integer/*4*/));
}/*]*/
/*[IRF3.6aalinecolor*/{T93* C1=C;
T2 b1=0;
T2 b2=40;
T2 b3=((/*RF2*/(C)->_width/*12*/))-(1);
T2 b4=40;
T0* b5=r93white();
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
/*[IRF3.6aalinecolor*/{T93* C1=C;
T2 b1=30;
T2 b2=20;
T2 b3=30;
T2 b4=((/*RF2*/(C)->_height/*16*/))-(1);
T0* b5=r93white();
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
_r=0;
while (!((_r)==((/*RF2*/(C)->_maxr/*36*/))))
{
/*[IRF3.6draw_row_label*/{T93* C1=C;
T2 b1=_r;
T0* b2=r2to_string(((/*RF2*/(C)->_originr/*24*/))+(_r));
r93write(C1,0,(40)+((b1)*(20)),b2);
}/*]*/
_r=(_r)+(1);
}
_c=0;
while (!((_c)==((/*RF2*/(C)->_maxc/*40*/))))
{
/*[IRF3.6draw_col_label*/{T93* C1=C;
T2 b1=_c;
T0* b2=r2to_string(((/*RF2*/(C)->_originc/*20*/))+(_c));
r93write(C1,(30)+((b1)*(50)),20,b2);
}/*]*/
_c=(_c)+(1);
}
_r=0;
while (!((_r)==((/*RF2*/(C)->_maxr/*36*/))))
{
_c=0;
while (!((_c)==((/*RF2*/(C)->_maxc/*40*/))))
{
/*[IF*/
if(/*(IRF4.6has*/r55has(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_originr/*24*/))+(_r),((/*RF2*/(C)->_originc/*20*/))+(_c))/*)*/){
r93write(C,(30)+((_c)*(50)),(40)+((_r)*(20)),/*(IRF4.6at*/r55at(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_originr/*24*/))+(_r),((/*RF2*/(C)->_originc/*20*/))+(_c))/*)*/);
}
/*FI]*/
_c=(_c)+(1);
}
_r=(_r)+(1);
}
_it=r106get_new_iterator((T106*)(r33get_playing_rows((T33*)(r93song()),(/*RF2*/(C)->_pattern/*48*/))));
X97start(_it);
while (!(X97is_off(_it)))
{
_r=(40)+(((X97item(_it))-((/*RF2*/(C)->_originr/*24*/)))*(20));
/*[IF*/
if(((_r)>=(40))&&((_r)<((/*RF2*/(C)->_height/*16*/)))){
/*[IRF3.6aalinecolor*/{T93* C1=C;
T2 b1=0;
T2 b2=_r;
T2 b3=((/*RF2*/(C)->_width/*12*/))-(1);
T2 b4=_r;
T0* b5=r93white();
ext_aalinecolor(((/*RF2*/(C1)->_offsetx/*4*/))+(b1),((/*RF2*/(C1)->_offsety/*8*/))+(b2),((/*RF2*/(C1)->_offsetx/*4*/))+(b3),((/*RF2*/(C1)->_offsety/*8*/))+(b4),(/*RF2*/(((T51*)b5))->_to_gfx_integer/*8*/));
}/*]*/
}
/*FI]*/
X97next(_it);
}
}


T0* r93song(void){
if(fBC20song==0){fBC20song=1;{
{T33*n=new33();
oBC20song=((T0*)n);
r33make(n);
}
}}
return oBC20song;
}


void r93text_remove_last(T93* C){
T0* _s=NULL;
/*[IF*/
if(/*(IRF4.6has*/r55has(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_cursorr/*28*/))+((/*RF2*/(C)->_originr/*24*/)),((/*RF2*/(C)->_cursorc/*32*/))+((/*RF2*/(C)->_originc/*20*/)))/*)*/){
_s=/*(IRF4.6at*/r55at(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_cursorr/*28*/))+((/*RF2*/(C)->_originr/*24*/)),((/*RF2*/(C)->_cursorc/*32*/))+((/*RF2*/(C)->_originc/*20*/)))/*)*/;
r7remove_last(((T7*)_s),1);
/*[IF*/
if(/*(IRF4.7is_empty*/((/*RF2*/(((T7*)_s))->_count/*8*/))==(0)/*)*/){
/*[IRF3.5remove*/r55remove(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_cursorr/*28*/))+((/*RF2*/(C)->_originr/*24*/)),((/*RF2*/(C)->_cursorc/*32*/))+((/*RF2*/(C)->_originc/*20*/)));
/*]*/
}
/*FI]*/
}
/*FI]*/
}


void r93write(T93* C,T2 a1,T2 a2,T0* a3){
T0* _img=NULL;
{T50*n=new50();
/*[IRF3.1make*//*]*/
_img=((T0*)n);
}
r50render_string(((T50*)_img),a3);
/*[IRF3.6blit*/{T50* C1=((T50*)_img);
T2 b1=((/*RF2*/(C)->_offsetx/*4*/))+(a1);
T2 b2=((/*RF2*/(C)->_offsety/*8*/))+(a2);
ext_blit_img((/*RF2*/(C1)->_ptr/*5*/),b1,b2);
}/*]*/
r50free(((T50*)_img));
}


void r93put_machine(T93* C,T0* a1){
(/*SFN*/C->_machine/*44*/)=a1;
/*[IF*/
if(/*(IRF4.7is_empty*/((/*RF2*/((T62*)(/*SSWARF2*//*X35pattern_table*/(/*RF2*/((T68*)((/*RF2*/(C)->_machine/*44*/)))->_pattern_table/*12*/)))->_count/*12*/))==(0)/*)*/){
(/*SFN*/C->_pattern/*48*/)=NULL;
}
else{
(/*SFN*/C->_pattern/*48*/)=/*(IRF4.6first*/(/*RF2*/(((T61*)((/*RF2*/((T60*)(/*SSWARF2*//*X35pattern_list*/(/*RF2*/((T68*)((/*RF2*/(C)->_machine/*44*/)))->_pattern_list/*16*/)))->_first_link/*8*/))))->_item/*4*/)/*)*/;
}
/*FI]*/
}


void r93move_cursor_up(T93* C,T2 a1){
/*[IF*/
if(((/*RF2*/(C)->_cursorr/*28*/))>=(a1)){
(/*SFN*/C->_cursorr/*28*/)=((/*RF2*/(C)->_cursorr/*28*/))-(a1);
}
else{
/*[IF*/
if(((/*RF2*/(C)->_originr/*24*/))>=(a1)){
(/*SFN*/C->_originr/*24*/)=((/*RF2*/(C)->_originr/*24*/))-(a1);
}
else{
(/*SFN*/C->_originr/*24*/)=0;
}
/*FI]*/
}
/*FI]*/
}


void r93text_append(T93* C,T3 a1){
T0* _s=NULL;
/*[IF*/
if(/*(IRF4.6has*/r55has(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_cursorr/*28*/))+((/*RF2*/(C)->_originr/*24*/)),((/*RF2*/(C)->_cursorc/*32*/))+((/*RF2*/(C)->_originc/*20*/)))/*)*/){
_s=/*(IRF4.6at*/r55at(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),((/*RF2*/(C)->_cursorr/*28*/))+((/*RF2*/(C)->_originr/*24*/)),((/*RF2*/(C)->_cursorc/*32*/))+((/*RF2*/(C)->_originc/*20*/)))/*)*/;
}
else{
{T7*n=new7();
r7make(n,10);
_s=((T0*)n);
}
}
/*FI]*/
r7add_last(((T7*)_s),a1);
/*[IRF3.5put*/r55put(((T55*)((/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_commands/*8*/))),_s,((/*RF2*/(C)->_cursorr/*28*/))+((/*RF2*/(C)->_originr/*24*/)),((/*RF2*/(C)->_cursorc/*32*/))+((/*RF2*/(C)->_originc/*20*/)));
/*]*/
}


void r93make(T93* C,T2 a1,T2 a2,T2 a3,T2 a4){
r93put_geometry(C,a1,a2,a3,a4);
(/*SFN*/C->_maxc/*40*/)=(((/*RF2*/(C)->_width/*12*/))/(50))-(1);
(/*SFN*/C->_maxr/*36*/)=(((/*RF2*/(C)->_height/*16*/))/(20))-(1);
}


void r93put_geometry(T93* C,T2 a1,T2 a2,T2 a3,T2 a4){
(/*SFN*/C->_offsetx/*4*/)=a1;
(/*SFN*/C->_offsety/*8*/)=a2;
(/*SFN*/C->_width/*12*/)=a3;
(/*SFN*/C->_height/*16*/)=a4;
}


void r93process_event(T93* C,T0* a1){
/*[IF*/
if(r7is_equal((T7*)((/*RF2*/(((T23*)a1))->_desc/*12*/)),((T0*)ms93_2079105))){
r93process_key(C,a1);
}
/*FI]*/
}


T0* r93twin(T93* C){
T0* R=NULL;
R=((void*)new93());
*((T93*)R)=*C;
return R;
}


T0* r93white(void){
if(fBC18white==0){fBC18white=1;{
{T51*n=new51();
oBC18white=((T0*)n);
r51make(n,255,255,255);
}
}}
return oBC18white;
}


void r93process_edit_key(T93* C,T2 a1){
/*[INSPECT*/
{int z1=a1;
switch(z1){
case 275:
/*[IF*/
if(((/*RF2*/(C)->_cursorc/*32*/))<(((/*RF2*/(C)->_maxc/*40*/))-(1))){
(/*SFN*/C->_cursorc/*32*/)=((/*RF2*/(C)->_cursorc/*32*/))+(1);
}
else{
(/*SFN*/C->_originc/*20*/)=((/*RF2*/(C)->_originc/*20*/))+(1);
}
/*FI]*/
break;
case 276:
/*[IF*/
if(((/*RF2*/(C)->_cursorc/*32*/))>(0)){
(/*SFN*/C->_cursorc/*32*/)=((/*RF2*/(C)->_cursorc/*32*/))-(1);
}
else{
/*[IF*/
if(((/*RF2*/(C)->_originc/*20*/))>(0)){
(/*SFN*/C->_originc/*20*/)=((/*RF2*/(C)->_originc/*20*/))-(1);
}
/*FI]*/
}
/*FI]*/
break;
case 274:
r93move_cursor_down(C,1);
break;
case 273:
r93move_cursor_up(C,1);
break;
default:;
r93process_text_edit_key(C,a1);
}
}/*INSPECT]*/
}


void r93move_cursor_down(T93* C,T2 a1){
/*[IF*/
if(((/*RF2*/(C)->_cursorr/*28*/))<(((/*RF2*/(C)->_maxr/*36*/))-(a1))){
(/*SFN*/C->_cursorr/*28*/)=((/*RF2*/(C)->_cursorr/*28*/))+(a1);
}
else{
(/*SFN*/C->_originr/*24*/)=((/*RF2*/(C)->_originr/*24*/))+(a1);
}
/*FI]*/
}


void r93update(T93* C){
r93write(C,0,0,r7_px_43(ms93_39610347,/*SSWARF2*//*X35name*/(/*RF2*/((T68*)((/*RF2*/(C)->_machine/*44*/)))->_name/*4*/)));
/*[IF*/
if(((/*RF2*/(C)->_pattern/*48*/))!=((void*)(NULL))){
r93write(C,300,0,r7_px_43(ms93_41083572,(/*RF2*/((T52*)((/*RF2*/(C)->_pattern/*48*/)))->_name/*4*/)));
r93draw_spreadsheet(C);
}
else{
r93write(C,(((/*RF2*/(C)->_width/*12*/))/(2))-(100),((/*RF2*/(C)->_height/*16*/))/(2),((T0*)ms93_574977583));
}
/*FI]*/
}


T5 r75get_data_double(T75* C,T2 a1){
T5 R=0;
T2 _n=0;
_n=(T3code(r184item((T184*)((/*RF2*/(C)->_data/*24*/)),(2)*(a1))))+((256)*(T3code(r184item((T184*)((/*RF2*/(C)->_data/*24*/)),((2)*(a1))+(1)))));
/*[IF*/
if((_n)>=(32768)){
_n=(_n)-(65536);
}
/*FI]*/
R=(((T5)(_n))/(65536))*((/*RF2*/(C)->_volume/*12*/));
return R;
}


T0* r75twin(T75* C){
T0* R=NULL;
R=((void*)new75());
*((T75*)R)=*C;
return R;
}


void r75put_name(T75* C,T0* a1){
{T7*n=new7();
r7copy(n,a1);
(/*SFN*/C->_name/*28*/)=((T0*)n);
}
}


T0* r23twin(T23* C){
T0* R=NULL;
R=((void*)new23());
*((T23*)R)=*C;
return R;
}


void r23desc_from_external(T23* C,T8 a1){
{T7*n=new7();
r7from_external_copy(n,a1);
(/*SFN*/C->_desc/*12*/)=((T0*)n);
}
}


void r23update(T23* C){
/*[IRF3.3put_x*/((((T23*)(C)))->_x/*8*/)=(export_current_x());
/*]*/
/*[IRF3.3put_y*/((((T23*)(C)))->_y/*4*/)=(export_current_y());
/*]*/
/*[IRF3.3put_i1*/((((T23*)(C)))->_i1/*20*/)=(export_current_i1());
/*]*/
/*[IRF3.3put_i2*/((((T23*)(C)))->_i2/*16*/)=(export_current_i2());
/*]*/
/*[IRF3.3put_kmod*/((((T23*)(C)))->_kmod/*24*/)=(export_current_kmod());
/*]*/
r23desc_from_external(C,export_current_desc());
}


T0* r33next_machine(T33* C,T0* a1){
T0* R=NULL;
T2 _i=0;
_i=(r41fast_index_of((T41*)((/*RF2*/(C)->_machine_list/*13*/)),a1))+(1);
/*[IF*/
if((_i)>((/*RF2*/((T41*)((/*RF2*/(C)->_machine_list/*13*/)))->_upper/*4*/))){
_i=1;
}
/*FI]*/
R=r41_px_64((T41*)((/*RF2*/(C)->_machine_list/*13*/)),_i);
return R;
}


T0* r33at(T33* C,T2 a1,T2 a2){
T0* R=NULL;
R=r57at((T57*)((/*RF2*/((T79*)(r80_px_64((T80*)((/*RF2*/(C)->_tracks/*25*/)),a2)))->_commands/*8*/)),a1);
return R;
}
T0*oBC34machine_class_table=NULL;
int fBC34machine_class_table=0;


T0* r33machine_class_table(void){
if(fBC34machine_class_table==0){fBC34machine_class_table=1;{
T0* _m=NULL;
{T45*n=new45();
oBC34machine_class_table=((T0*)n);
/*[IRF3.4make*/r45with_capacity(n,193);
/*]*/
}
{T74*n=new74();
/*[IRF3.6register*/{T74* C1=n;
T0* b1=oBC34machine_class_table;
r45put(((T45*)b1),(T0*)C1,((T0*)ms74_265794));
}/*]*/
_m=((T0*)n);
}
{T73*n=new73();
/*[IRF3.6register*/{T73* C1=n;
T0* b1=oBC34machine_class_table;
r45put(((T45*)b1),(T0*)C1,((T0*)ms73_1325625));
}/*]*/
_m=((T0*)n);
}
{T72*n=new72();
/*[IRF3.6register*/{T72* C1=n;
T0* b1=oBC34machine_class_table;
r45put(((T45*)b1),(T0*)C1,((T0*)ms72_319144));
}/*]*/
_m=((T0*)n);
}
{T70*n=new70();
/*[IRF3.6register*/{T70* C1=n;
T0* b1=oBC34machine_class_table;
r45put(((T45*)b1),(T0*)C1,((T0*)ms70_2425));
}/*]*/
_m=((T0*)n);
}
{T68*n=new68();
/*[IRF3.6register*/{T68* C1=n;
T0* b1=oBC34machine_class_table;
r45put(((T45*)b1),(T0*)C1,((T0*)ms68_33463794));
}/*]*/
_m=((T0*)n);
}
}}
return oBC34machine_class_table;
}


void r33move_to(T0* a1,T2 a2,T2 a3){
/*SSPRF3*//*X35move_to*/r68move_to(((T68*)a1),a2,a3);
}


T5 r33next_sample(T33* C){
T5 R=0;
/*[IF*/
if((/*RF2*/(C)->_play_flag/*8*/)){
/*[IF*/
if(/*(IRF4.7new_beat*/((/*RF2*/(C)->_sample_mod_tick/*57*/))==(0)/*)*/){
r33boom(C);
}
/*FI]*/
r33increment_sample_count(C);
R=X35next_sample((/*RF2*/(C)->_master/*4*/));
}
/*FI]*/
return R;
}


T0* r33new_machine_autoname(T33* C,T0* a1){
T0* R=NULL;
T0* _m=NULL;
T2 _i=0;
T0* _s=NULL;
_m=r45at((T45*)(r33machine_class_table()),a1);
_s=X35id(_m);
/*[IF*/
if(r45has((T45*)((/*RF2*/(C)->_machine_table/*9*/)),_s)){
_i=2;
while (!(!(r45has((T45*)((/*RF2*/(C)->_machine_table/*9*/)),r7_px_43(((T7*)_s),r2to_string(_i))))))
{
_i=(_i)+(1);
}
_s=r7_px_43(((T7*)_s),r2to_string(_i));
}
/*FI]*/
R=r33add_machine(C,_m,_s);
return R;
}


void r33boom(T33* C){
T0* _itm=NULL;
T0* _it=NULL;
/*[IF*/
if(((/*RF2*/(C)->_beat_count/*33*/))>=((/*RF2*/(C)->_end_beat/*37*/))){
(/*SFN*/C->_beat_count/*33*/)=0;
}
/*FI]*/
_itm=r41get_new_iterator((T41*)((/*RF2*/(C)->_machine_list/*13*/)));
X89start(_itm);
while (!(X89is_off(_itm)))
{
X35boom(X89item(_itm));
X89next(_itm);
}
_it=r80get_new_iterator((T80*)((/*RF2*/(C)->_tracks/*25*/)));
r113start(((T113*)_it));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T113*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
r79boom((T79*)(/*(IRF4.6item*/(/*RF2*/(((T81*)((/*RF2*/(((T113*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/),(/*RF2*/(C)->_beat_count/*33*/));
r113next(((T113*)_it));
}
(/*SFN*/C->_beat_count/*33*/)=((/*RF2*/(C)->_beat_count/*33*/))+(1);
}


void r33jump_to(T33* C,T2 a1){
(/*SFN*/C->_sample_mod_tick/*57*/)=0;
(/*SFN*/C->_beat_count/*33*/)=a1;
}


void r33make(T33* C){
{T41*n=new41();
r41make(n);
(/*SFN*/C->_machine_zorder/*17*/)=((T0*)n);
}
{T45*n=new45();
/*[IRF3.4make*/r45with_capacity(n,193);
/*]*/
(/*SFN*/C->_machine_table/*9*/)=((T0*)n);
}
{T41*n=new41();
r41make(n);
(/*SFN*/C->_machine_list/*13*/)=((T0*)n);
}
{T66*n=new66();
r66make(n);
(/*SFN*/C->_connection_list/*21*/)=((T0*)n);
}
{T80*n=new80();
r80make(n);
(/*SFN*/C->_tracks/*25*/)=((T0*)n);
}
{T76*n=new76();
/*[IRF3.4make*/r76with_capacity(n,193);
/*]*/
(/*SFN*/C->_wave_table/*29*/)=((T0*)n);
}
(/*SFN*/C->_master/*4*/)=r33new_machine(C,((T0*)ms33_319144a),((T0*)ms33_319144));
/*SSPRF3*//*X35move_to*/r68move_to((T68*)((/*RF2*/(C)->_master/*4*/)),((638)-(/*SSWARF2*//*X35width*/(/*RF2*/((T68*)((/*RF2*/(C)->_master/*4*/)))->_width/*32*/)))/(2),((438)-(/*SSWARF2*//*X35height*/(/*RF2*/((T68*)((/*RF2*/(C)->_master/*4*/)))->_height/*36*/)))/(2));
(/*SFN*/C->_end_beat/*37*/)=16;
}


void r33calculate_samples_per_tick(T33* C){
(/*SFN*/C->_sample_mod_tick/*57*/)=0;
(/*SFN*/C->_samples_per_tick/*65*/)=r5rounded(((T5)((60)*(44100)))/(((/*RF2*/(C)->_bpm/*49*/))*((/*RF2*/(C)->_tpb/*53*/))));
}


void r33import_buzz(T33* C,T0* a1){
T0* _bc=NULL;
{T128*n=new128();
/*[IRF3.1make*//*]*/
_bc=((T0*)n);
}
r128convert((T0*)C,a1);
}


T6 r33has(T33* C,T2 a1,T2 a2){
T6 R=0;
R=r57has((T57*)((/*RF2*/((T79*)(r80_px_64((T80*)((/*RF2*/(C)->_tracks/*25*/)),a2)))->_commands/*8*/)),a1);
return R;
}


T0* r33add_machine(T33* C,T0* a1,T0* a2){
T0* R=NULL;
R=X35make_instance(a1,a2);
r45put((T45*)((/*RF2*/(C)->_machine_table/*9*/)),R,a2);
r41add_last((T41*)((/*RF2*/(C)->_machine_zorder/*17*/)),R);
r41add_last((T41*)((/*RF2*/(C)->_machine_list/*13*/)),R);
return R;
}


void r33save(T33* C,T0* a1){
T0* _m=NULL;
T0* _it=NULL;
_it=r41get_new_iterator((T41*)((/*RF2*/(C)->_machine_zorder/*17*/)));
X89start(_it);
while (!(X89is_off(_it)))
{
_m=X89item(_it);
r82start_machine(((T82*)a1),/*SSWARF2*//*X35name*/(/*RF2*/(((T68*)_m))->_name/*4*/));
/*[IRF3.6put_machine_class*/{T82* C1=((T82*)a1);
T0* b1=X35id(_m);
r82put_line(C1,r7_px_43((T7*)(r7_px_43(ms82_1962444,b1)),((T0*)ms82_34a)));
}/*]*/
r82put_machine_pos(((T82*)a1),/*SSWARF2*//*X35posx*/(/*RF2*/(((T68*)_m))->_posx/*28*/),/*SSWARF2*//*X35posy*/(/*RF2*/(((T68*)_m))->_posy/*24*/));
r82end_machine(((T82*)a1));
X89next(_it);
}
_it=r41get_new_iterator((T41*)((/*RF2*/(C)->_machine_zorder/*17*/)));
r82start_zorder(((T82*)a1));
X89start(_it);
while (!(X89is_off(_it)))
{
/*[IRF3.6put_machine_name*/{T82* C1=((T82*)a1);
T0* b1=/*SSWARF2*//*X35name*/(/*RF2*/((T68*)(X89item(_it)))->_name/*4*/);
r82put_line(C1,r7_px_43((T7*)(r7_px_43(ms82_52110219,b1)),((T0*)ms82_34)));
}/*]*/
X89next(_it);
}
r82end_zorder(((T82*)a1));
}


void r33setup_machines(T33* C){
T0* _it=NULL;
_it=r41get_new_iterator((T41*)((/*RF2*/(C)->_machine_list/*13*/)));
X89start(_it);
while (!(X89is_off(_it)))
{
/*SSPRF3*//*X35setup*//*[IRF3.5setup*/r52instant_execute(((T52*)((/*RF2*/((T68*)(X89item(_it)))->_setup_pattern/*20*/))));
/*]*/
X89next(_it);
}
}


void r33put_bpm_tpb(T33* C,T2 a1,T2 a2){
(/*SFN*/C->_bpm/*49*/)=a1;
(/*SFN*/C->_tpb/*53*/)=a2;
r33calculate_samples_per_tick(C);
}


T0* r33get_playing_rows(T33* C,T0* a1){
T0* R=NULL;
T0* _it=NULL;
{T106*n=new106();
r106make(n);
R=((T0*)n);
}
_it=r80get_new_iterator((T80*)((/*RF2*/(C)->_tracks/*25*/)));
r113start(((T113*)_it));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T113*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
/*[IF*/
if(((/*RF2*/((T79*)(/*(IRF4.6item*/(/*RF2*/(((T81*)((/*RF2*/(((T113*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_playing_pattern/*12*/))==((void*)(a1))){
r106add_last(((T106*)R),((/*RF2*/(C)->_beat_count/*33*/))-((/*RF2*/((T79*)(/*(IRF4.6item*/(/*RF2*/(((T81*)((/*RF2*/(((T113*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/))->_offset/*16*/)));
}
/*FI]*/
r113next(((T113*)_it));
}
return R;
}


T0* r33twin(T33* C){
T0* R=NULL;
R=((void*)new33());
*((T33*)R)=*C;
return R;
}


void r33increment_sample_count(T33* C){
(/*SFN*/C->_sample_count/*61*/)=((/*RF2*/(C)->_sample_count/*61*/))+(1);
(/*SFN*/C->_sample_mod_tick/*57*/)=((/*RF2*/(C)->_sample_mod_tick/*57*/))+(1);
/*[IF*/
if(((/*RF2*/(C)->_sample_mod_tick/*57*/))==((/*RF2*/(C)->_samples_per_tick/*65*/))){
(/*SFN*/C->_sample_mod_tick/*57*/)=0;
}
/*FI]*/
}


void r33connect(T33* C,T0* a1,T0* a2){
T0* _edge=NULL;
{T65*n=new65();
r65make(n,a1,a2);
_edge=((T0*)n);
}
r66add_last((T66*)((/*RF2*/(C)->_connection_list/*21*/)),_edge);
/*SSPRF3*//*X35add_inedge*//*[IRF3.5add_inedge*/r66add_last(((T66*)((/*RF2*/(((T68*)a2))->_in_connection/*8*/))),_edge);
/*]*/
}


void r33delete_edge(T33* C,T0* a1){
T2 _i=0;
_i=r66fast_index_of((T66*)((/*RF2*/(C)->_connection_list/*21*/)),a1);
r66remove((T66*)((/*RF2*/(C)->_connection_list/*21*/)),_i);
/*SSPRF3*//*X35remove_inedge*//*[IRF3.6remove_inedge*/{T68* C1=(T68*)((/*RF2*/(((T65*)a1))->_dst/*4*/));
T0* b1=a1;
r66remove((T66*)((/*RF2*/(C1)->_in_connection/*8*/)),r66fast_index_of((T66*)((/*RF2*/(C1)->_in_connection/*8*/)),b1));
}/*]*/
}


T0* r33new_machine(T33* C,T0* a1,T0* a2){
T0* R=NULL;
T0* _m=NULL;
_m=r45at((T45*)(r33machine_class_table()),a2);
R=r33add_machine(C,_m,a1);
return R;
}


void r33rewind(T33* C){
T0* _it=NULL;
(/*SFN*/C->_beat_count/*33*/)=0;
_it=r80get_new_iterator((T80*)((/*RF2*/(C)->_tracks/*25*/)));
r113start(((T113*)_it));
while (!(/*(IRF4.7is_off*/((/*RF2*/(((T113*)_it))->_current_link/*8*/))==(NULL)/*)*/))
{
r79rewind((T79*)(/*(IRF4.6item*/(/*RF2*/(((T81*)((/*RF2*/(((T113*)_it))->_current_link/*8*/))))->_item/*4*/)/*)*/));
r113next(((T113*)_it));
}
r33setup_machines(C);
}


void r33add_track(T33* C,T0* a1){
T0* _t=NULL;
{T79*n=new79();
r79make(n,a1);
_t=((T0*)n);
}
r80add_last((T80*)((/*RF2*/(C)->_tracks/*25*/)),_t);
}

